<?php

$behavior = [
    0 => '/command_definitions/*/metadata/actor_states/*',
    1 => '/command_definitions/*/metadata/foreign_target/owner_states/*',
    2 => '/command_definitions/*/metadata/foreign_target/terrain_keys/*',
    3 => '/command_definitions/*/metadata/neutral_target/terrain_keys/*',
    4 => '/command_definitions/*/target_facility_keys/*',
    5 => '/command_definitions/*/target_terrain_keys/*',
    6 => 'allowed',
    7 => 'canonical_unit',
    8 => 'capital_core',
    9 => 'consumes_turn',
    10 => 'default_selector_value',
    11 => 'directions',
    12 => 'enabled',
    13 => 'execution_deferred',
    14 => 'execution_phase',
    15 => 'facility',
    16 => 'facility_key',
    17 => 'facility_scale',
    18 => 'fixed_cost_setting',
    19 => 'future_expand_command',
    20 => 'initial_scale_from_facility_definition',
    21 => 'key',
    22 => 'legacy_command',
    23 => 'monster_key',
    24 => 'monster_occupancy',
    25 => 'nullable',
    26 => 'oil_search_effect_key',
    27 => 'operating_condition',
    28 => 'output_resource_key',
    29 => 'owner',
    30 => 'owner_overbuild_effect',
    31 => 'per_shot_cost',
    32 => 'population',
    33 => 'price_reference',
    34 => 'private_actual_facility',
    35 => 'private_command',
    36 => 'private_coordinate',
    37 => 'quantity_selects_catalog',
    38 => 'required',
    39 => 'requires_empty_facility',
    40 => 'requires_owned_launch_base',
    41 => 'resource_and_state',
    42 => 'result_depends_on_target',
    43 => 'result_facility_key',
    44 => 'result_terrain_key',
    45 => 'single_command_per_turn',
    46 => 'sort_order',
    47 => 'source_owner',
    48 => 'target_type',
    49 => 'terrain',
    50 => 'terrain_destruction',
    51 => 'type',
    52 => 'value',
    53 => 'policy_version',
];

$data = [
    0 => '/development_plan_quantity/quick_presets/*',
    1 => 'adjacent_water_spread_maximum',
    2 => 'command_queue_limit',
    3 => 'cost_money',
    4 => 'default',
    5 => 'deviation_radius',
    6 => 'maximum',
    7 => 'minimum',
    8 => 'money_per_legacy_tree_unit',
    9 => 'owned_within_radius',
    10 => 'production_per_scale',
    11 => 'production_per_worker',
    12 => 'required_workforce_per_scale',
    13 => 'transfer_food_tons_per_quantity',
    14 => 'transfer_money_per_quantity',
];

$flavor = [
    0 => 'description',
    1 => 'label',
    2 => 'name',
];

return [
    'payload' => [
        'command_queue_limit' => 30,
        'command_definitions' => [
            0 => [
                'key' => 'land_clear',
                'name' => '整地',
                'description' => '所有する陸地を平地にします。',
                'target_type' => 'cell',
                'target_terrain_keys' => [
                    0 => 'wasteland',
                    1 => 'plain',
                    2 => 'forest',
                    3 => 'scorched',
                ],
                'target_facility_keys' => [
                ],
                'requires_empty_facility' => false,
                'cost_money' => 5,
                'required_resources' => [
                ],
                'execution_phase' => 'terrain',
                'result_terrain_key' => 'plain',
                'result_facility_key' => null,
                'sort_order' => 10,
                'metadata' => [
                    'legacy_command' => 'Prepare',
                    'consumes_turn' => true,
                    'execution_deferred' => false,
                ],
            ],
            1 => [
                'key' => 'land_level',
                'name' => '地ならし',
                'description' => '所有する陸地を、ターンを消費せず平地にします。ごくまれに地震が発生することがあります。',
                'target_type' => 'cell',
                'target_terrain_keys' => [
                    0 => 'wasteland',
                    1 => 'plain',
                    2 => 'forest',
                    3 => 'scorched',
                ],
                'target_facility_keys' => [
                ],
                'requires_empty_facility' => false,
                'cost_money' => 100,
                'required_resources' => [
                ],
                'execution_phase' => 'terrain',
                'result_terrain_key' => 'plain',
                'result_facility_key' => null,
                'sort_order' => 20,
                'metadata' => [
                    'legacy_command' => 'Prepare2',
                    'consumes_turn' => false,
                    'execution_deferred' => false,
                ],
            ],
            2 => [
                'key' => 'reclaim',
                'name' => '埋め立て',
                'description' => '海を中立の浅瀬へ、浅瀬を自国の荒地へ変更します。浅瀬の埋め立てでは周囲の水域も浅瀬化する場合があります。',
                'target_type' => 'cell',
                'target_terrain_keys' => [
                    0 => 'sea',
                    1 => 'shallow',
                ],
                'target_facility_keys' => [
                ],
                'requires_empty_facility' => true,
                'cost_money' => 150,
                'required_resources' => [
                ],
                'execution_phase' => 'terrain',
                'result_terrain_key' => null,
                'result_facility_key' => null,
                'sort_order' => 30,
                'metadata' => [
                    'legacy_command' => 'Reclaim',
                    'result_depends_on_target' => true,
                    'execution_deferred' => false,
                    'adjacent_water_spread_maximum' => 3,
                ],
            ],
            3 => [
                'key' => 'excavate',
                'name' => '掘削',
                'description' => '陸地を浅瀬へ、浅瀬を海へ、山を荒地へ変更します。海では数量に応じて海底油田を探索します。',
                'target_type' => 'cell',
                'target_terrain_keys' => [
                    0 => 'sea',
                    1 => 'shallow',
                    2 => 'wasteland',
                    3 => 'plain',
                    4 => 'forest',
                    5 => 'mountain',
                    6 => 'scorched',
                ],
                'target_facility_keys' => [
                ],
                'requires_empty_facility' => false,
                'cost_money' => 200,
                'required_resources' => [
                ],
                'execution_phase' => 'terrain',
                'result_terrain_key' => null,
                'result_facility_key' => null,
                'sort_order' => 40,
                'metadata' => [
                    'legacy_command' => 'Destroy',
                    'result_depends_on_target' => true,
                    'execution_deferred' => false,
                    'oil_search_effect_key' => 'seabed_oil_search',
                ],
            ],
            4 => [
                'key' => 'build_farm',
                'name' => '農場建設',
                'description' => '平地へ農場を建設します。',
                'target_type' => 'cell',
                'target_terrain_keys' => [
                    0 => 'plain',
                ],
                'target_facility_keys' => [
                ],
                'requires_empty_facility' => true,
                'cost_money' => 20,
                'required_resources' => [
                ],
                'execution_phase' => 'facility',
                'result_terrain_key' => 'plain',
                'result_facility_key' => 'farm',
                'sort_order' => 50,
                'metadata' => [
                    'legacy_command' => 'Farm',
                    'initial_scale_from_facility_definition' => true,
                    'future_expand_command' => 'expand_farm',
                    'execution_deferred' => false,
                ],
            ],
            5 => [
                'key' => 'build_factory',
                'name' => '工場建設',
                'description' => '平地へ工場を建設します。',
                'target_type' => 'cell',
                'target_terrain_keys' => [
                    0 => 'plain',
                ],
                'target_facility_keys' => [
                ],
                'requires_empty_facility' => true,
                'cost_money' => 100,
                'required_resources' => [
                ],
                'execution_phase' => 'facility',
                'result_terrain_key' => 'plain',
                'result_facility_key' => 'factory',
                'sort_order' => 60,
                'metadata' => [
                    'legacy_command' => 'Factory',
                    'initial_scale_from_facility_definition' => true,
                    'future_expand_command' => 'expand_factory',
                    'execution_deferred' => false,
                ],
            ],
            6 => [
                'key' => 'build_mine',
                'name' => '採掘場建設',
                'description' => '山へ採掘場を建設します。',
                'target_type' => 'cell',
                'target_terrain_keys' => [
                    0 => 'mountain',
                ],
                'target_facility_keys' => [
                ],
                'requires_empty_facility' => true,
                'cost_money' => 300,
                'required_resources' => [
                ],
                'execution_phase' => 'facility',
                'result_terrain_key' => 'mountain',
                'result_facility_key' => 'mine',
                'sort_order' => 70,
                'metadata' => [
                    'legacy_command' => 'Mountain',
                    'initial_scale_from_facility_definition' => true,
                    'future_expand_command' => 'expand_mine',
                    'execution_deferred' => false,
                ],
            ],
            7 => [
                'key' => 'logging',
                'name' => '伐採',
                'description' => '所有する森を伐採し、木の価値を資金として受け取ります。',
                'target_type' => 'cell',
                'target_terrain_keys' => [
                    0 => 'forest',
                ],
                'target_facility_keys' => [
                ],
                'requires_empty_facility' => false,
                'cost_money' => 0,
                'required_resources' => [
                ],
                'execution_phase' => 'terrain',
                'result_terrain_key' => 'plain',
                'result_facility_key' => null,
                'sort_order' => 80,
                'metadata' => [
                    'consumes_turn' => true,
                    'parameters' => [
                    ],
                    'legacy_command' => 'SellTree',
                    'money_per_legacy_tree_unit' => 5,
                    'private_coordinate' => true,
                ],
            ],
            8 => [
                'key' => 'territory_expand',
                'name' => '領土拡張',
                'description' => '自国領に隣接する中立陸地、または他国の荒地・焼け野原を領有します。休止中の首都周辺は保護されます。',
                'target_type' => 'cell',
                'target_terrain_keys' => [
                    0 => 'wasteland',
                    1 => 'scorched',
                    2 => 'plain',
                    3 => 'forest',
                    4 => 'mountain',
                ],
                'target_facility_keys' => [
                ],
                'requires_empty_facility' => true,
                'cost_money' => 100,
                'required_resources' => [
                ],
                'execution_phase' => 'territory',
                'result_terrain_key' => null,
                'result_facility_key' => null,
                'sort_order' => 90,
                'metadata' => [
                    'consumes_turn' => true,
                    'parameters' => [
                    ],
                    'legacy_command' => 'Widen',
                    'policy_version' => 3,
                    'actor_states' => [
                        0 => 'active',
                        1 => 'recovery',
                    ],
                    'adjacency' => [
                        'source_owner' => 'actor',
                        'directions' => 6,
                    ],
                    'neutral_target' => [
                        'allowed' => true,
                        'terrain_keys' => [
                            0 => 'wasteland',
                            1 => 'scorched',
                            2 => 'plain',
                            3 => 'forest',
                            4 => 'mountain',
                        ],
                        'requires_empty_facility' => true,
                    ],
                    'foreign_target' => [
                        'owner_states' => [
                            0 => 'active',
                            1 => 'dormant',
                        ],
                        'terrain_keys' => [
                            0 => 'wasteland',
                            1 => 'scorched',
                        ],
                        'requires_empty_facility' => true,
                    ],
                    'monster_occupancy' => 'reject',
                    'capital_core' => 'reject',
                    'effect' => [
                        'owner' => 'actor',
                        'terrain' => 'preserve',
                        'population' => 'preserve',
                        'facility' => 'preserve',
                        'facility_scale' => 'preserve',
                        'resource_and_state' => 'preserve',
                    ],
                ],
            ],
            9 => [
                'key' => 'plant_forest',
                'name' => '植林',
                'description' => '所有する平地へ森を植えます。',
                'target_type' => 'cell',
                'target_terrain_keys' => [
                    0 => 'plain',
                ],
                'target_facility_keys' => [
                ],
                'requires_empty_facility' => true,
                'cost_money' => 50,
                'required_resources' => [
                ],
                'execution_phase' => 'facility',
                'result_terrain_key' => 'forest',
                'result_facility_key' => null,
                'sort_order' => 100,
                'metadata' => [
                    'consumes_turn' => true,
                    'parameters' => [
                    ],
                    'legacy_command' => 'Plant',
                    'private_coordinate' => true,
                ],
            ],
            10 => [
                'key' => 'build_missile_base',
                'name' => 'ミサイル基地建設',
                'description' => '所有する平地へ秘密のミサイル基地を建設します。',
                'target_type' => 'cell',
                'target_terrain_keys' => [
                    0 => 'plain',
                ],
                'target_facility_keys' => [
                ],
                'requires_empty_facility' => true,
                'cost_money' => 300,
                'required_resources' => [
                ],
                'execution_phase' => 'facility',
                'result_terrain_key' => 'plain',
                'result_facility_key' => 'missile_base',
                'sort_order' => 110,
                'metadata' => [
                    'consumes_turn' => true,
                    'parameters' => [
                    ],
                    'legacy_command' => 'Base',
                    'private_coordinate' => true,
                ],
            ],
            11 => [
                'key' => 'build_defense_facility',
                'name' => '防衛施設建設',
                'description' => '所有する平地へ防衛施設を建設します。',
                'target_type' => 'cell',
                'target_terrain_keys' => [
                    0 => 'plain',
                ],
                'target_facility_keys' => [
                ],
                'requires_empty_facility' => true,
                'cost_money' => 800,
                'required_resources' => [
                ],
                'execution_phase' => 'facility',
                'result_terrain_key' => 'plain',
                'result_facility_key' => 'defense',
                'sort_order' => 120,
                'metadata' => [
                    'consumes_turn' => true,
                    'parameters' => [
                    ],
                    'legacy_command' => 'DBase',
                    'owner_overbuild_effect' => 'defense_self_destruct',
                ],
            ],
            12 => [
                'key' => 'build_seabed_base',
                'name' => '海底基地建設',
                'description' => '自国領から3hex以内の海へ秘密の海底基地を建設します。',
                'target_type' => 'cell',
                'target_terrain_keys' => [
                    0 => 'sea',
                ],
                'target_facility_keys' => [
                ],
                'requires_empty_facility' => true,
                'cost_money' => 8000,
                'required_resources' => [
                ],
                'execution_phase' => 'facility',
                'result_terrain_key' => 'sea',
                'result_facility_key' => 'seabed_base',
                'sort_order' => 130,
                'metadata' => [
                    'consumes_turn' => true,
                    'parameters' => [
                    ],
                    'legacy_command' => 'SBase',
                    'owned_within_radius' => 3,
                    'private_coordinate' => true,
                ],
            ],
            13 => [
                'key' => 'build_monument',
                'name' => '記念碑建設',
                'description' => '所有する平地へ選択した種類の記念碑を建設します。quantityは記念碑種類です。',
                'target_type' => 'cell',
                'target_terrain_keys' => [
                    0 => 'plain',
                ],
                'target_facility_keys' => [
                ],
                'requires_empty_facility' => true,
                'cost_money' => 9999,
                'required_resources' => [
                ],
                'execution_phase' => 'facility',
                'result_terrain_key' => 'plain',
                'result_facility_key' => 'monument',
                'sort_order' => 140,
                'metadata' => [
                    'consumes_turn' => true,
                    'parameters' => [
                        'target_nation_id' => [
                            'label' => '対象Nation ID',
                            'type' => 'integer',
                            'minimum' => 1,
                            'maximum' => 2147483647,
                            'required' => false,
                            'nullable' => true,
                        ],
                    ],
                    'legacy_command' => 'Monument',
                    'quantity_selects_catalog' => 'monument_definitions',
                    'owner_overbuild_effect' => 'monument_flight',
                ],
            ],
            14 => [
                'key' => 'build_decoy',
                'name' => '防衛施設建設',
                'description' => '所有する平地へ防衛施設に見えるハリボテを建設します。',
                'target_type' => 'cell',
                'target_terrain_keys' => [
                    0 => 'plain',
                ],
                'target_facility_keys' => [
                ],
                'requires_empty_facility' => true,
                'cost_money' => 1,
                'required_resources' => [
                ],
                'execution_phase' => 'facility',
                'result_terrain_key' => 'plain',
                'result_facility_key' => 'decoy',
                'sort_order' => 150,
                'metadata' => [
                    'consumes_turn' => true,
                    'parameters' => [
                    ],
                    'legacy_command' => 'Haribote',
                    'private_actual_facility' => true,
                ],
            ],
            15 => [
                'key' => 'missile',
                'name' => 'ミサイル発射',
                'description' => '指定座標へミサイルを発射します。数量で発射本数を設定します。誤差範囲は周囲2マスです。PPミサイルと同じターンに使用できます。',
                'target_type' => 'cell',
                'target_terrain_keys' => [
                    0 => 'sea',
                    1 => 'shallow',
                    2 => 'wasteland',
                    3 => 'scorched',
                    4 => 'plain',
                    5 => 'forest',
                    6 => 'mountain',
                ],
                'target_facility_keys' => [
                ],
                'requires_empty_facility' => false,
                'cost_money' => 20,
                'required_resources' => [
                ],
                'execution_phase' => 'military',
                'result_terrain_key' => null,
                'result_facility_key' => null,
                'sort_order' => 160,
                'metadata' => [
                    'consumes_turn' => true,
                    'parameters' => [
                    ],
                    'per_shot_cost' => true,
                    'deviation_radius' => 2,
                    'terrain_destruction' => false,
                    'single_command_per_turn' => false,
                    'requires_owned_launch_base' => true,
                ],
            ],
            16 => [
                'key' => 'pp_missile',
                'name' => 'PPミサイル発射',
                'description' => '指定座標へPPミサイルを発射します。数量で発射本数を設定します。誤差範囲は周囲1マスです。通常のミサイルと同じターンに使用できます。',
                'target_type' => 'cell',
                'target_terrain_keys' => [
                    0 => 'sea',
                    1 => 'shallow',
                    2 => 'wasteland',
                    3 => 'scorched',
                    4 => 'plain',
                    5 => 'forest',
                    6 => 'mountain',
                ],
                'target_facility_keys' => [
                ],
                'requires_empty_facility' => false,
                'cost_money' => 50,
                'required_resources' => [
                ],
                'execution_phase' => 'military',
                'result_terrain_key' => null,
                'result_facility_key' => null,
                'sort_order' => 170,
                'metadata' => [
                    'consumes_turn' => true,
                    'parameters' => [
                    ],
                    'per_shot_cost' => true,
                    'deviation_radius' => 1,
                    'terrain_destruction' => false,
                    'single_command_per_turn' => false,
                    'requires_owned_launch_base' => true,
                ],
            ],
            17 => [
                'key' => 'land_destruction_missile',
                'name' => '陸地破壊弾発射',
                'description' => '指定座標へ大地をえぐる陸地破壊弾を発射します。数量で発射本数を設定します。誤差範囲は周囲2マスです。他のミサイルとは同じターンに使用できません。',
                'target_type' => 'cell',
                'target_terrain_keys' => [
                    0 => 'sea',
                    1 => 'shallow',
                    2 => 'wasteland',
                    3 => 'scorched',
                    4 => 'plain',
                    5 => 'forest',
                    6 => 'mountain',
                ],
                'target_facility_keys' => [
                ],
                'requires_empty_facility' => false,
                'cost_money' => 100,
                'required_resources' => [
                ],
                'execution_phase' => 'military',
                'result_terrain_key' => null,
                'result_facility_key' => null,
                'sort_order' => 180,
                'metadata' => [
                    'consumes_turn' => true,
                    'parameters' => [
                    ],
                    'per_shot_cost' => true,
                    'deviation_radius' => 2,
                    'terrain_destruction' => true,
                    'single_command_per_turn' => true,
                    'requires_owned_launch_base' => true,
                ],
            ],
            18 => [
                'key' => 'spp_missile',
                'name' => 'SPPミサイル発射',
                'description' => '指定座標へSPPミサイルを発射します。数量で発射本数を設定します。着弾地点に誤差はありません。他のミサイルとは同じターンに使用できません。',
                'target_type' => 'cell',
                'target_terrain_keys' => [
                    0 => 'sea',
                    1 => 'shallow',
                    2 => 'wasteland',
                    3 => 'scorched',
                    4 => 'plain',
                    5 => 'forest',
                    6 => 'mountain',
                ],
                'target_facility_keys' => [
                ],
                'requires_empty_facility' => false,
                'cost_money' => 500,
                'required_resources' => [
                ],
                'execution_phase' => 'military',
                'result_terrain_key' => null,
                'result_facility_key' => null,
                'sort_order' => 190,
                'metadata' => [
                    'consumes_turn' => true,
                    'parameters' => [
                    ],
                    'per_shot_cost' => true,
                    'deviation_radius' => 0,
                    'terrain_destruction' => false,
                    'single_command_per_turn' => true,
                    'requires_owned_launch_base' => true,
                ],
            ],
            19 => [
                'key' => 'monster_dispatch',
                'name' => '怪獣派遣',
                'description' => '対象の国にメカいのらを派遣します。',
                'target_type' => 'nation',
                'target_terrain_keys' => [
                    0 => 'sea',
                    1 => 'shallow',
                    2 => 'wasteland',
                    3 => 'scorched',
                    4 => 'plain',
                    5 => 'forest',
                    6 => 'mountain',
                ],
                'target_facility_keys' => [
                ],
                'requires_empty_facility' => false,
                'cost_money' => 3000,
                'required_resources' => [
                ],
                'execution_phase' => 'military',
                'result_terrain_key' => null,
                'result_facility_key' => null,
                'sort_order' => 200,
                'metadata' => [
                    'parameters' => [
                        'target_nation_id' => [
                            'label' => '対象Nation ID',
                            'type' => 'integer',
                            'minimum' => 1,
                            'maximum' => 2147483647,
                            'required' => true,
                        ],
                    ],
                    'private_command' => true,
                    'quantity_selects_catalog' => 'monster_dispatch_options',
                    'default_selector_value' => 1,
                    'monster_dispatch_options' => [
                        0 => [
                            'value' => 1,
                            'monster_key' => 'mecha_inora',
                            'label' => 'メカいのら',
                            'cost_money' => 3000,
                            'enabled' => true,
                        ],
                        1 => [
                            'value' => 2,
                            'monster_key' => 'mecha_inora_zero',
                            'label' => 'メカいのら零式',
                            'cost_money' => 9999,
                            'enabled' => true,
                        ],
                    ],
                ],
            ],
            20 => [
                'key' => 'finance',
                'name' => '資金繰り',
                'description' => '何もせず、資金繰りを行います。',
                'target_type' => 'nation',
                'target_terrain_keys' => [
                    0 => 'sea',
                    1 => 'shallow',
                    2 => 'wasteland',
                    3 => 'scorched',
                    4 => 'plain',
                    5 => 'forest',
                    6 => 'mountain',
                ],
                'target_facility_keys' => [
                ],
                'requires_empty_facility' => false,
                'cost_money' => 0,
                'required_resources' => [
                ],
                'execution_phase' => 'operations',
                'result_terrain_key' => null,
                'result_facility_key' => null,
                'sort_order' => 210,
                'metadata' => [
                    'consumes_turn' => true,
                    'parameters' => [
                    ],
                ],
            ],
            21 => [
                'key' => 'money_aid',
                'name' => '資金援助',
                'description' => '対象の国に、数量×100億円の資金を援助します。',
                'target_type' => 'nation',
                'target_terrain_keys' => [
                    0 => 'sea',
                    1 => 'shallow',
                    2 => 'wasteland',
                    3 => 'scorched',
                    4 => 'plain',
                    5 => 'forest',
                    6 => 'mountain',
                ],
                'target_facility_keys' => [
                ],
                'requires_empty_facility' => false,
                'cost_money' => 0,
                'required_resources' => [
                ],
                'execution_phase' => 'operations',
                'result_terrain_key' => null,
                'result_facility_key' => null,
                'sort_order' => 220,
                'metadata' => [
                    'consumes_turn' => false,
                    'parameters' => [
                        'target_nation_id' => [
                            'label' => '対象Nation ID',
                            'type' => 'integer',
                            'minimum' => 1,
                            'maximum' => 2147483647,
                            'required' => true,
                        ],
                    ],
                    'transfer_money_per_quantity' => 100,
                ],
            ],
            22 => [
                'key' => 'food_aid',
                'name' => '食料援助',
                'description' => '対象の国に、数量×1,000トンの食料を援助します。',
                'target_type' => 'nation',
                'target_terrain_keys' => [
                    0 => 'sea',
                    1 => 'shallow',
                    2 => 'wasteland',
                    3 => 'scorched',
                    4 => 'plain',
                    5 => 'forest',
                    6 => 'mountain',
                ],
                'target_facility_keys' => [
                ],
                'requires_empty_facility' => false,
                'cost_money' => 0,
                'required_resources' => [
                ],
                'execution_phase' => 'operations',
                'result_terrain_key' => null,
                'result_facility_key' => null,
                'sort_order' => 230,
                'metadata' => [
                    'consumes_turn' => false,
                    'parameters' => [
                        'target_nation_id' => [
                            'label' => '対象Nation ID',
                            'type' => 'integer',
                            'minimum' => 1,
                            'maximum' => 2147483647,
                            'required' => true,
                        ],
                    ],
                    'transfer_food_tons_per_quantity' => 1000,
                ],
            ],
            23 => [
                'key' => 'attraction',
                'name' => '誘致活動',
                'description' => '誘致活動を行ったターンは、人口が増加しやすくなります。',
                'target_type' => 'nation',
                'target_terrain_keys' => [
                    0 => 'sea',
                    1 => 'shallow',
                    2 => 'wasteland',
                    3 => 'scorched',
                    4 => 'plain',
                    5 => 'forest',
                    6 => 'mountain',
                ],
                'target_facility_keys' => [
                ],
                'requires_empty_facility' => false,
                'cost_money' => 1000,
                'required_resources' => [
                ],
                'execution_phase' => 'operations',
                'result_terrain_key' => null,
                'result_facility_key' => null,
                'sort_order' => 240,
                'metadata' => [
                    'consumes_turn' => true,
                    'parameters' => [
                    ],
                    'legacy_command' => 'Propaganda',
                ],
            ],
            24 => [
                'key' => 'relocate_capital',
                'name' => '首都遷都',
                'description' => '指定した自国の都市を新しい首都にします。',
                'target_type' => 'cell',
                'target_terrain_keys' => [
                    0 => 'plain',
                ],
                'target_facility_keys' => [
                    0 => 'city',
                ],
                'requires_empty_facility' => false,
                'cost_money' => 1000,
                'required_resources' => [
                ],
                'execution_phase' => 'operations',
                'result_terrain_key' => 'plain',
                'result_facility_key' => 'capital',
                'sort_order' => 250,
                'metadata' => [
                    'consumes_turn' => true,
                    'parameters' => [
                    ],
                    'fixed_cost_setting' => 'capital_relocation_cost_money',
                ],
            ],
        ],
        'production_definitions' => [
            0 => [
                'key' => 'farm_wheat',
                'facility_key' => 'farm',
                'output_resource_key' => 'wheat',
                'production_per_scale' => 1000,
                'required_workforce_per_scale' => 1000,
                'operating_condition' => 'turn_start_workforce_allocation',
                'price_reference' => 'sale.wheat',
                'metadata' => [
                    'production_per_worker' => 1,
                    'canonical_unit' => 'ton',
                ],
            ],
            1 => [
                'key' => 'factory_industrial_goods',
                'facility_key' => 'factory',
                'output_resource_key' => 'industrial_goods',
                'production_per_scale' => 1000,
                'required_workforce_per_scale' => 1000,
                'operating_condition' => 'turn_start_workforce_allocation',
                'price_reference' => 'sale.industrial_goods',
                'metadata' => [
                    'production_per_worker' => 1,
                ],
            ],
            2 => [
                'key' => 'mine_minerals',
                'facility_key' => 'mine',
                'output_resource_key' => 'minerals',
                'production_per_scale' => 1000,
                'required_workforce_per_scale' => 1000,
                'operating_condition' => 'turn_start_workforce_allocation',
                'price_reference' => 'sale.minerals',
                'metadata' => [
                    'production_per_worker' => 1,
                ],
            ],
        ],
        'development_plan_quantity' => [
            'type' => 'integer',
            'minimum' => 1,
            'maximum' => 99,
            'default' => 1,
            'quick_presets' => [
                0 => 1,
                1 => 5,
                2 => 10,
                3 => 25,
                4 => 50,
                5 => 99,
            ],
        ],
    ],
    'classification' => [
        'behavior' => $behavior,
        'data' => $data,
        'flavor' => $flavor,
    ],
];
