<?php

$behavior = [
    0 => '/facility_definitions/decoy/buildable_terrain_keys/*',
    1 => '/facility_definitions/defense/buildable_terrain_keys/*',
    2 => '/facility_definitions/factory/buildable_terrain_keys/*',
    3 => '/facility_definitions/farm/buildable_terrain_keys/*',
    4 => '/facility_definitions/mine/buildable_terrain_keys/*',
    5 => '/facility_definitions/missile_base/buildable_terrain_keys/*',
    6 => '/facility_definitions/monument/buildable_terrain_keys/*',
    7 => '/facility_definitions/seabed_base/buildable_terrain_keys/*',
    8 => '/facility_definitions/seabed_oil_field/buildable_terrain_keys/*',
    9 => 'build_command_key',
    10 => 'disguise_ownership_policy',
    11 => 'disguise_terrain_key',
    12 => 'production_definition_key',
    13 => 'visibility_policy',
];

$data = [
    0 => '/facility_definitions/missile_base/launch_capacity_by_level/*',
    1 => '/facility_definitions/missile_base/level_thresholds/*',
    2 => '/facility_definitions/seabed_base/launch_capacity_by_level/*',
    3 => '/facility_definitions/seabed_base/level_thresholds/*',
    4 => 'initial_experience',
    5 => 'initial_scale',
    6 => 'maximum_experience',
    7 => 'maximum_scale',
    8 => 'scale_increment',
    9 => 'scale_unit_people',
    10 => 'workforce_per_scale_people',
];

$flavor = [
    0 => 'asset_key',
    1 => 'disguise_asset_key',
    2 => 'display_as_facility_key',
    3 => 'name',
];

return [
    'payload' => [
        'facility_definitions' => [
            'village' => [
                'name' => '村',
                'asset_key' => 'tile.village',
                'visibility_policy' => 'public',
                'build_command_key' => null,
                'scale_unit_people' => null,
                'initial_scale' => null,
                'scale_increment' => null,
                'maximum_scale' => null,
                'workforce_per_scale_people' => null,
                'production_definition_key' => null,
                'buildable_terrain_keys' => [
                ],
            ],
            'capital' => [
                'name' => '首都',
                'asset_key' => 'tile.capital',
                'visibility_policy' => 'public',
                'build_command_key' => null,
                'scale_unit_people' => null,
                'initial_scale' => null,
                'scale_increment' => null,
                'maximum_scale' => null,
                'workforce_per_scale_people' => null,
                'production_definition_key' => null,
                'buildable_terrain_keys' => [
                ],
            ],
            'farm' => [
                'name' => '農場',
                'asset_key' => 'tile.farm',
                'visibility_policy' => 'public',
                'build_command_key' => 'build_farm',
                'scale_unit_people' => 1000,
                'initial_scale' => 10,
                'scale_increment' => 2,
                'maximum_scale' => 50,
                'workforce_per_scale_people' => 1000,
                'production_definition_key' => 'farm_wheat',
                'buildable_terrain_keys' => [
                    0 => 'plain',
                ],
            ],
            'factory' => [
                'name' => '工場',
                'asset_key' => 'tile.factory',
                'visibility_policy' => 'public',
                'build_command_key' => 'build_factory',
                'scale_unit_people' => 1000,
                'initial_scale' => 30,
                'scale_increment' => 10,
                'maximum_scale' => 100,
                'workforce_per_scale_people' => 1000,
                'production_definition_key' => 'factory_industrial_goods',
                'buildable_terrain_keys' => [
                    0 => 'plain',
                ],
            ],
            'mine' => [
                'name' => '採掘場',
                'asset_key' => 'tile.mine',
                'visibility_policy' => 'public',
                'build_command_key' => 'build_mine',
                'scale_unit_people' => 1000,
                'initial_scale' => 5,
                'scale_increment' => 5,
                'maximum_scale' => 200,
                'workforce_per_scale_people' => 1000,
                'production_definition_key' => 'mine_minerals',
                'buildable_terrain_keys' => [
                    0 => 'mountain',
                ],
            ],
            'missile_base' => [
                'name' => 'ミサイル基地',
                'asset_key' => 'tile.missile_base',
                'visibility_policy' => 'disguised',
                'disguise_terrain_key' => 'forest',
                'disguise_asset_key' => 'tile.forest',
                'build_command_key' => 'build_missile_base',
                'scale_unit_people' => null,
                'initial_scale' => null,
                'scale_increment' => null,
                'maximum_scale' => null,
                'workforce_per_scale_people' => null,
                'production_definition_key' => null,
                'buildable_terrain_keys' => [
                    0 => 'plain',
                ],
                'initial_experience' => 0,
                'maximum_experience' => 200,
                'level_thresholds' => [
                    0 => 20,
                    1 => 60,
                    2 => 120,
                    3 => 200,
                ],
                'launch_capacity_by_level' => [
                    1 => 1,
                    2 => 2,
                    3 => 3,
                    4 => 4,
                    5 => 5,
                ],
            ],
            'town' => [
                'name' => '町',
                'asset_key' => 'tile.town',
                'visibility_policy' => 'public',
                'build_command_key' => null,
                'scale_unit_people' => null,
                'initial_scale' => null,
                'scale_increment' => null,
                'maximum_scale' => null,
                'workforce_per_scale_people' => null,
                'production_definition_key' => null,
                'buildable_terrain_keys' => [
                ],
            ],
            'city' => [
                'name' => '都市',
                'asset_key' => 'tile.city',
                'visibility_policy' => 'public',
                'build_command_key' => null,
                'scale_unit_people' => null,
                'initial_scale' => null,
                'scale_increment' => null,
                'maximum_scale' => null,
                'workforce_per_scale_people' => null,
                'production_definition_key' => null,
                'buildable_terrain_keys' => [
                ],
            ],
            'seabed_oil_field' => [
                'name' => '海底油田',
                'asset_key' => 'tile.seabed_oil_field',
                'visibility_policy' => 'public',
                'build_command_key' => 'excavate',
                'scale_unit_people' => null,
                'initial_scale' => null,
                'scale_increment' => null,
                'maximum_scale' => null,
                'workforce_per_scale_people' => null,
                'production_definition_key' => null,
                'buildable_terrain_keys' => [
                    0 => 'sea',
                ],
            ],
            'defense' => [
                'disguise_ownership_policy' => null,
                'scale_unit_people' => null,
                'initial_scale' => null,
                'scale_increment' => null,
                'maximum_scale' => null,
                'workforce_per_scale_people' => null,
                'production_definition_key' => null,
                'name' => '防衛施設',
                'asset_key' => 'tile.defense',
                'visibility_policy' => 'public',
                'build_command_key' => 'build_defense_facility',
                'buildable_terrain_keys' => [
                    0 => 'plain',
                ],
            ],
            'seabed_base' => [
                'disguise_ownership_policy' => 'neutral',
                'scale_unit_people' => null,
                'initial_scale' => null,
                'scale_increment' => null,
                'maximum_scale' => null,
                'workforce_per_scale_people' => null,
                'production_definition_key' => null,
                'name' => '海底基地',
                'asset_key' => 'tile.seabed_base',
                'visibility_policy' => 'disguised',
                'disguise_terrain_key' => 'sea',
                'disguise_asset_key' => 'tile.sea',
                'build_command_key' => 'build_seabed_base',
                'buildable_terrain_keys' => [
                    0 => 'sea',
                ],
                'initial_experience' => 0,
                'maximum_experience' => 200,
                'level_thresholds' => [
                    0 => 50,
                    1 => 200,
                ],
                'launch_capacity_by_level' => [
                    1 => 1,
                    2 => 2,
                    3 => 3,
                ],
            ],
            'monument' => [
                'disguise_ownership_policy' => null,
                'scale_unit_people' => null,
                'initial_scale' => null,
                'scale_increment' => null,
                'maximum_scale' => null,
                'workforce_per_scale_people' => null,
                'production_definition_key' => null,
                'name' => '記念碑',
                'asset_key' => 'tile.monument',
                'visibility_policy' => 'public',
                'build_command_key' => 'build_monument',
                'buildable_terrain_keys' => [
                    0 => 'plain',
                ],
            ],
            'decoy' => [
                'disguise_ownership_policy' => null,
                'scale_unit_people' => null,
                'initial_scale' => null,
                'scale_increment' => null,
                'maximum_scale' => null,
                'workforce_per_scale_people' => null,
                'production_definition_key' => null,
                'name' => 'ハリボテ',
                'asset_key' => 'tile.decoy',
                'visibility_policy' => 'public',
                'build_command_key' => 'build_decoy',
                'buildable_terrain_keys' => [
                    0 => 'plain',
                ],
                'display_as_facility_key' => 'defense',
            ],
        ],
    ],
    'classification' => [
        'behavior' => $behavior,
        'data' => $data,
        'flavor' => $flavor,
    ],
];
