<?php

$behavior = [
    0 => '/karma/anti_monster_missile_keys/*',
    1 => '/karma/sanction/interception/*',
    2 => '/nation_lifecycle/dormant_reasons/*',
    3 => '/nation_lifecycle/emergency_farm/candidate_terrain_keys/*',
    4 => '/nation_lifecycle/emergency_farm/selection/*',
    5 => '/nation_lifecycle/runtime_entry_states/*',
    6 => '/nation_lifecycle/states/*',
    7 => '/nation_lifecycle/territory_influence_source_states/*',
    8 => '/nation_lifecycle/territory_influence_target_states/*',
    9 => 'facility_key',
    10 => 'finance_command_key',
    11 => 'impact',
    12 => 'initial_food_resource_key',
    13 => 'random_stream_version',
    14 => 'recovery_entry_enabled',
    15 => 'result_terrain_key',
    16 => 'target_selection',
];

$data = [
    0 => 'abandonment_idle_threshold',
    1 => 'alliance_reward_money_per_karma_per_impact',
    2 => 'capital_above_minimum',
    3 => 'capital_at_minimum',
    4 => 'decay_amount',
    5 => 'decay_interval_turns',
    6 => 'dormant_finance_money',
    7 => 'dormant_idle_threshold',
    8 => 'dormant_protection_radius',
    9 => 'foreign_monster_kill_reduction',
    10 => 'hostile_monument_points',
    11 => 'initial_idle_counter',
    12 => 'land_destroyed',
    13 => 'manual_dormancy_max_days',
    14 => 'manual_dormancy_min_days',
    15 => 'maximum',
    16 => 'minimum',
    17 => 'ordinary',
    18 => 'overflow_points_per_shot',
    19 => 'recovery_duration_turns',
    20 => 'recovery_entry_reduction',
    21 => 'seabed_base_destroyed',
    22 => 'seabed_oil_field_destroyed',
    23 => 'settlement_or_facility',
    24 => 'spp_self_destruct_setup_points',
    25 => 'terrain',
    26 => 'turns_per_day',
    27 => 'victim_reduction_per_impact',
];

$flavor = [
    0 => 'dormant_visual_theme',
];

return [
    'payload' => [
        'nation_lifecycle' => [
            'states' => [
                0 => 'active',
                1 => 'dormant',
                2 => 'recovery',
                3 => 'abandoned',
            ],
            'runtime_entry_states' => [
                0 => 'active',
                1 => 'dormant',
                2 => 'recovery',
                3 => 'abandoned',
            ],
            'recovery_entry_enabled' => true,
            'recovery_duration_turns' => 84,
            'dormant_reasons' => [
                0 => 'idle',
                1 => 'collapse',
                2 => 'manual',
            ],
            'initial_idle_counter' => 2000,
            'dormant_idle_threshold' => 360,
            'abandonment_idle_threshold' => 2160,
            'turns_per_day' => 12,
            'manual_dormancy_min_days' => 1,
            'manual_dormancy_max_days' => 7,
            'dormant_finance_money' => 10,
            'dormant_protection_radius' => 2,
            'dormant_visual_theme' => 'snow',
            'territory_influence_target_states' => [
                0 => 'active',
                1 => 'dormant',
            ],
            'territory_influence_source_states' => [
                0 => 'active',
            ],
            'initial_food_resource_key' => 'wheat',
            'finance_command_key' => 'finance',
            'emergency_farm' => [
                'facility_key' => 'farm',
                'result_terrain_key' => 'plain',
                'candidate_terrain_keys' => [
                    0 => 'plain',
                    1 => 'wasteland',
                    2 => 'scorched',
                    3 => 'shallow',
                    4 => 'sea',
                ],
                'selection' => [
                    0 => 'distance',
                    1 => 'y',
                    2 => 'x',
                ],
            ],
        ],
        'karma' => [
            'minimum' => -10,
            'ordinary' => 0,
            'maximum' => 100,
            'impact_points' => [
                'terrain' => 1,
                'settlement_or_facility' => 2,
                'capital_above_minimum' => 2,
                'capital_at_minimum' => 0,
                'seabed_oil_field_destroyed' => 10,
                'land_destroyed' => 10,
                'seabed_base_destroyed' => 3,
            ],
            'anti_monster_missile_keys' => [
                0 => 'missile',
                1 => 'pp_missile',
                2 => 'spp_missile',
            ],
            'spp_self_destruct_setup_points' => 20,
            'hostile_monument_points' => 15,
            'foreign_monster_kill_reduction' => 1,
            'victim_reduction_per_impact' => 1,
            'decay_interval_turns' => 6,
            'decay_amount' => 1,
            'recovery_entry_reduction' => 3,
            'alliance_reward_money_per_karma_per_impact' => 1,
            'sanction' => [
                'overflow_points_per_shot' => 1,
                'target_selection' => 'owned_surface_territory_with_replacement',
                'interception' => [
                    0 => 'defense',
                    1 => 'secretary',
                ],
                'impact' => 'canonical_scorch_or_destruction',
                'random_stream_version' => 1,
            ],
        ],
    ],
    'classification' => [
        'behavior' => $behavior,
        'data' => $data,
        'flavor' => $flavor,
    ],
];
