<?php

$behavior = [
    0 => '/military/defense_interception/missile_keys/*',
    1 => '/military/defense_spp_resistance/ineffective_missile_keys/*',
    2 => '/military/dormant_impact/preserve/*',
    3 => '/military/launch_base_experience/facility_keys/*',
    4 => '/military/launch_base_experience/settlement_hit/missile_keys/*',
    5 => '/military/launch_base_facility_keys/*',
    6 => '/military/refugees/event_types/*',
    7 => '/military/refugees/settlement_facility_keys/*',
    8 => '/military/seabed_base_resistance/destructive_missile_keys/*',
    9 => '/military/seabed_base_resistance/ineffective_missile_keys/*',
    10 => '/monster_definitions/*/movement_terrain_contract/blocked_facility_keys/*',
    11 => '/monster_definitions/*/movement_terrain_contract/blocked_terrain_keys/*',
    12 => '/monster_definitions/*/source_metadata/behavior/world_spawn/terrain_keys/*',
    13 => '/monster_definitions/0/natural_spawn_tier',
    14 => '/monster_definitions/1/natural_spawn_tier',
    15 => '/monster_definitions/6/natural_spawn_tier',
    16 => '/monster_system/movement/blocked_facility_keys/*',
    17 => '/monster_system/movement/blocked_terrain_keys/*',
    18 => '/monster_system/natural_spawn/population_tiers/*/monster_keys/*',
    19 => '/monster_system/natural_spawn/settlement_facility_keys/*',
    20 => '/monster_system/terrain_events/preserve_occupancy/*',
    21 => '/monster_system/terrain_events/remove_without_rewards/*',
    22 => 'authoritative_for_final_blow_count',
    23 => 'authoritative_for_kill_marks',
    24 => 'can_act_on_spawn_turn',
    25 => 'clear_owner',
    26 => 'creates_terrain',
    27 => 'defense_facility_key',
    28 => 'defense_target_cells',
    29 => 'destination_terrain_key',
    30 => 'dispatchable',
    31 => 'display_order',
    32 => 'eligible_nation_state',
    33 => 'exclude_capital',
    34 => 'exclude_center',
    35 => 'explicit_target_state',
    36 => 'facility_key',
    37 => 'facility_owner_scope',
    38 => 'firing_nation_details',
    39 => 'host_food_resource_key',
    40 => 'host_remainder_share',
    41 => 'increment_on_attributed_final_blow',
    42 => 'ineffective_impacts',
    43 => 'island_creation_displaceable',
    44 => 'key',
    45 => 'killer_money_share',
    46 => 'kind',
    47 => 'launch_summary',
    48 => 'meaningful_impacts',
    49 => 'monster_damage_experience',
    50 => 'monster_exception',
    51 => 'monster_occupied_cells',
    52 => 'movement',
    53 => 'one_draw_per_active_nation',
    54 => 'overlap_resolution',
    55 => 'parity',
    56 => 'policy',
    57 => 'preserve_owner',
    58 => 'recipient',
    59 => 'refugees',
    60 => 'remove_facility',
    61 => 'resolve_before',
    62 => 'restore_previous_terrain',
    63 => 'reward_policy',
    64 => 'scope',
    65 => 'selection',
    66 => 'self_fired_missiles',
    67 => 'skill_code',
    68 => 'skill_key',
    69 => 'special_action',
    70 => 'stream_version',
    71 => 'type',
    72 => 'visibility',
];

$data = [
    0 => '/monster_definitions/2/natural_spawn_tier',
    1 => '/monster_definitions/3/natural_spawn_tier',
    2 => '/monster_definitions/4/natural_spawn_tier',
    3 => '/monster_definitions/5/natural_spawn_tier',
    4 => '/monster_definitions/7/natural_spawn_tier',
    5 => '/monster_definitions/8/natural_spawn_tier',
    6 => '/monster_definitions/9/natural_spawn_tier',
    7 => 'base_hp',
    8 => 'candidate_attempts_per_action',
    9 => 'capital_population_loss_multiplier',
    10 => 'cost_money_per_shot',
    11 => 'denominator',
    12 => 'deviation_radius',
    13 => 'experience_per_damage',
    14 => 'food_tons_per_money_unit',
    15 => 'footprint_cells',
    16 => 'hp_variation',
    17 => 'maximum_per_nation_per_turn',
    18 => 'maximum_probability_numerator',
    19 => 'minimum_land_distance',
    20 => 'minimum_population',
    21 => 'missile_base_experience',
    22 => 'missile_base_experience_maximum',
    23 => 'monster_final_blow_experience',
    24 => 'movement_limit',
    25 => 'numerator',
    26 => 'population_after',
    27 => 'population_divisor',
    28 => 'radius',
    29 => 'remaining_hp',
    30 => 'wreckage_value_money',
];

$flavor = [
    0 => 'appearance',
    1 => 'asset_key',
    2 => 'filename',
    3 => 'hardened_asset_key',
    4 => 'name',
    5 => 'skill_description',
    6 => 'special',
];

return [
    'payload' => [
        'monster_definitions' => [
            0 => [
                'key' => 'mecha_inora',
                'name' => 'メカいのら',
                'asset_key' => 'hakoniwa_original.monster.mecha_inora',
                'hardened_asset_key' => null,
                'base_hp' => 2,
                'hp_variation' => 0,
                'skill_key' => 'none',
                'movement_limit' => 1,
                'natural_spawn_tier' => null,
                'wreckage_value_money' => 0,
                'missile_base_experience' => 5,
                'experience_per_damage' => 3,
                'skill_description' => '特殊能力なし（最大1歩移動）',
                'visibility' => 'public',
                'movement_terrain_contract' => [
                    'candidate_attempts_per_action' => 3,
                    'blocked_terrain_keys' => [
                        0 => 'sea',
                        1 => 'shallow',
                        2 => 'mountain',
                    ],
                    'blocked_facility_keys' => [
                        0 => 'seabed_oil_field',
                        1 => 'seabed_base',
                        2 => 'mine',
                        3 => 'monument',
                        4 => 'capital',
                    ],
                    'defense_facility_key' => 'defense',
                    'destination_terrain_key' => 'wasteland',
                    'preserve_owner' => true,
                ],
                'trample_contract' => [
                    'population_after' => 0,
                    'remove_facility' => true,
                    'restore_previous_terrain' => false,
                ],
                'hardening_contract' => [
                    'type' => 'none',
                ],
                'source_metadata' => [
                    'kind' => 0,
                    'skill_code' => 0,
                    'filename' => 'monster7.gif',
                    'reward_policy' => 'standard_split',
                    'manual' => [
                        'appearance' => '怪獣派遣',
                        'special' => '特殊能力なし',
                    ],
                    'behavior' => [
                        'movement' => 'legacy_land',
                        'dispatchable' => true,
                        'can_act_on_spawn_turn' => false,
                        'special_action' => 'none',
                        'island_creation_displaceable' => false,
                    ],
                ],
                'display_order' => 0,
            ],
            1 => [
                'key' => 'mecha_inora_zero',
                'name' => 'メカいのら零式',
                'asset_key' => 'hakoniwa_custom.monster.mecha_inora_zero',
                'hardened_asset_key' => null,
                'base_hp' => 4,
                'hp_variation' => 0,
                'skill_key' => 'none',
                'movement_limit' => 1,
                'natural_spawn_tier' => null,
                'wreckage_value_money' => 0,
                'missile_base_experience' => 35,
                'experience_per_damage' => 9,
                'skill_description' => 'HP1で核爆発',
                'visibility' => 'public',
                'movement_terrain_contract' => [
                    'candidate_attempts_per_action' => 3,
                    'blocked_terrain_keys' => [
                        0 => 'sea',
                        1 => 'shallow',
                        2 => 'mountain',
                    ],
                    'blocked_facility_keys' => [
                        0 => 'seabed_oil_field',
                        1 => 'seabed_base',
                        2 => 'mine',
                        3 => 'monument',
                        4 => 'capital',
                    ],
                    'defense_facility_key' => 'defense',
                    'destination_terrain_key' => 'wasteland',
                    'preserve_owner' => true,
                ],
                'trample_contract' => [
                    'population_after' => 0,
                    'remove_facility' => true,
                    'restore_previous_terrain' => false,
                ],
                'hardening_contract' => [
                    'type' => 'none',
                ],
                'source_metadata' => [
                    'reward_policy' => 'standard_split',
                    'secretary_item_target_safety' => [
                        'policy' => 'certain_self_action_at_remaining_hp',
                        'remaining_hp' => 1,
                    ],
                    'manual' => [
                        'appearance' => '怪獣派遣（9,999億円）',
                        'special' => 'HP1で核爆発',
                    ],
                    'behavior' => [
                        'movement' => 'legacy_land',
                        'dispatchable' => true,
                        'can_act_on_spawn_turn' => false,
                        'special_action' => 'nuclear_self_destruct_at_hp_one',
                        'island_creation_displaceable' => false,
                    ],
                ],
                'display_order' => 50,
            ],
            2 => [
                'key' => 'inora',
                'name' => 'いのら',
                'asset_key' => 'hakoniwa_original.monster.inora',
                'hardened_asset_key' => null,
                'base_hp' => 1,
                'hp_variation' => 1,
                'skill_key' => 'none',
                'movement_limit' => 1,
                'natural_spawn_tier' => 1,
                'wreckage_value_money' => 400,
                'missile_base_experience' => 5,
                'experience_per_damage' => 4,
                'skill_description' => '特殊能力なし（最大1歩移動）',
                'visibility' => 'public',
                'movement_terrain_contract' => [
                    'candidate_attempts_per_action' => 3,
                    'blocked_terrain_keys' => [
                        0 => 'sea',
                        1 => 'shallow',
                        2 => 'mountain',
                    ],
                    'blocked_facility_keys' => [
                        0 => 'seabed_oil_field',
                        1 => 'seabed_base',
                        2 => 'mine',
                        3 => 'monument',
                        4 => 'capital',
                    ],
                    'defense_facility_key' => 'defense',
                    'destination_terrain_key' => 'wasteland',
                    'preserve_owner' => true,
                ],
                'trample_contract' => [
                    'population_after' => 0,
                    'remove_facility' => true,
                    'restore_previous_terrain' => false,
                ],
                'hardening_contract' => [
                    'type' => 'none',
                ],
                'source_metadata' => [
                    'kind' => 1,
                    'skill_code' => 0,
                    'filename' => 'monster0.gif',
                    'reward_policy' => 'standard_split',
                    'manual' => [
                        'appearance' => '人口10万人以上で自然発生',
                        'special' => '特殊能力なし',
                    ],
                    'behavior' => [
                        'movement' => 'legacy_land',
                        'dispatchable' => false,
                        'can_act_on_spawn_turn' => false,
                        'special_action' => 'none',
                        'island_creation_displaceable' => false,
                    ],
                ],
                'display_order' => 100,
            ],
            3 => [
                'key' => 'sanjira',
                'name' => 'サンジラ',
                'asset_key' => 'hakoniwa_original.monster.sanjira',
                'hardened_asset_key' => 'hakoniwa_original.monster.hardened',
                'base_hp' => 1,
                'hp_variation' => 1,
                'skill_key' => 'harden_odd',
                'movement_limit' => 1,
                'natural_spawn_tier' => 1,
                'wreckage_value_money' => 500,
                'missile_base_experience' => 7,
                'experience_per_damage' => 5,
                'skill_description' => '奇数ターンは硬化し、移動と通常ダメージを無効化',
                'visibility' => 'public',
                'movement_terrain_contract' => [
                    'candidate_attempts_per_action' => 3,
                    'blocked_terrain_keys' => [
                        0 => 'sea',
                        1 => 'shallow',
                        2 => 'mountain',
                    ],
                    'blocked_facility_keys' => [
                        0 => 'seabed_oil_field',
                        1 => 'seabed_base',
                        2 => 'mine',
                        3 => 'monument',
                        4 => 'capital',
                    ],
                    'defense_facility_key' => 'defense',
                    'destination_terrain_key' => 'wasteland',
                    'preserve_owner' => true,
                ],
                'trample_contract' => [
                    'population_after' => 0,
                    'remove_facility' => true,
                    'restore_previous_terrain' => false,
                ],
                'hardening_contract' => [
                    'type' => 'target_turn_parity',
                    'parity' => 'odd',
                ],
                'source_metadata' => [
                    'kind' => 2,
                    'skill_code' => 3,
                    'filename' => 'monster5.gif',
                    'reward_policy' => 'standard_split',
                    'manual' => [
                        'appearance' => '人口10万人以上で自然発生',
                        'special' => '奇数ターンは硬化',
                    ],
                    'behavior' => [
                        'movement' => 'legacy_land',
                        'dispatchable' => false,
                        'can_act_on_spawn_turn' => false,
                        'special_action' => 'none',
                        'island_creation_displaceable' => false,
                    ],
                ],
                'display_order' => 200,
            ],
            4 => [
                'key' => 'red_inora',
                'name' => 'レッドいのら',
                'asset_key' => 'hakoniwa_original.monster.red_inora',
                'hardened_asset_key' => null,
                'base_hp' => 3,
                'hp_variation' => 1,
                'skill_key' => 'none',
                'movement_limit' => 1,
                'natural_spawn_tier' => 2,
                'wreckage_value_money' => 1000,
                'missile_base_experience' => 12,
                'experience_per_damage' => 4,
                'skill_description' => '特殊能力なし（最大1歩移動）',
                'visibility' => 'public',
                'movement_terrain_contract' => [
                    'candidate_attempts_per_action' => 3,
                    'blocked_terrain_keys' => [
                        0 => 'sea',
                        1 => 'shallow',
                        2 => 'mountain',
                    ],
                    'blocked_facility_keys' => [
                        0 => 'seabed_oil_field',
                        1 => 'seabed_base',
                        2 => 'mine',
                        3 => 'monument',
                        4 => 'capital',
                    ],
                    'defense_facility_key' => 'defense',
                    'destination_terrain_key' => 'wasteland',
                    'preserve_owner' => true,
                ],
                'trample_contract' => [
                    'population_after' => 0,
                    'remove_facility' => true,
                    'restore_previous_terrain' => false,
                ],
                'hardening_contract' => [
                    'type' => 'none',
                ],
                'source_metadata' => [
                    'kind' => 3,
                    'skill_code' => 0,
                    'filename' => 'monster1.gif',
                    'reward_policy' => 'standard_split',
                    'manual' => [
                        'appearance' => '人口25万人以上で自然発生',
                        'special' => '特殊能力なし',
                    ],
                    'behavior' => [
                        'movement' => 'legacy_land',
                        'dispatchable' => false,
                        'can_act_on_spawn_turn' => false,
                        'special_action' => 'none',
                        'island_creation_displaceable' => false,
                    ],
                ],
                'display_order' => 300,
            ],
            5 => [
                'key' => 'dark_inora',
                'name' => 'ダークいのら',
                'asset_key' => 'hakoniwa_original.monster.dark_inora',
                'hardened_asset_key' => null,
                'base_hp' => 2,
                'hp_variation' => 1,
                'skill_key' => 'move_2',
                'movement_limit' => 2,
                'natural_spawn_tier' => 2,
                'wreckage_value_money' => 800,
                'missile_base_experience' => 15,
                'experience_per_damage' => 6,
                'skill_description' => '1ターンに最大2歩移動',
                'visibility' => 'public',
                'movement_terrain_contract' => [
                    'candidate_attempts_per_action' => 3,
                    'blocked_terrain_keys' => [
                        0 => 'sea',
                        1 => 'shallow',
                        2 => 'mountain',
                    ],
                    'blocked_facility_keys' => [
                        0 => 'seabed_oil_field',
                        1 => 'seabed_base',
                        2 => 'mine',
                        3 => 'monument',
                        4 => 'capital',
                    ],
                    'defense_facility_key' => 'defense',
                    'destination_terrain_key' => 'wasteland',
                    'preserve_owner' => true,
                ],
                'trample_contract' => [
                    'population_after' => 0,
                    'remove_facility' => true,
                    'restore_previous_terrain' => false,
                ],
                'hardening_contract' => [
                    'type' => 'none',
                ],
                'source_metadata' => [
                    'kind' => 4,
                    'skill_code' => 1,
                    'filename' => 'monster2.gif',
                    'reward_policy' => 'standard_split',
                    'manual' => [
                        'appearance' => '人口25万人以上で自然発生',
                        'special' => '最大2歩移動',
                    ],
                    'behavior' => [
                        'movement' => 'legacy_land',
                        'dispatchable' => false,
                        'can_act_on_spawn_turn' => false,
                        'special_action' => 'none',
                        'island_creation_displaceable' => false,
                    ],
                ],
                'display_order' => 400,
            ],
            6 => [
                'key' => 'aoi_inora',
                'name' => 'あおいのら',
                'asset_key' => 'hakoniwa_custom.monster.aoi_inora',
                'hardened_asset_key' => null,
                'base_hp' => 2,
                'hp_variation' => 1,
                'skill_key' => 'none',
                'movement_limit' => 1,
                'natural_spawn_tier' => null,
                'wreckage_value_money' => 1200,
                'missile_base_experience' => 18,
                'experience_per_damage' => 8,
                'skill_description' => '海から陸地へ侵攻し、踏み荒らした場所を中立の海へ変える',
                'visibility' => 'public',
                'movement_terrain_contract' => [
                    'candidate_attempts_per_action' => 3,
                    'blocked_terrain_keys' => [
                        0 => 'mountain',
                    ],
                    'blocked_facility_keys' => [
                        0 => 'mine',
                        1 => 'monument',
                        2 => 'capital',
                    ],
                    'defense_facility_key' => 'defense',
                    'destination_terrain_key' => 'sea',
                    'clear_owner' => true,
                ],
                'trample_contract' => [
                    'population_after' => 0,
                    'remove_facility' => true,
                    'restore_previous_terrain' => false,
                ],
                'hardening_contract' => [
                    'type' => 'none',
                ],
                'source_metadata' => [
                    'reward_policy' => 'hostless_full_killer_money',
                    'manual' => [
                        'appearance' => 'Worldの海上災害',
                        'special' => '海から陸地へ侵攻し中立の海へ変化。中立海上の通常撃破は撃破者へ残骸資金100%',
                    ],
                    'behavior' => [
                        'movement' => 'water_neutralizing',
                        'dispatchable' => false,
                        'can_act_on_spawn_turn' => false,
                        'special_action' => 'none',
                        'island_creation_displaceable' => true,
                        'world_spawn' => [
                            'type' => 'world_aoi_disaster',
                            'probability_per_active_owned_land_cell' => [
                                'numerator' => 1,
                                'denominator' => 10000,
                            ],
                            'maximum_probability_numerator' => 10000,
                            'terrain_keys' => [
                                0 => 'sea',
                                1 => 'shallow',
                            ],
                            'minimum_land_distance' => 4,
                            'stream_version' => 1,
                        ],
                    ],
                ],
                'display_order' => 450,
            ],
            7 => [
                'key' => 'inora_ghost',
                'name' => 'いのらゴースト',
                'asset_key' => 'hakoniwa_original.monster.inora_ghost',
                'hardened_asset_key' => null,
                'base_hp' => 1,
                'hp_variation' => 0,
                'skill_key' => 'move_9999',
                'movement_limit' => 9999,
                'natural_spawn_tier' => 2,
                'wreckage_value_money' => 300,
                'missile_base_experience' => 10,
                'experience_per_damage' => 10,
                'skill_description' => '1ターンに最大？歩移動',
                'visibility' => 'public',
                'movement_terrain_contract' => [
                    'candidate_attempts_per_action' => 3,
                    'blocked_terrain_keys' => [
                        0 => 'sea',
                        1 => 'shallow',
                        2 => 'mountain',
                    ],
                    'blocked_facility_keys' => [
                        0 => 'seabed_oil_field',
                        1 => 'seabed_base',
                        2 => 'mine',
                        3 => 'monument',
                        4 => 'capital',
                    ],
                    'defense_facility_key' => 'defense',
                    'destination_terrain_key' => 'wasteland',
                    'preserve_owner' => true,
                ],
                'trample_contract' => [
                    'population_after' => 0,
                    'remove_facility' => true,
                    'restore_previous_terrain' => false,
                ],
                'hardening_contract' => [
                    'type' => 'none',
                ],
                'source_metadata' => [
                    'kind' => 5,
                    'skill_code' => 2,
                    'filename' => 'monster8.gif',
                    'reward_policy' => 'standard_split',
                    'manual' => [
                        'appearance' => '人口25万人以上で自然発生',
                        'special' => '高速移動',
                    ],
                    'behavior' => [
                        'movement' => 'legacy_land',
                        'dispatchable' => false,
                        'can_act_on_spawn_turn' => false,
                        'special_action' => 'none',
                        'island_creation_displaceable' => false,
                    ],
                ],
                'display_order' => 500,
            ],
            8 => [
                'key' => 'whale',
                'name' => 'クジラ',
                'asset_key' => 'hakoniwa_original.monster.kujira',
                'hardened_asset_key' => 'hakoniwa_original.monster.hardened',
                'base_hp' => 4,
                'hp_variation' => 1,
                'skill_key' => 'harden_even',
                'movement_limit' => 1,
                'natural_spawn_tier' => 3,
                'wreckage_value_money' => 1500,
                'missile_base_experience' => 20,
                'experience_per_damage' => 5,
                'skill_description' => '偶数ターンは硬化し、移動と通常ダメージを無効化',
                'visibility' => 'public',
                'movement_terrain_contract' => [
                    'candidate_attempts_per_action' => 3,
                    'blocked_terrain_keys' => [
                        0 => 'sea',
                        1 => 'shallow',
                        2 => 'mountain',
                    ],
                    'blocked_facility_keys' => [
                        0 => 'seabed_oil_field',
                        1 => 'seabed_base',
                        2 => 'mine',
                        3 => 'monument',
                        4 => 'capital',
                    ],
                    'defense_facility_key' => 'defense',
                    'destination_terrain_key' => 'wasteland',
                    'preserve_owner' => true,
                ],
                'trample_contract' => [
                    'population_after' => 0,
                    'remove_facility' => true,
                    'restore_previous_terrain' => false,
                ],
                'hardening_contract' => [
                    'type' => 'target_turn_parity',
                    'parity' => 'even',
                ],
                'source_metadata' => [
                    'kind' => 6,
                    'skill_code' => 4,
                    'filename' => 'monster6.gif',
                    'reward_policy' => 'standard_split',
                    'manual' => [
                        'appearance' => '人口40万人以上で自然発生',
                        'special' => '偶数ターンは硬化',
                    ],
                    'behavior' => [
                        'movement' => 'legacy_land',
                        'dispatchable' => false,
                        'can_act_on_spawn_turn' => false,
                        'special_action' => 'none',
                        'island_creation_displaceable' => false,
                    ],
                ],
                'display_order' => 600,
            ],
            9 => [
                'key' => 'king_inora',
                'name' => 'キングいのら',
                'asset_key' => 'hakoniwa_original.monster.king_inora',
                'hardened_asset_key' => null,
                'base_hp' => 5,
                'hp_variation' => 1,
                'skill_key' => 'none',
                'movement_limit' => 1,
                'natural_spawn_tier' => 3,
                'wreckage_value_money' => 2000,
                'missile_base_experience' => 30,
                'experience_per_damage' => 6,
                'skill_description' => '特殊能力なし（最大1歩移動）',
                'visibility' => 'public',
                'movement_terrain_contract' => [
                    'candidate_attempts_per_action' => 3,
                    'blocked_terrain_keys' => [
                        0 => 'sea',
                        1 => 'shallow',
                        2 => 'mountain',
                    ],
                    'blocked_facility_keys' => [
                        0 => 'seabed_oil_field',
                        1 => 'seabed_base',
                        2 => 'mine',
                        3 => 'monument',
                        4 => 'capital',
                    ],
                    'defense_facility_key' => 'defense',
                    'destination_terrain_key' => 'wasteland',
                    'preserve_owner' => true,
                ],
                'trample_contract' => [
                    'population_after' => 0,
                    'remove_facility' => true,
                    'restore_previous_terrain' => false,
                ],
                'hardening_contract' => [
                    'type' => 'none',
                ],
                'source_metadata' => [
                    'kind' => 7,
                    'skill_code' => 0,
                    'filename' => 'monster3.gif',
                    'reward_policy' => 'standard_split',
                    'manual' => [
                        'appearance' => '人口40万人以上で自然発生',
                        'special' => '特殊能力なし',
                    ],
                    'behavior' => [
                        'movement' => 'legacy_land',
                        'dispatchable' => false,
                        'can_act_on_spawn_turn' => false,
                        'special_action' => 'none',
                        'island_creation_displaceable' => false,
                    ],
                ],
                'display_order' => 700,
            ],
        ],
        'monster_system' => [
            'footprint_cells' => 1,
            'natural_spawn' => [
                'probability_per_land_cell' => [
                    'numerator' => 2,
                    'denominator' => 10000,
                ],
                'maximum_probability_numerator' => 10000,
                'one_draw_per_active_nation' => true,
                'eligible_nation_state' => 'active',
                'minimum_population' => 100000,
                'population_tiers' => [
                    0 => [
                        'minimum_population' => 100000,
                        'monster_keys' => [
                            0 => 'inora',
                            1 => 'sanjira',
                        ],
                    ],
                    1 => [
                        'minimum_population' => 250000,
                        'monster_keys' => [
                            0 => 'inora',
                            1 => 'sanjira',
                            2 => 'red_inora',
                            3 => 'dark_inora',
                            4 => 'inora_ghost',
                        ],
                    ],
                    2 => [
                        'minimum_population' => 400000,
                        'monster_keys' => [
                            0 => 'inora',
                            1 => 'sanjira',
                            2 => 'red_inora',
                            3 => 'dark_inora',
                            4 => 'inora_ghost',
                            5 => 'whale',
                            6 => 'king_inora',
                        ],
                    ],
                ],
                'settlement_facility_keys' => [
                    0 => 'village',
                    1 => 'town',
                    2 => 'city',
                ],
                'exclude_capital' => true,
                'maximum_per_nation_per_turn' => 1,
                'selection' => 'uniform_source_pool',
                'stream_version' => 1,
            ],
            'movement' => [
                'candidate_attempts_per_action' => 3,
                'blocked_terrain_keys' => [
                    0 => 'sea',
                    1 => 'shallow',
                    2 => 'mountain',
                ],
                'blocked_facility_keys' => [
                    0 => 'seabed_oil_field',
                    1 => 'seabed_base',
                    2 => 'mine',
                    3 => 'monument',
                    4 => 'capital',
                ],
                'defense_facility_key' => 'defense',
                'destination_terrain_key' => 'wasteland',
                'preserve_owner' => true,
            ],
            'reward' => [
                'killer_money_share' => 'floor_half',
                'host_remainder_share' => true,
                'host_food_resource_key' => 'monster_meat',
                'food_tons_per_money_unit' => 500,
                'missile_base_experience_maximum' => 200,
            ],
            'terrain_events' => [
                'preserve_occupancy' => [
                    0 => 'earthquake',
                    1 => 'tsunami',
                    2 => 'typhoon',
                ],
                'remove_without_rewards' => [
                    0 => 'meteor_shower',
                    1 => 'huge_meteor',
                    2 => 'eruption',
                    3 => 'land_subsidence',
                    4 => 'defense_self_destruct',
                    5 => 'terrain_destruction_missile',
                ],
            ],
            'kill_stats' => [
                'scope' => 'nation_monster_definition',
                'increment_on_attributed_final_blow' => true,
                'authoritative_for_final_blow_count' => true,
                'authoritative_for_kill_marks' => true,
            ],
        ],
        'military' => [
            'launch_base_facility_keys' => [
                0 => 'missile_base',
                1 => 'seabed_base',
            ],
            'missiles' => [
                'missile' => [
                    'cost_money_per_shot' => 20,
                    'deviation_radius' => 2,
                    'creates_terrain' => 'scorched',
                    'refugees' => true,
                ],
                'pp_missile' => [
                    'cost_money_per_shot' => 50,
                    'deviation_radius' => 1,
                    'creates_terrain' => 'scorched',
                    'refugees' => true,
                ],
                'land_destruction_missile' => [
                    'cost_money_per_shot' => 100,
                    'deviation_radius' => 2,
                    'creates_terrain' => null,
                    'refugees' => false,
                ],
                'spp_missile' => [
                    'cost_money_per_shot' => 500,
                    'deviation_radius' => 0,
                    'creates_terrain' => 'scorched',
                    'refugees' => true,
                ],
            ],
            'visibility' => [
                'launch_summary' => 'public',
                'meaningful_impacts' => 'public',
                'ineffective_impacts' => 'aggregate_per_launch',
                'firing_nation_details' => 'private',
                'anonymous_missile_keys' => [
                ],
            ],
            'dormant_impact' => [
                'explicit_target_state' => 'any_existing_coordinate',
                'no_effect_owner_states' => [
                ],
                'preserve' => [
                    0 => 'cell',
                    1 => 'facility',
                    2 => 'population',
                    3 => 'monster_occupancy',
                ],
                'monster_exception' => false,
            ],
            'refugees' => [
                'settlement_facility_keys' => [
                    0 => 'village',
                    1 => 'town',
                    2 => 'city',
                    3 => 'capital',
                ],
                'recipient' => 'firing_nation',
                'generated_fraction' => [
                    'numerator' => 1,
                    'denominator' => 2,
                ],
                'event_types' => [
                    0 => 'refugee_generated',
                    1 => 'refugee_received',
                ],
            ],
            'launch_base_experience' => [
                'facility_keys' => [
                    0 => 'missile_base',
                    1 => 'seabed_base',
                ],
                'settlement_hit' => [
                    'missile_keys' => [
                        0 => 'missile',
                        1 => 'pp_missile',
                        2 => 'spp_missile',
                    ],
                    'population_divisor' => 2000,
                    'capital_population_loss_multiplier' => 2,
                ],
                'monster_damage_experience' => 'actual_damage_times_monster_definition.experience_per_damage',
                'monster_final_blow_experience' => 0,
            ],
            'seabed_base_resistance' => [
                'facility_key' => 'seabed_base',
                'ineffective_missile_keys' => [
                    0 => 'missile',
                    1 => 'pp_missile',
                    2 => 'spp_missile',
                ],
                'destructive_missile_keys' => [
                    0 => 'land_destruction_missile',
                ],
            ],
            'defense_spp_resistance' => [
                'facility_key' => 'defense',
                'ineffective_missile_keys' => [
                    0 => 'spp_missile',
                ],
            ],
            'defense_interception' => [
                'facility_key' => 'defense',
                'radius' => 2,
                'exclude_center' => true,
                'defense_target_cells' => 'exclude',
                'missile_keys' => [
                    0 => 'missile',
                    1 => 'pp_missile',
                    2 => 'land_destruction_missile',
                    3 => 'spp_missile',
                ],
                'facility_owner_scope' => 'any',
                'monster_occupied_cells' => 'include',
                'self_fired_missiles' => 'include',
                'overlap_resolution' => 'single_interception',
                'resolve_before' => 'secretary',
            ],
        ],
    ],
    'classification' => [
        'behavior' => $behavior,
        'data' => $data,
        'flavor' => $flavor,
    ],
];
