<?php

return [
    'payload' => [
        'secretary' => [
            'capacity_bonus' => [
                'level_source' => 'sum_passive_skill_levels',
                'money_percent_per_level' => 1,
                'food_percent_per_level' => 1,
                'rounding' => 'floor_after_multiplier',
                'cap' => null,
            ],
            'skills' => [
                'agricultural_policy' => [
                    'key' => 'agricultural_policy',
                    'name' => '農業政策',
                    'initial_level' => 0,
                    'level_requirement' => [
                        'basis' => 'next_level_squared',
                        'multiplier' => 1,
                    ],
                    'effect' => [
                        'type' => 'production_multiplier',
                        'resource_key' => 'wheat',
                        'per_mille_per_level' => 1,
                    ],
                    'experience_source' => [
                        'type' => 'successful_command_execution',
                        'command_key' => 'build_farm',
                        'points_per_execution' => 1,
                        'quantity_multiplier' => false,
                    ],
                ],
                'specialty_development' => [
                    'key' => 'specialty_development',
                    'name' => '特産品開発',
                    'initial_level' => 0,
                    'level_requirement' => [
                        'basis' => 'next_level_squared',
                        'multiplier' => 1,
                    ],
                    'effect' => [
                        'type' => 'production_multiplier',
                        'resource_key' => 'industrial_goods',
                        'per_mille_per_level' => 1,
                    ],
                    'experience_source' => [
                        'type' => 'successful_command_execution',
                        'command_key' => 'build_factory',
                        'points_per_execution' => 1,
                        'quantity_multiplier' => false,
                    ],
                ],
                'gold_vein_survey' => [
                    'key' => 'gold_vein_survey',
                    'name' => '金鉱脈調査',
                    'initial_level' => 0,
                    'level_requirement' => [
                        'basis' => 'next_level_squared',
                        'multiplier' => 1,
                    ],
                    'effect' => [
                        'type' => 'production_multiplier',
                        'resource_key' => 'minerals',
                        'per_mille_per_level' => 1,
                    ],
                    'experience_source' => [
                        'type' => 'successful_command_execution',
                        'command_key' => 'build_mine',
                        'points_per_execution' => 1,
                        'quantity_multiplier' => false,
                    ],
                ],
                'forest_management' => [
                    'key' => 'forest_management',
                    'name' => '森林管理',
                    'initial_level' => 0,
                    'level_requirement' => [
                        'basis' => 'next_level_squared',
                        'multiplier' => 1,
                    ],
                    'effect' => [
                        'type' => 'forest_management',
                        'percent_per_level' => 1,
                        'rounding' => 'floor_after_multiplier',
                        'logging_base' => 'canonical_logging_income',
                        'forest_growth_base' => 'terrain_quantities.forest.growth_increment',
                    ],
                    'experience_source' => [
                        'type' => 'successful_command_execution',
                        'command_keys' => [
                            0 => 'logging',
                            1 => 'plant_forest',
                        ],
                        'points_per_execution' => 1,
                        'quantity_multiplier' => false,
                        'historical_backfill' => false,
                    ],
                ],
                'final_defense_line' => [
                    'key' => 'final_defense_line',
                    'name' => '最終防衛ライン',
                    'initial_level' => 1,
                    'level_requirement' => [
                        'basis' => 'current_level_squared',
                        'multiplier' => 100,
                    ],
                    'effect' => [
                        'type' => 'final_defense_line',
                        'interceptions_per_level_per_turn' => 1,
                        'normal_defense_resolves_first' => true,
                        'exclude_monster_occupied_cells' => true,
                    ],
                    'experience_source' => [
                        'type' => 'owned_cell_missile_arrival',
                        'points_per_missile' => 1,
                        'include_normal_defense_interception' => true,
                        'include_secretary_interception' => true,
                        'include_actual_impact' => true,
                        'include_self_fired_collateral' => true,
                        'independent_from_interception_eligibility' => true,
                    ],
                ],
                'declining_birthrate_policy' => [
                    'key' => 'declining_birthrate_policy',
                    'name' => '少子化対策',
                    'initial_level' => 0,
                    'level_requirement' => [
                        'basis' => 'triangular_growth',
                        'multiplier' => 10000,
                        'accounting' => 'cumulative_non_consuming',
                    ],
                    'effect' => [
                        'type' => 'settlement_population_limits',
                        'natural_maximum_per_level' => 50,
                        'attraction_maximum_per_level' => 100,
                        'capital_maximum_modifier' => 0,
                    ],
                    'experience_source' => [
                        'type' => 'nation_population_high_water_increase',
                        'checkpoint' => 'nations.population_high_water',
                        'timing' => 'final_population_before_secretary_experience_flush',
                        'historical_backfill' => 'authoritative_turn_summary_and_current_population_only',
                    ],
                ],
                'indomitable' => [
                    'key' => 'indomitable',
                    'name' => '不屈',
                    'initial_level' => 0,
                    'level_requirement' => [
                        'basis' => 'triangular_growth',
                        'multiplier' => 10000,
                        'accounting' => 'consume_required_carry_remainder',
                    ],
                    'effect' => [
                        'type' => 'natural_population_growth_percent',
                        'basis_points_per_level' => 25,
                        'rounding' => 'floor',
                        'maximum' => 'effective_natural_maximum',
                        'extra_random_draw' => false,
                    ],
                    'experience_source' => [
                        'type' => 'turn_net_population_loss',
                        'calculation' => 'max_zero_start_population_minus_end_population',
                        'timing' => 'final_population_before_secretary_experience_flush',
                        'historical_backfill' => 'authoritative_turn_summary_only',
                    ],
                ],
                'ship_operations' => [
                    'key' => 'ship_operations',
                    'name' => '船舶運用',
                    'initial_level' => 0,
                    'level_requirement' => [
                        'basis' => 'next_level_linear',
                        'multiplier' => 100,
                    ],
                    'effect' => [
                        'type' => 'placeholder',
                        'display' => '準備中',
                    ],
                    'experience_source' => [
                        'type' => 'successful_ship_movement',
                        'points_per_execution' => 1,
                        'quantity_multiplier' => false,
                    ],
                ],
                'navy' => [
                    'key' => 'navy',
                    'name' => '海軍',
                    'initial_level' => 0,
                    'level_requirement' => [
                        'basis' => 'next_level_linear',
                        'multiplier' => 30,
                    ],
                    'effect' => [
                        'type' => 'placeholder',
                        'display' => '効果なし',
                    ],
                    'experience_source' => [
                        'type' => 'successful_warship_hit',
                        'target_experience' => 'normal_missile_hit_equivalent',
                    ],
                ],
            ],
            'item_rarities' => [
                'novice' => [
                    'key' => 'novice',
                    'name' => 'ノービス',
                    'fixed_sale_price_money' => 100,
                ],
                'regular' => [
                    'key' => 'regular',
                    'name' => 'レギュラー',
                    'fixed_sale_price_money' => 500,
                ],
                'cursed' => [
                    'key' => 'cursed',
                    'name' => 'カースド',
                    'fixed_sale_price_money' => 1,
                ],
                'high_quality' => [
                    'key' => 'high_quality',
                    'name' => 'ハイクオリティ',
                    'fixed_sale_price_money' => 1500,
                ],
                'artifact' => [
                    'key' => 'artifact',
                    'name' => 'アーティファクト',
                    'fixed_sale_price_money' => 3000,
                ],
                'relic' => [
                    'key' => 'relic',
                    'name' => 'レリック',
                    'fixed_sale_price_money' => 6000,
                ],
            ],
            'item_categories' => [
                'accessory' => [
                    'key' => 'accessory',
                    'max_equipped' => 99,
                ],
                'bow' => [
                    'key' => 'bow',
                    'max_equipped' => 1,
                ],
                'clothing' => [
                    'key' => 'clothing',
                    'max_equipped' => 1,
                ],
                'ticket' => [
                    'key' => 'ticket',
                    'max_equipped' => 0,
                ],
            ],
            'items' => [
                'old_bow' => [
                    'key' => 'old_bow',
                    'category' => 'bow',
                    'rarity' => 'novice',
                    'tradable' => false,
                    'npc_tradable' => false,
                    'max_level' => 1,
                    'effects' => [
                        0 => [
                            'type' => 'pre_normal_monster_attack',
                            'timing' => 'after_missile_finalization_before_normal_monsters',
                            'chance_basis_points' => 1000,
                            'damage' => 1,
                            'damage_type' => 'secretary_old_bow',
                            'target_scope' => 'owned_territory',
                            'target_map_space_keys' => [
                                0 => 'surface',
                            ],
                            'target_safety_policy' => 'avoid_ineffective_or_immediate_hazard',
                            'random_stream_version' => 1,
                        ],
                    ],
                    'gacha_exception' => true,
                ],
                'ring' => [
                    'key' => 'ring',
                    'category' => 'accessory',
                    'rarity' => 'novice',
                    'tradable' => true,
                    'npc_tradable' => true,
                    'max_level' => 10,
                    'effects' => [
                        0 => [
                            'type' => 'finance_income_bonus',
                            'bonus_money_per_level' => 1,
                            'stacking' => 'sum_equipped_levels',
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'secretary_suit' => [
                    'key' => 'secretary_suit',
                    'category' => 'clothing',
                    'rarity' => 'novice',
                    'tradable' => true,
                    'npc_tradable' => true,
                    'max_level' => 10,
                    'effects' => [
                        0 => [
                            'type' => 'secretary_experience_double_chance',
                            'chance_percent_per_level' => 1,
                            'multiplier' => 2,
                            'sources' => [
                                0 => 'passive_skill_experience',
                                1 => 'monster_experience',
                            ],
                            'draw_unit' => 'canonical_award_event',
                            'random_stream_version' => 1,
                            'excluded_skill_keys' => [
                                0 => 'declining_birthrate_policy',
                            ],
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'inora_bracelet' => [
                    'key' => 'inora_bracelet',
                    'category' => 'accessory',
                    'rarity' => 'novice',
                    'tradable' => true,
                    'npc_tradable' => true,
                    'max_level' => 10,
                    'effects' => [
                        0 => [
                            'type' => 'natural_monster_spawn_percent',
                            'source_genre' => 'item',
                            'target' => 'normal_nation_natural_spawn',
                            'percent_per_level' => 10,
                            'minimum_final_probability' => 0,
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'hoarder_talisman' => [
                    'key' => 'hoarder_talisman',
                    'category' => 'accessory',
                    'rarity' => 'novice',
                    'tradable' => true,
                    'npc_tradable' => true,
                    'max_level' => 10,
                    'effects' => [
                        0 => [
                            'type' => 'capacity_percent',
                            'source_genre' => 'item',
                            'target' => 'all_nation_resources',
                            'percent_per_level' => 1,
                            'rounding' => 'floor_after_all_source_genres',
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'good_person_treasure' => [
                    'key' => 'good_person_treasure',
                    'category' => 'accessory',
                    'rarity' => 'novice',
                    'tradable' => true,
                    'npc_tradable' => true,
                    'max_level' => 20,
                    'effects' => [
                        0 => [
                            'type' => 'karma_minimum_delta',
                            'lower_minimum_per_level' => 1,
                            'snapshot_timing' => 'turn_start',
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'vault_key' => [
                    'key' => 'vault_key',
                    'category' => 'accessory',
                    'rarity' => 'novice',
                    'tradable' => true,
                    'npc_tradable' => true,
                    'max_level' => 10,
                    'effects' => [
                        0 => [
                            'type' => 'capacity_percent',
                            'source_genre' => 'item',
                            'target' => 'money',
                            'percent_per_level' => 1,
                            'rounding' => 'floor_after_all_source_genres',
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'monster_repellent_incense' => [
                    'key' => 'monster_repellent_incense',
                    'category' => 'accessory',
                    'rarity' => 'novice',
                    'tradable' => true,
                    'npc_tradable' => true,
                    'max_level' => 10,
                    'effects' => [
                        0 => [
                            'type' => 'natural_monster_spawn_percent',
                            'source_genre' => 'item',
                            'target' => 'normal_nation_natural_spawn',
                            'percent_per_level' => -1,
                            'minimum_final_probability' => 0,
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'fullness_herb' => [
                    'key' => 'fullness_herb',
                    'category' => 'accessory',
                    'rarity' => 'novice',
                    'tradable' => true,
                    'npc_tradable' => true,
                    'max_level' => 10,
                    'effects' => [
                        0 => [
                            'type' => 'capacity_percent',
                            'source_genre' => 'item',
                            'target' => 'food_aggregate',
                            'percent_per_level' => 2,
                            'rounding' => 'floor_after_all_source_genres',
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'elf_bow' => [
                    'key' => 'elf_bow',
                    'category' => 'bow',
                    'rarity' => 'regular',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 10,
                    'effects' => [
                        0 => [
                            'type' => 'pre_normal_monster_attack',
                            'timing' => 'after_missile_finalization_before_normal_monsters',
                            'chance_base_basis_points' => 1100,
                            'chance_basis_points_per_level' => 100,
                            'damage' => 1,
                            'damage_type' => 'secretary_elf_bow',
                            'target_scope' => 'owned_territory',
                            'target_map_space_keys' => [
                                0 => 'surface',
                            ],
                            'target_safety_policy' => 'avoid_ineffective_or_immediate_hazard',
                            'random_stream_version' => 1,
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'longshot_bow' => [
                    'key' => 'longshot_bow',
                    'category' => 'bow',
                    'rarity' => 'regular',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 10,
                    'effects' => [
                        0 => [
                            'type' => 'pre_normal_monster_attack',
                            'timing' => 'after_missile_finalization_before_normal_monsters',
                            'chance_base_basis_points' => 1100,
                            'chance_basis_points_per_level' => 100,
                            'damage' => 1,
                            'damage_type' => 'secretary_longshot_bow',
                            'target_scope' => 'owned_territory_or_surface_aoi_inora',
                            'target_map_space_keys' => [
                                0 => 'surface',
                            ],
                            'target_safety_policy' => 'avoid_ineffective_or_immediate_hazard',
                            'random_stream_version' => 1,
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'mechanical_bow' => [
                    'key' => 'mechanical_bow',
                    'category' => 'bow',
                    'rarity' => 'regular',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 10,
                    'effects' => [
                        0 => [
                            'type' => 'pre_normal_monster_attack',
                            'timing' => 'after_missile_finalization_before_normal_monsters',
                            'chance_base_basis_points' => 900,
                            'chance_basis_points_per_level' => 100,
                            'damage' => 1,
                            'damage_type' => 'secretary_mechanical_bow',
                            'target_scope' => 'owned_territory',
                            'target_map_space_keys' => [
                                0 => 'surface',
                            ],
                            'target_safety_policy' => 'avoid_ineffective_or_immediate_hazard',
                            'finisher' => [
                                'current_hp' => 2,
                                'damage' => 2,
                                'chance_multiplier_numerator' => 2,
                                'chance_multiplier_denominator' => 5,
                                'requires_damage_one_safety_rejection' => true,
                                'requires_damage_two_kill' => true,
                            ],
                            'random_stream_version' => 1,
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'collar' => [
                    'key' => 'collar',
                    'category' => 'accessory',
                    'rarity' => 'cursed',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 11,
                    'effects' => [
                        0 => [
                            'type' => 'refugee_generation_percent',
                            'minimum_start_karma' => 1,
                            'base_percent' => 4,
                            'percent_per_level' => 1,
                            'rounding' => 'floor',
                            'apply_after' => 'karma_refugee_generation',
                        ],
                        1 => [
                            'type' => 'karma_crime_double_chance',
                            'base_percent' => 4,
                            'percent_per_level' => 1,
                            'multiplier' => 2,
                            'facility_keys' => [
                                0 => 'village',
                                1 => 'town',
                                2 => 'city',
                                3 => 'capital',
                            ],
                            'draw_unit' => 'qualifying_impact',
                            'snapshot_timing' => 'turn_start',
                            'random_stream_version' => 1,
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'wakuwaku_ticket' => [
                    'key' => 'wakuwaku_ticket',
                    'category' => 'ticket',
                    'rarity' => 'regular',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 1,
                    'effects' => [
                    ],
                    'gacha_exception' => true,
                ],
                'dokidoki_ticket' => [
                    'key' => 'dokidoki_ticket',
                    'category' => 'ticket',
                    'rarity' => 'high_quality',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 1,
                    'effects' => [
                    ],
                    'gacha_exception' => true,
                ],
                'fire_charm' => [
                    'key' => 'fire_charm',
                    'category' => 'accessory',
                    'rarity' => 'regular',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 3,
                    'effects' => [
                        0 => [
                            'type' => 'disaster_guard',
                            'disaster_key' => 'fire',
                            'cells_per_charge' => 1,
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'wave_charm' => [
                    'key' => 'wave_charm',
                    'category' => 'accessory',
                    'rarity' => 'regular',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 3,
                    'effects' => [
                        0 => [
                            'type' => 'disaster_guard',
                            'disaster_key' => 'tsunami',
                            'cells_per_charge' => 1,
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'wind_charm' => [
                    'key' => 'wind_charm',
                    'category' => 'accessory',
                    'rarity' => 'regular',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 3,
                    'effects' => [
                        0 => [
                            'type' => 'disaster_guard',
                            'disaster_key' => 'typhoon',
                            'cells_per_charge' => 1,
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'quake_charm' => [
                    'key' => 'quake_charm',
                    'category' => 'accessory',
                    'rarity' => 'regular',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 3,
                    'effects' => [
                        0 => [
                            'type' => 'disaster_guard',
                            'disaster_key' => 'earthquake',
                            'cells_per_charge' => 1,
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'star_charm' => [
                    'key' => 'star_charm',
                    'category' => 'accessory',
                    'rarity' => 'high_quality',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 3,
                    'effects' => [
                        0 => [
                            'type' => 'disaster_guard',
                            'disaster_key' => 'meteor_shower',
                            'cells_per_charge' => 1,
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'gem_bow' => [
                    'key' => 'gem_bow',
                    'category' => 'bow',
                    'rarity' => 'high_quality',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 15,
                    'effects' => [
                        0 => [
                            'type' => 'pre_normal_monster_attack',
                            'timing' => 'after_missile_finalization_before_normal_monsters',
                            'chance_base_basis_points' => 2400,
                            'chance_basis_points_per_level' => 100,
                            'damage' => 1,
                            'damage_type' => 'secretary_gem_bow',
                            'target_scope' => 'owned_territory',
                            'target_map_space_keys' => [
                                0 => 'surface',
                            ],
                            'target_safety_policy' => 'avoid_ineffective_or_immediate_hazard',
                            'random_stream_version' => 1,
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'elven_bow' => [
                    'key' => 'elven_bow',
                    'category' => 'bow',
                    'rarity' => 'artifact',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 50,
                    'effects' => [
                        0 => [
                            'type' => 'pre_normal_monster_attack',
                            'timing' => 'after_missile_finalization_before_normal_monsters',
                            'chance_base_basis_points' => 4900,
                            'chance_basis_points_per_level' => 100,
                            'damage' => 1,
                            'damage_type' => 'secretary_elven_bow',
                            'target_scope' => 'owned_territory',
                            'target_map_space_keys' => [
                                0 => 'surface',
                            ],
                            'target_safety_policy' => 'avoid_ineffective_or_immediate_hazard',
                            'random_stream_version' => 1,
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'aquamarine_bow' => [
                    'key' => 'aquamarine_bow',
                    'category' => 'bow',
                    'rarity' => 'high_quality',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 15,
                    'effects' => [
                        0 => [
                            'type' => 'pre_normal_monster_attack',
                            'timing' => 'after_missile_finalization_before_normal_monsters',
                            'chance_base_basis_points' => 2400,
                            'chance_basis_points_per_level' => 100,
                            'damage' => 1,
                            'damage_type' => 'secretary_aquamarine_bow',
                            'target_scope' => 'owned_territory_or_surface_aoi_inora',
                            'target_map_space_keys' => [
                                0 => 'surface',
                            ],
                            'target_safety_policy' => 'avoid_ineffective_or_immediate_hazard',
                            'random_stream_version' => 1,
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'artemis_bow' => [
                    'key' => 'artemis_bow',
                    'category' => 'bow',
                    'rarity' => 'artifact',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 50,
                    'effects' => [
                        0 => [
                            'type' => 'pre_normal_monster_attack',
                            'timing' => 'after_missile_finalization_before_normal_monsters',
                            'chance_base_basis_points' => 4900,
                            'chance_basis_points_per_level' => 100,
                            'damage' => 1,
                            'damage_type' => 'secretary_artemis_bow',
                            'target_scope' => 'owned_territory_or_surface_aoi_inora',
                            'target_map_space_keys' => [
                                0 => 'surface',
                            ],
                            'target_safety_policy' => 'avoid_ineffective_or_immediate_hazard',
                            'random_stream_version' => 1,
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'bullseye_bow' => [
                    'key' => 'bullseye_bow',
                    'category' => 'bow',
                    'rarity' => 'high_quality',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 15,
                    'effects' => [
                        0 => [
                            'type' => 'pre_normal_monster_attack',
                            'timing' => 'after_missile_finalization_before_normal_monsters',
                            'chance_base_basis_points' => 1900,
                            'chance_basis_points_per_level' => 100,
                            'damage' => 1,
                            'damage_type' => 'secretary_bullseye_bow',
                            'target_scope' => 'owned_territory',
                            'target_map_space_keys' => [
                                0 => 'surface',
                            ],
                            'target_safety_policy' => 'avoid_ineffective_or_immediate_hazard',
                            'random_stream_version' => 1,
                            'finisher' => [
                                'current_hp' => 2,
                                'damage' => 2,
                                'chance_multiplier_numerator' => 2,
                                'chance_multiplier_denominator' => 5,
                                'requires_damage_one_safety_rejection' => true,
                                'requires_damage_two_kill' => true,
                            ],
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'shiva_bow' => [
                    'key' => 'shiva_bow',
                    'category' => 'bow',
                    'rarity' => 'artifact',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 50,
                    'effects' => [
                        0 => [
                            'type' => 'pre_normal_monster_attack',
                            'timing' => 'after_missile_finalization_before_normal_monsters',
                            'chance_base_basis_points' => 3900,
                            'chance_basis_points_per_level' => 100,
                            'damage' => 1,
                            'damage_type' => 'secretary_shiva_bow',
                            'target_scope' => 'owned_territory',
                            'target_map_space_keys' => [
                                0 => 'surface',
                            ],
                            'target_safety_policy' => 'avoid_ineffective_or_immediate_hazard',
                            'random_stream_version' => 1,
                            'finisher' => [
                                'current_hp' => 2,
                                'damage' => 2,
                                'chance_multiplier_numerator' => 2,
                                'chance_multiplier_denominator' => 5,
                                'requires_damage_one_safety_rejection' => true,
                                'requires_damage_two_kill' => true,
                            ],
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'experienced_suit' => [
                    'key' => 'experienced_suit',
                    'category' => 'clothing',
                    'rarity' => 'regular',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 10,
                    'effects' => [
                        0 => [
                            'type' => 'secretary_experience_double_chance',
                            'chance_base_percent' => 12,
                            'chance_percent_per_level' => 1,
                            'chance_multiplier_numerator' => 1,
                            'chance_multiplier_denominator' => 1,
                            'multiplier' => 2,
                            'sources' => [
                                0 => 'passive_skill_experience',
                                1 => 'monster_experience',
                            ],
                            'eligible_skill_keys' => [
                            ],
                            'excluded_skill_keys' => [
                                0 => 'declining_birthrate_policy',
                            ],
                            'draw_unit' => 'canonical_award_event',
                            'random_stream_version' => 1,
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'eternal_suit' => [
                    'key' => 'eternal_suit',
                    'category' => 'clothing',
                    'rarity' => 'high_quality',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 11,
                    'effects' => [
                        0 => [
                            'type' => 'secretary_experience_double_chance',
                            'chance_base_percent' => 24,
                            'chance_percent_per_level' => 1,
                            'chance_multiplier_numerator' => 1,
                            'chance_multiplier_denominator' => 1,
                            'multiplier' => 2,
                            'sources' => [
                                0 => 'passive_skill_experience',
                                1 => 'monster_experience',
                            ],
                            'eligible_skill_keys' => [
                            ],
                            'excluded_skill_keys' => [
                                0 => 'declining_birthrate_policy',
                            ],
                            'draw_unit' => 'canonical_award_event',
                            'random_stream_version' => 1,
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'star_reader_suit' => [
                    'key' => 'star_reader_suit',
                    'category' => 'clothing',
                    'rarity' => 'artifact',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 12,
                    'effects' => [
                        0 => [
                            'type' => 'secretary_experience_double_chance',
                            'chance_base_percent' => 38,
                            'chance_percent_per_level' => 1,
                            'chance_multiplier_numerator' => 1,
                            'chance_multiplier_denominator' => 1,
                            'multiplier' => 2,
                            'sources' => [
                                0 => 'passive_skill_experience',
                                1 => 'monster_experience',
                            ],
                            'eligible_skill_keys' => [
                            ],
                            'excluded_skill_keys' => [
                                0 => 'declining_birthrate_policy',
                            ],
                            'draw_unit' => 'canonical_award_event',
                            'random_stream_version' => 1,
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'military_suit' => [
                    'key' => 'military_suit',
                    'category' => 'clothing',
                    'rarity' => 'regular',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 10,
                    'effects' => [
                        0 => [
                            'type' => 'secretary_experience_double_chance',
                            'chance_base_percent' => 12,
                            'chance_percent_per_level' => 1,
                            'chance_multiplier_numerator' => 3,
                            'chance_multiplier_denominator' => 2,
                            'multiplier' => 2,
                            'sources' => [
                                0 => 'passive_skill_experience',
                                1 => 'monster_experience',
                            ],
                            'eligible_skill_keys' => [
                                0 => 'final_defense_line',
                                1 => 'navy',
                            ],
                            'excluded_skill_keys' => [
                                0 => 'declining_birthrate_policy',
                            ],
                            'draw_unit' => 'canonical_award_event',
                            'random_stream_version' => 1,
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'marshal_suit' => [
                    'key' => 'marshal_suit',
                    'category' => 'clothing',
                    'rarity' => 'high_quality',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 11,
                    'effects' => [
                        0 => [
                            'type' => 'secretary_experience_double_chance',
                            'chance_base_percent' => 24,
                            'chance_percent_per_level' => 1,
                            'chance_multiplier_numerator' => 3,
                            'chance_multiplier_denominator' => 2,
                            'multiplier' => 2,
                            'sources' => [
                                0 => 'passive_skill_experience',
                                1 => 'monster_experience',
                            ],
                            'eligible_skill_keys' => [
                                0 => 'final_defense_line',
                                1 => 'navy',
                            ],
                            'excluded_skill_keys' => [
                                0 => 'declining_birthrate_policy',
                            ],
                            'draw_unit' => 'canonical_award_event',
                            'random_stream_version' => 1,
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'war_suit' => [
                    'key' => 'war_suit',
                    'category' => 'clothing',
                    'rarity' => 'artifact',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 12,
                    'effects' => [
                        0 => [
                            'type' => 'secretary_experience_double_chance',
                            'chance_base_percent' => 38,
                            'chance_percent_per_level' => 1,
                            'chance_multiplier_numerator' => 3,
                            'chance_multiplier_denominator' => 2,
                            'multiplier' => 2,
                            'sources' => [
                                0 => 'passive_skill_experience',
                                1 => 'monster_experience',
                            ],
                            'eligible_skill_keys' => [
                                0 => 'final_defense_line',
                                1 => 'navy',
                            ],
                            'excluded_skill_keys' => [
                                0 => 'declining_birthrate_policy',
                            ],
                            'draw_unit' => 'canonical_award_event',
                            'random_stream_version' => 1,
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'chancellor_suit' => [
                    'key' => 'chancellor_suit',
                    'category' => 'clothing',
                    'rarity' => 'regular',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 10,
                    'effects' => [
                        0 => [
                            'type' => 'secretary_experience_double_chance',
                            'chance_base_percent' => 12,
                            'chance_percent_per_level' => 1,
                            'chance_multiplier_numerator' => 3,
                            'chance_multiplier_denominator' => 2,
                            'multiplier' => 2,
                            'sources' => [
                                0 => 'passive_skill_experience',
                            ],
                            'eligible_skill_keys' => [
                                0 => 'agricultural_policy',
                                1 => 'specialty_development',
                                2 => 'gold_vein_survey',
                                3 => 'forest_management',
                                4 => 'indomitable',
                                5 => 'ship_operations',
                            ],
                            'excluded_skill_keys' => [
                                0 => 'declining_birthrate_policy',
                            ],
                            'draw_unit' => 'canonical_award_event',
                            'random_stream_version' => 1,
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'grand_chancellor_suit' => [
                    'key' => 'grand_chancellor_suit',
                    'category' => 'clothing',
                    'rarity' => 'high_quality',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 11,
                    'effects' => [
                        0 => [
                            'type' => 'secretary_experience_double_chance',
                            'chance_base_percent' => 24,
                            'chance_percent_per_level' => 1,
                            'chance_multiplier_numerator' => 3,
                            'chance_multiplier_denominator' => 2,
                            'multiplier' => 2,
                            'sources' => [
                                0 => 'passive_skill_experience',
                            ],
                            'eligible_skill_keys' => [
                                0 => 'agricultural_policy',
                                1 => 'specialty_development',
                                2 => 'gold_vein_survey',
                                3 => 'forest_management',
                                4 => 'indomitable',
                                5 => 'ship_operations',
                            ],
                            'excluded_skill_keys' => [
                                0 => 'declining_birthrate_policy',
                            ],
                            'draw_unit' => 'canonical_award_event',
                            'random_stream_version' => 1,
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'star_chancellor_suit' => [
                    'key' => 'star_chancellor_suit',
                    'category' => 'clothing',
                    'rarity' => 'artifact',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 12,
                    'effects' => [
                        0 => [
                            'type' => 'secretary_experience_double_chance',
                            'chance_base_percent' => 38,
                            'chance_percent_per_level' => 1,
                            'chance_multiplier_numerator' => 3,
                            'chance_multiplier_denominator' => 2,
                            'multiplier' => 2,
                            'sources' => [
                                0 => 'passive_skill_experience',
                            ],
                            'eligible_skill_keys' => [
                                0 => 'agricultural_policy',
                                1 => 'specialty_development',
                                2 => 'gold_vein_survey',
                                3 => 'forest_management',
                                4 => 'indomitable',
                                5 => 'ship_operations',
                            ],
                            'excluded_skill_keys' => [
                                0 => 'declining_birthrate_policy',
                            ],
                            'draw_unit' => 'canonical_award_event',
                            'random_stream_version' => 1,
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'magic_white_flag' => [
                    'key' => 'magic_white_flag',
                    'category' => 'accessory',
                    'rarity' => 'high_quality',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 1,
                    'effects' => [
                        0 => [
                            'type' => 'monster_missile_defense_bypass',
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'nyowamiya_ribbon' => [
                    'key' => 'nyowamiya_ribbon',
                    'category' => 'accessory',
                    'rarity' => 'high_quality',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 1,
                    'effects' => [
                        0 => [
                            'type' => 'nyowamiya_ribbon',
                            'nyowamiya_type_weight_bonus' => 1,
                        ],
                    ],
                    'gacha_exception' => false,
                ],
                'love_emblem' => [
                    'key' => 'love_emblem',
                    'category' => 'accessory',
                    'rarity' => 'artifact',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 1,
                    'effects' => [
                        0 => [
                            'type' => 'population_growth_percent',
                            'percent' => 10,
                            'applies_to' => [
                                0 => 'ordinary',
                                1 => 'attraction',
                            ],
                        ],
                    ],
                    'gacha_exception' => true,
                ],
                'twin_star_emblem' => [
                    'key' => 'twin_star_emblem',
                    'category' => 'accessory',
                    'rarity' => 'artifact',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 1,
                    'effects' => [
                        0 => [
                            'type' => 'final_defense_preserve_chance',
                            'chance_percent' => 10,
                            'random_stream_version' => 1,
                        ],
                    ],
                    'gacha_exception' => true,
                ],
                'crescent_emblem' => [
                    'key' => 'crescent_emblem',
                    'category' => 'accessory',
                    'rarity' => 'artifact',
                    'tradable' => true,
                    'npc_tradable' => false,
                    'max_level' => 1,
                    'effects' => [
                        0 => [
                            'type' => 'launch_base_experience_double_chance',
                            'chance_percent' => 10,
                            'foreign_settlement_chance_percent' => 100,
                            'random_stream_version' => 1,
                        ],
                    ],
                    'gacha_exception' => true,
                ],
            ],
            'ticket_gacha' => [
                'wakuwaku_ticket' => [
                    'rarity_weights_basis_points' => [
                        'regular' => 6895,
                        'high_quality' => 2955,
                        'artifact' => 150,
                    ],
                ],
                'dokidoki_ticket' => [
                    'rarity_weights_basis_points' => [
                        'high_quality' => 7000,
                        'artifact' => 3000,
                    ],
                ],
            ],
        ],
    ],
    'classification' => [
        'behavior' => [
            0 => '/secretary/capacity_bonus/cap',
            1 => '/secretary/items/old_bow/effects/*/target_map_space_keys/*',
            2 => '/secretary/items/secretary_suit/effects/*/sources/*',
            3 => '/secretary/skills/forest_management/experience_source/command_keys/*',
            4 => 'basis',
            5 => 'category',
            6 => 'command_key',
            7 => 'damage_type',
            8 => 'draw_unit',
            9 => 'exclude_monster_occupied_cells',
            10 => 'forest_growth_base',
            11 => 'historical_backfill',
            12 => 'include_actual_impact',
            13 => 'include_normal_defense_interception',
            14 => 'include_secretary_interception',
            15 => 'include_self_fired_collateral',
            16 => 'independent_from_interception_eligibility',
            17 => 'key',
            18 => 'level_source',
            19 => 'logging_base',
            20 => 'normal_defense_resolves_first',
            21 => 'npc_tradable',
            22 => 'quantity_multiplier',
            23 => 'random_stream_version',
            24 => 'rarity',
            25 => 'resource_key',
            26 => 'rounding',
            27 => 'snapshot_timing',
            28 => 'source_genre',
            29 => 'stacking',
            30 => 'target',
            31 => 'target_safety_policy',
            32 => 'target_scope',
            33 => 'timing',
            34 => 'tradable',
            35 => 'type',
            36 => 'apply_after',
            37 => 'requires_damage_one_safety_rejection',
            38 => 'requires_damage_two_kill',
            39 => 'minimum_start_karma',
            40 => 'accounting',
            41 => 'checkpoint',
            42 => 'calculation',
            43 => 'maximum',
            44 => 'extra_random_draw',
            45 => '/secretary/items/elf_bow/effects/*/target_map_space_keys/*',
            46 => '/secretary/items/longshot_bow/effects/*/target_map_space_keys/*',
            47 => '/secretary/items/mechanical_bow/effects/*/target_map_space_keys/*',
            48 => '/secretary/items/collar/effects/*/facility_keys/*',
            49 => '/secretary/items/secretary_suit/effects/*/excluded_skill_keys/*',
            50 => 'target_experience',
            51 => 'gacha_exception',
            52 => 'disaster_key',
            53 => '/secretary/items/love_emblem/effects/*/applies_to/*',
            54 => '/secretary/items/gem_bow/effects/*/target_map_space_keys/*',
            55 => '/secretary/items/elven_bow/effects/*/target_map_space_keys/*',
            56 => '/secretary/items/aquamarine_bow/effects/*/target_map_space_keys/*',
            57 => '/secretary/items/artemis_bow/effects/*/target_map_space_keys/*',
            58 => '/secretary/items/bullseye_bow/effects/*/target_map_space_keys/*',
            59 => '/secretary/items/shiva_bow/effects/*/target_map_space_keys/*',
            60 => '/secretary/items/experienced_suit/effects/*/sources/*',
            61 => '/secretary/items/experienced_suit/effects/*/excluded_skill_keys/*',
            62 => '/secretary/items/eternal_suit/effects/*/sources/*',
            63 => '/secretary/items/eternal_suit/effects/*/excluded_skill_keys/*',
            64 => '/secretary/items/star_reader_suit/effects/*/sources/*',
            65 => '/secretary/items/star_reader_suit/effects/*/excluded_skill_keys/*',
            66 => '/secretary/items/military_suit/effects/*/sources/*',
            67 => '/secretary/items/military_suit/effects/*/excluded_skill_keys/*',
            68 => '/secretary/items/military_suit/effects/*/eligible_skill_keys/*',
            69 => '/secretary/items/marshal_suit/effects/*/sources/*',
            70 => '/secretary/items/marshal_suit/effects/*/excluded_skill_keys/*',
            71 => '/secretary/items/marshal_suit/effects/*/eligible_skill_keys/*',
            72 => '/secretary/items/war_suit/effects/*/sources/*',
            73 => '/secretary/items/war_suit/effects/*/excluded_skill_keys/*',
            74 => '/secretary/items/war_suit/effects/*/eligible_skill_keys/*',
            75 => '/secretary/items/chancellor_suit/effects/*/sources/*',
            76 => '/secretary/items/chancellor_suit/effects/*/excluded_skill_keys/*',
            77 => '/secretary/items/chancellor_suit/effects/*/eligible_skill_keys/*',
            78 => '/secretary/items/grand_chancellor_suit/effects/*/sources/*',
            79 => '/secretary/items/grand_chancellor_suit/effects/*/excluded_skill_keys/*',
            80 => '/secretary/items/grand_chancellor_suit/effects/*/eligible_skill_keys/*',
            81 => '/secretary/items/star_chancellor_suit/effects/*/sources/*',
            82 => '/secretary/items/star_chancellor_suit/effects/*/excluded_skill_keys/*',
            83 => '/secretary/items/star_chancellor_suit/effects/*/eligible_skill_keys/*',
        ],
        'data' => [
            0 => 'bonus_money_per_level',
            1 => 'chance_basis_points',
            2 => 'chance_percent_per_level',
            3 => 'damage',
            4 => 'food_percent_per_level',
            5 => 'initial_level',
            6 => 'interceptions_per_level_per_turn',
            7 => 'lower_minimum_per_level',
            8 => 'max_equipped',
            9 => 'max_level',
            10 => 'minimum_final_probability',
            11 => 'money_percent_per_level',
            12 => 'multiplier',
            13 => 'per_mille_per_level',
            14 => 'percent_per_level',
            15 => 'points_per_execution',
            16 => 'points_per_missile',
            17 => 'fixed_sale_price_money',
            18 => 'chance_base_basis_points',
            19 => 'chance_basis_points_per_level',
            20 => 'base_percent',
            21 => 'chance_multiplier_numerator',
            22 => 'chance_multiplier_denominator',
            23 => 'current_hp',
            24 => 'natural_maximum_per_level',
            25 => 'attraction_maximum_per_level',
            26 => 'capital_maximum_modifier',
            27 => 'basis_points_per_level',
            28 => 'chance_base_percent',
            29 => 'cells_per_charge',
            30 => 'nyowamiya_type_weight_bonus',
            31 => 'percent',
            32 => 'chance_percent',
            33 => 'foreign_settlement_chance_percent',
            34 => '/secretary/ticket_gacha/wakuwaku_ticket/rarity_weights_basis_points/regular',
            35 => '/secretary/ticket_gacha/wakuwaku_ticket/rarity_weights_basis_points/high_quality',
            36 => '/secretary/ticket_gacha/wakuwaku_ticket/rarity_weights_basis_points/artifact',
            37 => '/secretary/ticket_gacha/dokidoki_ticket/rarity_weights_basis_points/high_quality',
            38 => '/secretary/ticket_gacha/dokidoki_ticket/rarity_weights_basis_points/artifact',
        ],
        'flavor' => [
            0 => 'name',
            1 => 'display',
        ],
    ],
];
