<?php

return [
    'payload' => [
        'surface_ships' => [
            'capacity_per_type' => 3,
            'movement' => [
                'terrain_key' => 'sea',
                'required_port_facility_key' => 'port',
                'fuel_resource_key' => 'oil',
                'normal_event_limit_per_turn' => 1,
                'fuel_shortage_damage_chance_percent' => 1,
                'fuel_shortage_damage' => 1,
                'random_stream_version' => 1,
                'secretary_skill_key' => 'ship_operations',
                'secretary_experience_per_successful_move' => 1,
            ],
            'forced_displacement' => [
                'port_search_distances' => [
                    0 => 1,
                    1 => 2,
                ],
                'foreign_destroy_karma' => 1,
            ],
            'missile_impact' => [
                'damage_by_missile_key' => [
                    'missile' => 1,
                    'pp_missile' => 1,
                    'spp_missile' => 1,
                ],
                'instant_sink_missile_keys' => [
                    0 => 'land_destruction_missile',
                ],
                'foreign_sink_karma' => 1,
            ],
            'definitions' => [
                'fishing' => [
                    'name' => '漁船',
                    'asset_key' => 'ship.fishing',
                    'player_buildable' => true,
                    'build_selector' => 1,
                    'sort_order' => 10,
                    'build_cost_money' => 500,
                    'maximum_hp' => 1,
                    'movement_oil_units' => 1,
                    'movement_reward_resource_key' => 'fish',
                    'movement_reward_resource_units' => 7000,
                    'movement_reward_money' => 0,
                    'visibility_radius' => 1,
                    'movement_mode' => 'heading_or_random',
                    'combat_role' => 'none',
                ],
                'tourist' => [
                    'name' => '観光船',
                    'asset_key' => 'ship.tourist',
                    'player_buildable' => true,
                    'build_selector' => 2,
                    'sort_order' => 20,
                    'build_cost_money' => 1500,
                    'maximum_hp' => 2,
                    'movement_oil_units' => 2,
                    'movement_reward_resource_key' => null,
                    'movement_reward_resource_units' => 0,
                    'movement_reward_money' => 20,
                    'visibility_radius' => 1,
                    'movement_mode' => 'heading_or_random',
                    'combat_role' => 'none',
                ],
                'exploration' => [
                    'name' => '探索船',
                    'asset_key' => 'ship.exploration',
                    'player_buildable' => true,
                    'build_selector' => 3,
                    'sort_order' => 30,
                    'build_cost_money' => 1000,
                    'maximum_hp' => 2,
                    'movement_oil_units' => 1,
                    'movement_reward_resource_key' => null,
                    'movement_reward_resource_units' => 0,
                    'movement_reward_money' => 0,
                    'visibility_radius' => 3,
                    'movement_mode' => 'sparkle_or_random',
                    'combat_role' => 'none',
                ],
                'pirate' => [
                    'name' => '海賊船',
                    'asset_key' => 'ship.pirate',
                    'player_buildable' => false,
                    'build_selector' => null,
                    'sort_order' => 40,
                    'build_cost_money' => 0,
                    'maximum_hp' => 3,
                    'movement_oil_units' => 0,
                    'movement_reward_resource_key' => null,
                    'movement_reward_resource_units' => 0,
                    'movement_reward_money' => 0,
                    'visibility_radius' => 1,
                    'movement_mode' => 'random_drift',
                    'combat_role' => 'pirate',
                ],
                'treasure' => [
                    'name' => '宝船',
                    'asset_key' => 'ship.treasure',
                    'player_buildable' => false,
                    'build_selector' => null,
                    'sort_order' => 50,
                    'build_cost_money' => 0,
                    'maximum_hp' => 1,
                    'movement_oil_units' => 0,
                    'movement_reward_resource_key' => null,
                    'movement_reward_resource_units' => 0,
                    'movement_reward_money' => 0,
                    'visibility_radius' => 1,
                    'movement_mode' => 'random_drift',
                    'combat_role' => 'none',
                ],
                'warship' => [
                    'name' => '戦艦',
                    'asset_key' => 'ship.warship',
                    'player_buildable' => true,
                    'build_selector' => 4,
                    'sort_order' => 60,
                    'build_cost_money' => 3000,
                    'maximum_hp' => 3,
                    'movement_oil_units' => 3,
                    'movement_reward_resource_key' => null,
                    'movement_reward_resource_units' => 0,
                    'movement_reward_money' => 0,
                    'visibility_radius' => 5,
                    'movement_mode' => 'heading_only',
                    'combat_role' => 'warship',
                ],
            ],
        ],
    ],
    'classification' => [
        'behavior' => [
            0 => 'asset_key',
            1 => 'build_selector',
            2 => 'fuel_resource_key',
            3 => 'movement_reward_resource_key',
            4 => 'required_port_facility_key',
            5 => 'secretary_skill_key',
            6 => 'terrain_key',
            7 => '/surface_ships/forced_displacement/port_search_distances/*',
            8 => '/surface_ships/missile_impact/instant_sink_missile_keys/*',
            9 => 'player_buildable',
            10 => 'movement_mode',
            11 => 'combat_role',
        ],
        'data' => [
            0 => 'build_cost_money',
            1 => 'capacity_per_type',
            2 => 'maximum_hp',
            3 => 'movement_oil_units',
            4 => 'movement_reward_money',
            5 => 'movement_reward_resource_units',
            6 => 'normal_event_limit_per_turn',
            7 => 'fuel_shortage_damage',
            8 => 'fuel_shortage_damage_chance_percent',
            9 => 'foreign_destroy_karma',
            10 => '/surface_ships/missile_impact/damage_by_missile_key/missile',
            11 => '/surface_ships/missile_impact/damage_by_missile_key/pp_missile',
            12 => '/surface_ships/missile_impact/damage_by_missile_key/spp_missile',
            13 => '/surface_ships/missile_impact/foreign_sink_karma',
            14 => 'random_stream_version',
            15 => 'secretary_experience_per_successful_move',
            16 => 'sort_order',
            17 => 'visibility_radius',
        ],
        'flavor' => [
            0 => 'name',
        ],
    ],
];
