<?php

return [
    'key' => 'hakoniwa-2s-plus-v13',
    'version' => 13,
    'chunk_size' => 16,
    'initial_x_min' => 0,
    'initial_x_max' => 59,
    'initial_y_min' => 0,
    'initial_y_max' => 59,
    'minimum_capital_distance' => 12,
    'capital_initial_population' => 1000,
    'capital_minimum_population' => 100,
    'initial_money' => 100,
    'nation_lifecycle' => [
        'states' => ['active', 'dormant', 'recovery', 'abandoned'],
        'runtime_entry_states' => ['active', 'dormant', 'recovery', 'abandoned'],
        'recovery_entry_enabled' => true,
        'recovery_duration_turns' => 84,
        'dormant_reasons' => ['idle', 'collapse', 'manual'],
        'initial_idle_counter' => 2000,
        'dormant_idle_threshold' => 360,
        'abandonment_idle_threshold' => 2160,
        'turns_per_day' => 12,
        'manual_dormancy_min_days' => 1,
        'manual_dormancy_max_days' => 7,
        'dormant_finance_money' => 10,
        'dormant_protection_radius' => 2,
        'dormant_visual_theme' => 'snow',
        'territory_influence_target_states' => ['active', 'dormant'],
        'territory_influence_source_states' => ['active'],
        'initial_food_resource_key' => 'wheat',
        'finance_command_key' => 'finance',
        'emergency_farm' => [
            'facility_key' => 'farm',
            'result_terrain_key' => 'plain',
            'candidate_terrain_keys' => ['plain', 'wasteland', 'scorched', 'shallow', 'sea'],
            'selection' => ['distance', 'y', 'x'],
        ],
    ],
    'karma' => [
        'minimum' => -10,
        'ordinary' => 0,
        'maximum' => 100,
        'impact_points' => [
            'terrain' => 1,
            'settlement_or_facility' => 2,
            'capital_above_minimum' => 2,
            'capital_at_minimum' => 0,
            'seabed_oil_field_destroyed' => 10,
            'land_destroyed' => 10,
            'seabed_base_destroyed' => 3,
        ],
        'anti_monster_missile_keys' => ['missile', 'pp_missile', 'spp_missile'],
        'spp_self_destruct_setup_points' => 20,
        'hostile_monument_points' => 15,
        'foreign_monster_kill_reduction' => 1,
        'victim_reduction_per_impact' => 1,
        'decay_interval_turns' => 6,
        'decay_amount' => 1,
        'recovery_entry_reduction' => 3,
        'alliance_reward_money_per_karma_per_impact' => 1,
        'sanction' => [
            'overflow_points_per_shot' => 1,
            'target_selection' => 'owned_surface_territory_with_replacement',
            'interception' => ['defense', 'secretary'],
            'impact' => 'canonical_scorch_or_destruction',
            'random_stream_version' => 1,
        ],
    ],
    'resource_definitions' => [
        0 => [
            'key' => 'wheat',
            'name' => '小麦',
            'category' => 'food',
            'unit' => 'ton',
            'nutrition_per_unit' => 1,
            'storable' => true,
            'tradable' => true,
            'sale_price_key' => 'sale.wheat',
            'sort_order' => 10,
            'metadata' => [
                'produced_by' => 'farm',
            ],
            'unit_label' => 'トン',
        ],
        1 => [
            'key' => 'fish',
            'name' => '魚',
            'category' => 'food',
            'unit' => 'ton',
            'nutrition_per_unit' => 1,
            'storable' => true,
            'tradable' => true,
            'sale_price_key' => 'sale.fish',
            'sort_order' => 20,
            'metadata' => [
            ],
            'unit_label' => 'トン',
        ],
        2 => [
            'key' => 'monster_meat',
            'name' => '怪獣肉',
            'category' => 'food',
            'unit' => 'ton',
            'nutrition_per_unit' => 2,
            'storable' => true,
            'tradable' => true,
            'sale_price_key' => 'sale.monster_meat',
            'sort_order' => 30,
            'metadata' => [
                'nutrition_is_provisional' => true,
            ],
            'unit_label' => 'トン',
        ],
        3 => [
            'key' => 'industrial_goods',
            'name' => '工業品',
            'category' => 'industry',
            'unit' => 'unit',
            'nutrition_per_unit' => null,
            'storable' => true,
            'tradable' => true,
            'sale_price_key' => 'sale.industrial_goods',
            'sort_order' => 40,
            'metadata' => [
                'produced_by' => 'factory',
            ],
            'unit_label' => 'ユニット',
        ],
        4 => [
            'key' => 'minerals',
            'name' => '鉱物',
            'category' => 'material',
            'unit' => 'ton',
            'nutrition_per_unit' => null,
            'storable' => true,
            'tradable' => true,
            'sale_price_key' => 'sale.minerals',
            'sort_order' => 50,
            'metadata' => [
                'produced_by' => 'mine',
            ],
            'unit_label' => 'トン',
        ],
    ],
    'resource_sale_prices' => [
        'sale.wheat' => 1,
        'sale.fish' => 1,
        'sale.monster_meat' => 2,
        'sale.industrial_goods' => 1,
        'sale.minerals' => 1,
    ],
    'initial_resources' => [
        'wheat' => 10000,
        'fish' => 0,
        'monster_meat' => 0,
        'industrial_goods' => 0,
        'minerals' => 0,
    ],
    'default_sale_policy' => 'stockpile',
    'command_queue_limit' => 30,
    'terrain_quantities' => [
        'forest' => [
            'key' => 'trees',
            'label' => '木',
            'unit' => '本',
            'initial_quantity' => 500,
            'minimum_quantity' => 0,
            'maximum_quantity' => 20000,
            'growth_increment' => 100,
            'growth_rule_key' => 'legacy.forest.grow_each_turn',
        ],
    ],
    'facility_definitions' => [
        'village' => [
            'name' => '村',
            'asset_key' => 'tile.village',
            'visibility_policy' => 'public',
            'build_command_key' => null,
            'scale_unit_people' => null,
            'initial_scale' => null,
            'scale_increment' => null,
            'maximum_scale' => null,
            'workforce_per_scale_people' => null,
            'production_definition_key' => null,
            'buildable_terrain_keys' => [
            ],
        ],
        'capital' => [
            'name' => '首都',
            'asset_key' => 'tile.capital',
            'visibility_policy' => 'public',
            'build_command_key' => null,
            'scale_unit_people' => null,
            'initial_scale' => null,
            'scale_increment' => null,
            'maximum_scale' => null,
            'workforce_per_scale_people' => null,
            'production_definition_key' => null,
            'buildable_terrain_keys' => [
            ],
        ],
        'farm' => [
            'name' => '農場',
            'asset_key' => 'tile.farm',
            'visibility_policy' => 'public',
            'build_command_key' => 'build_farm',
            'scale_unit_people' => 1000,
            'initial_scale' => 10,
            'scale_increment' => 2,
            'maximum_scale' => 50,
            'workforce_per_scale_people' => 1000,
            'production_definition_key' => 'farm_wheat',
            'buildable_terrain_keys' => [
                0 => 'plain',
            ],
        ],
        'factory' => [
            'name' => '工場',
            'asset_key' => 'tile.factory',
            'visibility_policy' => 'public',
            'build_command_key' => 'build_factory',
            'scale_unit_people' => 1000,
            'initial_scale' => 30,
            'scale_increment' => 10,
            'maximum_scale' => 100,
            'workforce_per_scale_people' => 1000,
            'production_definition_key' => 'factory_industrial_goods',
            'buildable_terrain_keys' => [
                0 => 'plain',
            ],
        ],
        'mine' => [
            'name' => '採掘場',
            'asset_key' => 'tile.mine',
            'visibility_policy' => 'public',
            'build_command_key' => 'build_mine',
            'scale_unit_people' => 1000,
            'initial_scale' => 5,
            'scale_increment' => 5,
            'maximum_scale' => 200,
            'workforce_per_scale_people' => 1000,
            'production_definition_key' => 'mine_minerals',
            'buildable_terrain_keys' => [
                0 => 'mountain',
            ],
        ],
        'missile_base' => [
            'name' => 'ミサイル基地',
            'asset_key' => 'tile.missile_base',
            'visibility_policy' => 'disguised',
            'disguise_terrain_key' => 'forest',
            'disguise_asset_key' => 'tile.forest',
            'build_command_key' => 'build_missile_base',
            'scale_unit_people' => null,
            'initial_scale' => null,
            'scale_increment' => null,
            'maximum_scale' => null,
            'workforce_per_scale_people' => null,
            'production_definition_key' => null,
            'buildable_terrain_keys' => [
                0 => 'plain',
            ],
            'initial_experience' => 0,
            'maximum_experience' => 200,
            'level_thresholds' => [
                0 => 20,
                1 => 60,
                2 => 120,
                3 => 200,
            ],
            'launch_capacity_by_level' => [
                1 => 1,
                2 => 2,
                3 => 3,
                4 => 4,
                5 => 5,
            ],
        ],
        'town' => [
            'name' => '町',
            'asset_key' => 'tile.town',
            'visibility_policy' => 'public',
            'build_command_key' => null,
            'scale_unit_people' => null,
            'initial_scale' => null,
            'scale_increment' => null,
            'maximum_scale' => null,
            'workforce_per_scale_people' => null,
            'production_definition_key' => null,
            'buildable_terrain_keys' => [
            ],
        ],
        'city' => [
            'name' => '都市',
            'asset_key' => 'tile.city',
            'visibility_policy' => 'public',
            'build_command_key' => null,
            'scale_unit_people' => null,
            'initial_scale' => null,
            'scale_increment' => null,
            'maximum_scale' => null,
            'workforce_per_scale_people' => null,
            'production_definition_key' => null,
            'buildable_terrain_keys' => [
            ],
        ],
        'seabed_oil_field' => [
            'name' => '海底油田',
            'asset_key' => 'tile.seabed_oil_field',
            'visibility_policy' => 'public',
            'build_command_key' => 'excavate',
            'scale_unit_people' => null,
            'initial_scale' => null,
            'scale_increment' => null,
            'maximum_scale' => null,
            'workforce_per_scale_people' => null,
            'production_definition_key' => null,
            'buildable_terrain_keys' => [
                0 => 'sea',
            ],
        ],
        'defense' => [
            'disguise_ownership_policy' => null,
            'scale_unit_people' => null,
            'initial_scale' => null,
            'scale_increment' => null,
            'maximum_scale' => null,
            'workforce_per_scale_people' => null,
            'production_definition_key' => null,
            'name' => '防衛施設',
            'asset_key' => 'tile.defense',
            'visibility_policy' => 'public',
            'build_command_key' => 'build_defense_facility',
            'buildable_terrain_keys' => [
                0 => 'plain',
            ],
        ],
        'seabed_base' => [
            'disguise_ownership_policy' => 'neutral',
            'scale_unit_people' => null,
            'initial_scale' => null,
            'scale_increment' => null,
            'maximum_scale' => null,
            'workforce_per_scale_people' => null,
            'production_definition_key' => null,
            'name' => '海底基地',
            'asset_key' => 'tile.seabed_base',
            'visibility_policy' => 'disguised',
            'disguise_terrain_key' => 'sea',
            'disguise_asset_key' => 'tile.sea',
            'build_command_key' => 'build_seabed_base',
            'buildable_terrain_keys' => [
                0 => 'sea',
            ],
            'initial_experience' => 0,
            'maximum_experience' => 200,
            'level_thresholds' => [
                0 => 50,
                1 => 200,
            ],
            'launch_capacity_by_level' => [
                1 => 1,
                2 => 2,
                3 => 3,
            ],
        ],
        'monument' => [
            'disguise_ownership_policy' => null,
            'scale_unit_people' => null,
            'initial_scale' => null,
            'scale_increment' => null,
            'maximum_scale' => null,
            'workforce_per_scale_people' => null,
            'production_definition_key' => null,
            'name' => '記念碑',
            'asset_key' => 'tile.monument',
            'visibility_policy' => 'public',
            'build_command_key' => 'build_monument',
            'buildable_terrain_keys' => [
                0 => 'plain',
            ],
        ],
        'decoy' => [
            'disguise_ownership_policy' => null,
            'scale_unit_people' => null,
            'initial_scale' => null,
            'scale_increment' => null,
            'maximum_scale' => null,
            'workforce_per_scale_people' => null,
            'production_definition_key' => null,
            'name' => 'ハリボテ',
            'asset_key' => 'tile.decoy',
            'visibility_policy' => 'public',
            'build_command_key' => 'build_decoy',
            'buildable_terrain_keys' => [
                0 => 'plain',
            ],
            'display_as_facility_key' => 'defense',
        ],
    ],
    'command_definitions' => [
        0 => [
            'key' => 'land_clear',
            'name' => '整地',
            'description' => '所有する陸地を平地にします。',
            'target_type' => 'cell',
            'target_terrain_keys' => [
                0 => 'wasteland',
                1 => 'plain',
                2 => 'forest',
                3 => 'scorched',
            ],
            'target_facility_keys' => [
            ],
            'requires_empty_facility' => false,
            'cost_money' => 5,
            'required_resources' => [
            ],
            'execution_phase' => 'terrain',
            'result_terrain_key' => 'plain',
            'result_facility_key' => null,
            'sort_order' => 10,
            'metadata' => [
                'legacy_command' => 'Prepare',
                'consumes_turn' => true,
                'execution_deferred' => false,
            ],
        ],
        1 => [
            'key' => 'land_level',
            'name' => '地ならし',
            'description' => '所有する陸地を、ターンを消費せず平地にします。ごくまれに地震が発生することがあります。',
            'target_type' => 'cell',
            'target_terrain_keys' => [
                0 => 'wasteland',
                1 => 'plain',
                2 => 'forest',
                3 => 'scorched',
            ],
            'target_facility_keys' => [
            ],
            'requires_empty_facility' => false,
            'cost_money' => 100,
            'required_resources' => [
            ],
            'execution_phase' => 'terrain',
            'result_terrain_key' => 'plain',
            'result_facility_key' => null,
            'sort_order' => 20,
            'metadata' => [
                'legacy_command' => 'Prepare2',
                'consumes_turn' => false,
                'execution_deferred' => false,
            ],
        ],
        2 => [
            'key' => 'reclaim',
            'name' => '埋め立て',
            'description' => '海を中立の浅瀬へ、浅瀬を自国の荒地へ変更します。浅瀬の埋め立てでは周囲の水域も浅瀬化する場合があります。',
            'target_type' => 'cell',
            'target_terrain_keys' => [
                0 => 'sea',
                1 => 'shallow',
            ],
            'target_facility_keys' => [
            ],
            'requires_empty_facility' => true,
            'cost_money' => 150,
            'required_resources' => [
            ],
            'execution_phase' => 'terrain',
            'result_terrain_key' => null,
            'result_facility_key' => null,
            'sort_order' => 30,
            'metadata' => [
                'legacy_command' => 'Reclaim',
                'result_depends_on_target' => true,
                'execution_deferred' => false,
                'adjacent_water_spread_maximum' => 3,
            ],
        ],
        3 => [
            'key' => 'excavate',
            'name' => '掘削',
            'description' => '陸地を浅瀬へ、浅瀬を海へ、山を荒地へ変更します。海では数量に応じて海底油田を探索します。',
            'target_type' => 'cell',
            'target_terrain_keys' => [
                0 => 'sea',
                1 => 'shallow',
                2 => 'wasteland',
                3 => 'plain',
                4 => 'forest',
                5 => 'mountain',
                6 => 'scorched',
            ],
            'target_facility_keys' => [
            ],
            'requires_empty_facility' => false,
            'cost_money' => 200,
            'required_resources' => [
            ],
            'execution_phase' => 'terrain',
            'result_terrain_key' => null,
            'result_facility_key' => null,
            'sort_order' => 40,
            'metadata' => [
                'legacy_command' => 'Destroy',
                'result_depends_on_target' => true,
                'execution_deferred' => false,
                'oil_search_effect_key' => 'seabed_oil_search',
            ],
        ],
        4 => [
            'key' => 'build_farm',
            'name' => '農場建設',
            'description' => '平地へ農場を建設します。',
            'target_type' => 'cell',
            'target_terrain_keys' => [
                0 => 'plain',
            ],
            'target_facility_keys' => [
            ],
            'requires_empty_facility' => true,
            'cost_money' => 20,
            'required_resources' => [
            ],
            'execution_phase' => 'facility',
            'result_terrain_key' => 'plain',
            'result_facility_key' => 'farm',
            'sort_order' => 50,
            'metadata' => [
                'legacy_command' => 'Farm',
                'initial_scale_from_facility_definition' => true,
                'future_expand_command' => 'expand_farm',
                'execution_deferred' => false,
            ],
        ],
        5 => [
            'key' => 'build_factory',
            'name' => '工場建設',
            'description' => '平地へ工場を建設します。',
            'target_type' => 'cell',
            'target_terrain_keys' => [
                0 => 'plain',
            ],
            'target_facility_keys' => [
            ],
            'requires_empty_facility' => true,
            'cost_money' => 100,
            'required_resources' => [
            ],
            'execution_phase' => 'facility',
            'result_terrain_key' => 'plain',
            'result_facility_key' => 'factory',
            'sort_order' => 60,
            'metadata' => [
                'legacy_command' => 'Factory',
                'initial_scale_from_facility_definition' => true,
                'future_expand_command' => 'expand_factory',
                'execution_deferred' => false,
            ],
        ],
        6 => [
            'key' => 'build_mine',
            'name' => '採掘場建設',
            'description' => '山へ採掘場を建設します。',
            'target_type' => 'cell',
            'target_terrain_keys' => [
                0 => 'mountain',
            ],
            'target_facility_keys' => [
            ],
            'requires_empty_facility' => true,
            'cost_money' => 300,
            'required_resources' => [
            ],
            'execution_phase' => 'facility',
            'result_terrain_key' => 'mountain',
            'result_facility_key' => 'mine',
            'sort_order' => 70,
            'metadata' => [
                'legacy_command' => 'Mountain',
                'initial_scale_from_facility_definition' => true,
                'future_expand_command' => 'expand_mine',
                'execution_deferred' => false,
            ],
        ],
        7 => [
            'key' => 'logging',
            'name' => '伐採',
            'description' => '所有する森を伐採し、木の価値を資金として受け取ります。',
            'target_type' => 'cell',
            'target_terrain_keys' => [
                0 => 'forest',
            ],
            'target_facility_keys' => [
            ],
            'requires_empty_facility' => false,
            'cost_money' => 0,
            'required_resources' => [
            ],
            'execution_phase' => 'terrain',
            'result_terrain_key' => 'plain',
            'result_facility_key' => null,
            'sort_order' => 80,
            'metadata' => [
                'consumes_turn' => true,
                'parameters' => [
                ],
                'legacy_command' => 'SellTree',
                'money_per_legacy_tree_unit' => 5,
                'private_coordinate' => true,
            ],
        ],
        8 => [
            'key' => 'territory_expand',
            'name' => '領土拡張',
            'description' => '自国領に隣接する中立陸地、または他国の荒地・焼け野原を領有します。休止中の首都周辺は保護されます。',
            'target_type' => 'cell',
            'target_terrain_keys' => [
                0 => 'wasteland',
                1 => 'scorched',
                2 => 'plain',
                3 => 'forest',
                4 => 'mountain',
            ],
            'target_facility_keys' => [
            ],
            'requires_empty_facility' => true,
            'cost_money' => 100,
            'required_resources' => [
            ],
            'execution_phase' => 'territory',
            'result_terrain_key' => null,
            'result_facility_key' => null,
            'sort_order' => 90,
            'metadata' => [
                'consumes_turn' => true,
                'parameters' => [
                ],
                'legacy_command' => 'Widen',
                'policy_version' => 3,
                'actor_states' => [
                    0 => 'active',
                ],
                'adjacency' => [
                    'source_owner' => 'actor',
                    'directions' => 6,
                ],
                'neutral_target' => [
                    'allowed' => true,
                    'terrain_keys' => [
                        0 => 'wasteland',
                        1 => 'scorched',
                        2 => 'plain',
                        3 => 'forest',
                        4 => 'mountain',
                    ],
                    'requires_empty_facility' => true,
                ],
                'foreign_target' => [
                    'owner_states' => [
                        0 => 'active',
                        1 => 'dormant',
                    ],
                    'terrain_keys' => [
                        0 => 'wasteland',
                        1 => 'scorched',
                    ],
                    'requires_empty_facility' => true,
                ],
                'monster_occupancy' => 'reject',
                'capital_core' => 'reject',
                'effect' => [
                    'owner' => 'actor',
                    'terrain' => 'preserve',
                    'population' => 'preserve',
                    'facility' => 'preserve',
                    'facility_scale' => 'preserve',
                    'resource_and_state' => 'preserve',
                ],
            ],
        ],
        9 => [
            'key' => 'plant_forest',
            'name' => '植林',
            'description' => '所有する平地へ森を植えます。',
            'target_type' => 'cell',
            'target_terrain_keys' => [
                0 => 'plain',
            ],
            'target_facility_keys' => [
            ],
            'requires_empty_facility' => true,
            'cost_money' => 50,
            'required_resources' => [
            ],
            'execution_phase' => 'facility',
            'result_terrain_key' => 'forest',
            'result_facility_key' => null,
            'sort_order' => 100,
            'metadata' => [
                'consumes_turn' => true,
                'parameters' => [
                ],
                'legacy_command' => 'Plant',
                'private_coordinate' => true,
            ],
        ],
        10 => [
            'key' => 'build_missile_base',
            'name' => 'ミサイル基地建設',
            'description' => '所有する平地へ秘密のミサイル基地を建設します。',
            'target_type' => 'cell',
            'target_terrain_keys' => [
                0 => 'plain',
            ],
            'target_facility_keys' => [
            ],
            'requires_empty_facility' => true,
            'cost_money' => 300,
            'required_resources' => [
            ],
            'execution_phase' => 'facility',
            'result_terrain_key' => 'plain',
            'result_facility_key' => 'missile_base',
            'sort_order' => 110,
            'metadata' => [
                'consumes_turn' => true,
                'parameters' => [
                ],
                'legacy_command' => 'Base',
                'private_coordinate' => true,
            ],
        ],
        11 => [
            'key' => 'build_defense_facility',
            'name' => '防衛施設建設',
            'description' => '所有する平地へ防衛施設を建設します。',
            'target_type' => 'cell',
            'target_terrain_keys' => [
                0 => 'plain',
            ],
            'target_facility_keys' => [
            ],
            'requires_empty_facility' => true,
            'cost_money' => 800,
            'required_resources' => [
            ],
            'execution_phase' => 'facility',
            'result_terrain_key' => 'plain',
            'result_facility_key' => 'defense',
            'sort_order' => 120,
            'metadata' => [
                'consumes_turn' => true,
                'parameters' => [
                ],
                'legacy_command' => 'DBase',
                'owner_overbuild_effect' => 'defense_self_destruct',
            ],
        ],
        12 => [
            'key' => 'build_seabed_base',
            'name' => '海底基地建設',
            'description' => '自国領から3hex以内の海へ秘密の海底基地を建設します。',
            'target_type' => 'cell',
            'target_terrain_keys' => [
                0 => 'sea',
            ],
            'target_facility_keys' => [
            ],
            'requires_empty_facility' => true,
            'cost_money' => 8000,
            'required_resources' => [
            ],
            'execution_phase' => 'facility',
            'result_terrain_key' => 'sea',
            'result_facility_key' => 'seabed_base',
            'sort_order' => 130,
            'metadata' => [
                'consumes_turn' => true,
                'parameters' => [
                ],
                'legacy_command' => 'SBase',
                'owned_within_radius' => 3,
                'private_coordinate' => true,
            ],
        ],
        13 => [
            'key' => 'build_monument',
            'name' => '記念碑建設',
            'description' => '所有する平地へ選択した種類の記念碑を建設します。quantityは記念碑種類です。',
            'target_type' => 'cell',
            'target_terrain_keys' => [
                0 => 'plain',
            ],
            'target_facility_keys' => [
            ],
            'requires_empty_facility' => true,
            'cost_money' => 9999,
            'required_resources' => [
            ],
            'execution_phase' => 'facility',
            'result_terrain_key' => 'plain',
            'result_facility_key' => 'monument',
            'sort_order' => 140,
            'metadata' => [
                'consumes_turn' => true,
                'parameters' => [
                    'target_nation_id' => [
                        'label' => '対象Nation ID',
                        'type' => 'integer',
                        'minimum' => 1,
                        'maximum' => 2147483647,
                        'required' => false,
                        'nullable' => true,
                    ],
                ],
                'legacy_command' => 'Monument',
                'quantity_selects_catalog' => 'monument_definitions',
                'owner_overbuild_effect' => 'monument_flight',
            ],
        ],
        14 => [
            'key' => 'build_decoy',
            'name' => '防衛施設建設',
            'description' => '所有する平地へ防衛施設に見えるハリボテを建設します。',
            'target_type' => 'cell',
            'target_terrain_keys' => [
                0 => 'plain',
            ],
            'target_facility_keys' => [
            ],
            'requires_empty_facility' => true,
            'cost_money' => 1,
            'required_resources' => [
            ],
            'execution_phase' => 'facility',
            'result_terrain_key' => 'plain',
            'result_facility_key' => 'decoy',
            'sort_order' => 150,
            'metadata' => [
                'consumes_turn' => true,
                'parameters' => [
                ],
                'legacy_command' => 'Haribote',
                'private_actual_facility' => true,
            ],
        ],
        15 => [
            'key' => 'missile',
            'name' => 'ミサイル発射',
            'description' => '指定座標へミサイルを発射します。数量で発射本数を設定します。誤差範囲は周囲2マスです。PPミサイルと同じターンに使用できます。',
            'target_type' => 'cell',
            'target_terrain_keys' => [
                0 => 'sea',
                1 => 'shallow',
                2 => 'wasteland',
                3 => 'scorched',
                4 => 'plain',
                5 => 'forest',
                6 => 'mountain',
            ],
            'target_facility_keys' => [
            ],
            'requires_empty_facility' => false,
            'cost_money' => 20,
            'required_resources' => [
            ],
            'execution_phase' => 'military',
            'result_terrain_key' => null,
            'result_facility_key' => null,
            'sort_order' => 160,
            'metadata' => [
                'consumes_turn' => true,
                'parameters' => [
                ],
                'per_shot_cost' => true,
                'deviation_radius' => 2,
                'terrain_destruction' => false,
                'single_command_per_turn' => false,
                'requires_owned_launch_base' => true,
            ],
        ],
        16 => [
            'key' => 'pp_missile',
            'name' => 'PPミサイル発射',
            'description' => '指定座標へPPミサイルを発射します。数量で発射本数を設定します。誤差範囲は周囲1マスです。通常のミサイルと同じターンに使用できます。',
            'target_type' => 'cell',
            'target_terrain_keys' => [
                0 => 'sea',
                1 => 'shallow',
                2 => 'wasteland',
                3 => 'scorched',
                4 => 'plain',
                5 => 'forest',
                6 => 'mountain',
            ],
            'target_facility_keys' => [
            ],
            'requires_empty_facility' => false,
            'cost_money' => 50,
            'required_resources' => [
            ],
            'execution_phase' => 'military',
            'result_terrain_key' => null,
            'result_facility_key' => null,
            'sort_order' => 170,
            'metadata' => [
                'consumes_turn' => true,
                'parameters' => [
                ],
                'per_shot_cost' => true,
                'deviation_radius' => 1,
                'terrain_destruction' => false,
                'single_command_per_turn' => false,
                'requires_owned_launch_base' => true,
            ],
        ],
        17 => [
            'key' => 'land_destruction_missile',
            'name' => '陸地破壊弾発射',
            'description' => '指定座標へ大地をえぐる陸地破壊弾を発射します。数量で発射本数を設定します。誤差範囲は周囲2マスです。他のミサイルとは同じターンに使用できません。',
            'target_type' => 'cell',
            'target_terrain_keys' => [
                0 => 'sea',
                1 => 'shallow',
                2 => 'wasteland',
                3 => 'scorched',
                4 => 'plain',
                5 => 'forest',
                6 => 'mountain',
            ],
            'target_facility_keys' => [
            ],
            'requires_empty_facility' => false,
            'cost_money' => 100,
            'required_resources' => [
            ],
            'execution_phase' => 'military',
            'result_terrain_key' => null,
            'result_facility_key' => null,
            'sort_order' => 180,
            'metadata' => [
                'consumes_turn' => true,
                'parameters' => [
                ],
                'per_shot_cost' => true,
                'deviation_radius' => 2,
                'terrain_destruction' => true,
                'single_command_per_turn' => true,
                'requires_owned_launch_base' => true,
            ],
        ],
        18 => [
            'key' => 'spp_missile',
            'name' => 'SPPミサイル発射',
            'description' => '指定座標へSPPミサイルを発射します。数量で発射本数を設定します。着弾地点に誤差はありません。他のミサイルとは同じターンに使用できません。',
            'target_type' => 'cell',
            'target_terrain_keys' => [
                0 => 'sea',
                1 => 'shallow',
                2 => 'wasteland',
                3 => 'scorched',
                4 => 'plain',
                5 => 'forest',
                6 => 'mountain',
            ],
            'target_facility_keys' => [
            ],
            'requires_empty_facility' => false,
            'cost_money' => 500,
            'required_resources' => [
            ],
            'execution_phase' => 'military',
            'result_terrain_key' => null,
            'result_facility_key' => null,
            'sort_order' => 190,
            'metadata' => [
                'consumes_turn' => true,
                'parameters' => [
                ],
                'per_shot_cost' => true,
                'deviation_radius' => 0,
                'terrain_destruction' => false,
                'single_command_per_turn' => true,
                'requires_owned_launch_base' => true,
            ],
        ],
        19 => [
            'key' => 'monster_dispatch',
            'name' => '怪獣派遣',
            'description' => '対象の国にメカいのらを派遣します。',
            'target_type' => 'nation',
            'target_terrain_keys' => [
                0 => 'sea',
                1 => 'shallow',
                2 => 'wasteland',
                3 => 'scorched',
                4 => 'plain',
                5 => 'forest',
                6 => 'mountain',
            ],
            'target_facility_keys' => [
            ],
            'requires_empty_facility' => false,
            'cost_money' => 3000,
            'required_resources' => [
            ],
            'execution_phase' => 'military',
            'result_terrain_key' => null,
            'result_facility_key' => null,
            'sort_order' => 200,
            'metadata' => [
                'parameters' => [
                    'target_nation_id' => [
                        'label' => '対象Nation ID',
                        'type' => 'integer',
                        'minimum' => 1,
                        'maximum' => 2147483647,
                        'required' => true,
                    ],
                ],
                'private_command' => true,
                'quantity_selects_catalog' => 'monster_dispatch_options',
                'default_selector_value' => 1,
                'monster_dispatch_options' => [
                    0 => [
                        'value' => 1,
                        'monster_key' => 'mecha_inora',
                        'label' => 'メカいのら',
                        'cost_money' => 3000,
                        'enabled' => true,
                    ],
                    1 => [
                        'value' => 2,
                        'monster_key' => 'mecha_inora_zero',
                        'label' => 'メカいのら零式',
                        'cost_money' => 9999,
                        'enabled' => true,
                    ],
                ],
            ],
        ],
        20 => [
            'key' => 'finance',
            'name' => '資金繰り',
            'description' => '何もせず、資金繰りを行います。',
            'target_type' => 'nation',
            'target_terrain_keys' => [
                0 => 'sea',
                1 => 'shallow',
                2 => 'wasteland',
                3 => 'scorched',
                4 => 'plain',
                5 => 'forest',
                6 => 'mountain',
            ],
            'target_facility_keys' => [
            ],
            'requires_empty_facility' => false,
            'cost_money' => 0,
            'required_resources' => [
            ],
            'execution_phase' => 'operations',
            'result_terrain_key' => null,
            'result_facility_key' => null,
            'sort_order' => 210,
            'metadata' => [
                'consumes_turn' => true,
                'parameters' => [
                ],
            ],
        ],
        21 => [
            'key' => 'money_aid',
            'name' => '資金援助',
            'description' => '対象の国に、数量×100億円の資金を援助します。',
            'target_type' => 'nation',
            'target_terrain_keys' => [
                0 => 'sea',
                1 => 'shallow',
                2 => 'wasteland',
                3 => 'scorched',
                4 => 'plain',
                5 => 'forest',
                6 => 'mountain',
            ],
            'target_facility_keys' => [
            ],
            'requires_empty_facility' => false,
            'cost_money' => 0,
            'required_resources' => [
            ],
            'execution_phase' => 'operations',
            'result_terrain_key' => null,
            'result_facility_key' => null,
            'sort_order' => 220,
            'metadata' => [
                'consumes_turn' => false,
                'parameters' => [
                    'target_nation_id' => [
                        'label' => '対象Nation ID',
                        'type' => 'integer',
                        'minimum' => 1,
                        'maximum' => 2147483647,
                        'required' => true,
                    ],
                ],
                'transfer_money_per_quantity' => 100,
            ],
        ],
        22 => [
            'key' => 'food_aid',
            'name' => '食料援助',
            'description' => '対象の国に、数量×1,000トンの食料を援助します。',
            'target_type' => 'nation',
            'target_terrain_keys' => [
                0 => 'sea',
                1 => 'shallow',
                2 => 'wasteland',
                3 => 'scorched',
                4 => 'plain',
                5 => 'forest',
                6 => 'mountain',
            ],
            'target_facility_keys' => [
            ],
            'requires_empty_facility' => false,
            'cost_money' => 0,
            'required_resources' => [
            ],
            'execution_phase' => 'operations',
            'result_terrain_key' => null,
            'result_facility_key' => null,
            'sort_order' => 230,
            'metadata' => [
                'consumes_turn' => false,
                'parameters' => [
                    'target_nation_id' => [
                        'label' => '対象Nation ID',
                        'type' => 'integer',
                        'minimum' => 1,
                        'maximum' => 2147483647,
                        'required' => true,
                    ],
                ],
                'transfer_food_tons_per_quantity' => 1000,
            ],
        ],
        23 => [
            'key' => 'attraction',
            'name' => '誘致活動',
            'description' => '誘致活動を行ったターンは、人口が増加しやすくなります。',
            'target_type' => 'nation',
            'target_terrain_keys' => [
                0 => 'sea',
                1 => 'shallow',
                2 => 'wasteland',
                3 => 'scorched',
                4 => 'plain',
                5 => 'forest',
                6 => 'mountain',
            ],
            'target_facility_keys' => [
            ],
            'requires_empty_facility' => false,
            'cost_money' => 1000,
            'required_resources' => [
            ],
            'execution_phase' => 'operations',
            'result_terrain_key' => null,
            'result_facility_key' => null,
            'sort_order' => 240,
            'metadata' => [
                'consumes_turn' => true,
                'parameters' => [
                ],
                'legacy_command' => 'Propaganda',
            ],
        ],
        24 => [
            'key' => 'relocate_capital',
            'name' => '首都遷都',
            'description' => '指定した自国の都市を新しい首都にします。',
            'target_type' => 'cell',
            'target_terrain_keys' => [
                0 => 'plain',
            ],
            'target_facility_keys' => [
                0 => 'city',
            ],
            'requires_empty_facility' => false,
            'cost_money' => 1000,
            'required_resources' => [
            ],
            'execution_phase' => 'operations',
            'result_terrain_key' => 'plain',
            'result_facility_key' => 'capital',
            'sort_order' => 250,
            'metadata' => [
                'consumes_turn' => true,
                'parameters' => [
                ],
                'fixed_cost_setting' => 'capital_relocation_cost_money',
            ],
        ],
    ],
    'production_definitions' => [
        0 => [
            'key' => 'farm_wheat',
            'facility_key' => 'farm',
            'output_resource_key' => 'wheat',
            'production_per_scale' => 1000,
            'required_workforce_per_scale' => 1000,
            'operating_condition' => 'turn_start_workforce_allocation',
            'price_reference' => 'sale.wheat',
            'metadata' => [
                'production_per_worker' => 1,
                'canonical_unit' => 'ton',
            ],
        ],
        1 => [
            'key' => 'factory_industrial_goods',
            'facility_key' => 'factory',
            'output_resource_key' => 'industrial_goods',
            'production_per_scale' => 1000,
            'required_workforce_per_scale' => 1000,
            'operating_condition' => 'turn_start_workforce_allocation',
            'price_reference' => 'sale.industrial_goods',
            'metadata' => [
                'production_per_worker' => 1,
            ],
        ],
        2 => [
            'key' => 'mine_minerals',
            'facility_key' => 'mine',
            'output_resource_key' => 'minerals',
            'production_per_scale' => 1000,
            'required_workforce_per_scale' => 1000,
            'operating_condition' => 'turn_start_workforce_allocation',
            'price_reference' => 'sale.minerals',
            'metadata' => [
                'production_per_worker' => 1,
            ],
        ],
    ],
    'initial_territory_radius' => 2,
    'initial_island_land_radius' => 2,
    'initial_island_growth_radius' => 4,
    'initial_island_reservation_radius' => 5,
    'initial_island_growth_steps' => 100,
    'development_plan_quantity' => [
        'type' => 'integer',
        'minimum' => 1,
        'maximum' => 99,
        'default' => 1,
        'quick_presets' => [
            0 => 1,
            1 => 5,
            2 => 10,
            3 => 25,
            4 => 50,
            5 => 99,
        ],
    ],
    'initial_island_minimum_shallow_cells' => 3,
    'base_money_capacity' => 9999,
    'base_food_capacity_tons' => 999900,
    'inventory_sale_rates' => [
        'wheat' => [
            'inventory_units' => 1000,
            'money_units' => 1,
        ],
        'fish' => [
            'inventory_units' => 1000,
            'money_units' => 1,
        ],
        'monster_meat' => [
            'inventory_units' => 1000,
            'money_units' => 2,
        ],
        'industrial_goods' => [
            'inventory_units' => 1000,
            'money_units' => 1,
        ],
        'minerals' => [
            'inventory_units' => 1000,
            'money_units' => 1,
        ],
    ],
    'turn_processing' => [
        'automatic_finance_money' => 10,
        'food' => [
            'population_per_nutrition' => 5,
            'consumption_priority' => [
                0 => 'wheat',
                1 => 'fish',
                2 => 'monster_meat',
            ],
            'production_overflow_resolution_stage' => 'after_population_nutrition_consumption',
        ],
        'workforce' => [
            'priority' => [
                0 => 'farm',
                1 => 'factory_mine',
            ],
            'farm_output_per_worker' => 1,
            'factory_output_per_worker' => 1,
            'mine_output_per_worker' => 1,
            'allocation_rule' => 'capacity_proportional_largest_remainder',
        ],
        'settlement' => [
            'appearance_probability' => [
                'numerator' => 20,
                'denominator' => 100,
            ],
            'initial_population' => 100,
            'eligible_terrain_key' => 'plain',
            'adjacent_facility_key' => 'farm',
            'stages' => [
                'village' => [
                    'facility_key' => 'village',
                    'minimum_population' => 1,
                    'maximum_population' => 2999,
                ],
                'town' => [
                    'facility_key' => 'town',
                    'minimum_population' => 3000,
                    'maximum_population' => 9999,
                ],
                'city' => [
                    'facility_key' => 'city',
                    'minimum_population' => 10000,
                    'maximum_population' => 2147483647,
                ],
            ],
            'ordinary_growth' => [
                'minimum' => 100,
                'maximum' => 1000,
                'unit_people' => 1,
            ],
            'attraction_growth' => [
                'minimum' => 100,
                'maximum' => 3000,
                'unit_people' => 1,
            ],
            'attraction_maximum_population' => 20000,
            'post_ordinary_attraction_growth' => [
                'minimum' => 100,
                'maximum' => 300,
                'unit_people' => 1,
            ],
            'ordinary_maximum_population' => 10000,
        ],
        'famine' => [
            'loss_minimum' => 100,
            'loss_maximum' => 3000,
            'loss_unit_people' => 1,
        ],
        'riot' => [
            'probability' => [
                'numerator' => 1,
                'denominator' => 4,
            ],
            'facility_keys' => [
                0 => 'farm',
                1 => 'factory',
                2 => 'missile_base',
                3 => 'seabed_base',
                4 => 'defense',
                5 => 'decoy',
            ],
        ],
        'command_random_effects' => [
            'land_clear_buried_treasure' => [
                'probability' => [
                    'numerator' => 10,
                    'denominator' => 1000,
                ],
                'reward_minimum_money' => 100,
                'reward_maximum_money' => 1000,
            ],
            'seabed_oil_search' => [
                'facility_key' => 'seabed_oil_field',
                'draw_denominator' => 100,
                'success_threshold_per_cost_unit' => 1,
            ],
            'land_level_earthquake' => [
                'probability' => [
                    'numerator' => 5,
                    'denominator' => 2000,
                ],
                'radius' => 10,
                'minimum_city_population' => 10000,
                'facility_keys' => [
                    0 => 'factory',
                    1 => 'decoy',
                ],
                'damage_probability' => [
                    'numerator' => 1,
                    'denominator' => 4,
                ],
            ],
        ],
        'sale_policy' => [
            'sell_all_forbidden_resource_keys' => [
                0 => 'wheat',
            ],
        ],
        'disasters' => [
            'earthquake' => [
                'probability' => [
                    'numerator' => 80,
                    'denominator' => 2000,
                ],
                'center_padding' => 5,
                'radius' => 10,
                'minimum_city_population' => 10000,
                'facility_keys' => [
                    0 => 'factory',
                    1 => 'decoy',
                ],
                'damage_probability' => [
                    'numerator' => 1,
                    'denominator' => 4,
                ],
            ],
            'tsunami' => [
                'probability' => [
                    'numerator' => 300,
                    'denominator' => 2000,
                ],
                'center_padding' => 5,
                'radius' => 10,
                'settlement_facility_keys' => [
                    0 => 'village',
                    1 => 'town',
                    2 => 'city',
                    3 => 'capital',
                ],
                'facility_keys' => [
                    0 => 'farm',
                    1 => 'factory',
                    2 => 'missile_base',
                    3 => 'defense',
                    4 => 'decoy',
                ],
                'excluded_facility_keys' => [
                    0 => 'seabed_base',
                    1 => 'monument',
                ],
                'water_facility_keys' => [
                    0 => 'seabed_base',
                ],
                'internal_denominator' => 12,
                'adjacent_water_offset' => 1,
            ],
            'typhoon' => [
                'probability' => [
                    'numerator' => 400,
                    'denominator' => 2000,
                ],
                'center_padding' => 5,
                'radius' => 10,
                'facility_keys' => [
                    0 => 'farm',
                    1 => 'decoy',
                ],
                'internal_denominator' => 12,
                'base_damage_threshold' => 6,
                'protection_facility_keys' => [
                    0 => 'monument',
                ],
            ],
            'meteor_shower' => [
                'probability' => [
                    'numerator' => 200,
                    'denominator' => 2000,
                ],
                'center_padding' => 5,
                'radius' => 10,
                'continuation_probability' => [
                    'numerator' => 1,
                    'denominator' => 2,
                ],
                'seabed_facility_keys' => [
                    0 => 'seabed_oil_field',
                    1 => 'seabed_base',
                ],
            ],
            'huge_meteor' => [
                'probability' => [
                    'numerator' => 100,
                    'denominator' => 2000,
                ],
                'center_padding' => 2,
                'radius' => 2,
                'seabed_facility_keys' => [
                    0 => 'seabed_oil_field',
                    1 => 'seabed_base',
                ],
            ],
            'eruption' => [
                'probability' => [
                    'numerator' => 200,
                    'denominator' => 2000,
                ],
                'center_padding' => 0,
                'radius' => 1,
                'seabed_facility_keys' => [
                    0 => 'seabed_oil_field',
                    1 => 'seabed_base',
                ],
            ],
            'fire' => [
                'probability' => [
                    'numerator' => 10,
                    'denominator' => 2000,
                ],
                'minimum_city_population' => 10000,
                'facility_keys' => [
                    0 => 'factory',
                    1 => 'decoy',
                ],
                'protection_facility_keys' => [
                    0 => 'monument',
                ],
            ],
            'land_subsidence' => [
                'enabled' => true,
                'base_safe_land_cells' => 100,
                'probability' => [
                    'numerator' => 2,
                    'denominator' => 100,
                ],
                'affected_shallow_result' => 'sea',
                'affected_coastal_land_result' => 'shallow',
                'mountain_immune' => true,
                'capital_damage_percentage' => 30,
                'out_of_bounds_is_water' => true,
                'stream_version' => 1,
            ],
        ],
        'oil_field' => [
            'facility_key' => 'seabed_oil_field',
            'income_money' => 1000,
            'depletion_probability' => [
                'numerator' => 40,
                'denominator' => 1000,
            ],
            'depleted_terrain_key' => 'sea',
        ],
        'resource_sale_phase' => [
            'after' => 'nation_economy',
            'before' => 'development_commands',
        ],
        'territory_influence' => [
            'enabled' => true,
            'policy_version' => 1,
            'owner_states' => [
                0 => 'active',
            ],
            'target' => [
                'unfacilitated_terrain_keys' => [
                    0 => 'forest',
                    1 => 'mountain',
                ],
                'facility_keys' => [
                    0 => 'village',
                    1 => 'town',
                    2 => 'city',
                    3 => 'farm',
                    4 => 'factory',
                    5 => 'mine',
                    6 => 'missile_base',
                    7 => 'defense',
                ],
                'excluded_terrain_keys' => [
                    0 => 'sea',
                    1 => 'shallow',
                    2 => 'wasteland',
                    3 => 'scorched',
                ],
                'excluded_facility_keys' => [
                    0 => 'seabed_base',
                    1 => 'seabed_oil_field',
                    2 => 'monument',
                ],
                'monster_occupancy' => 'exclude',
                'capital_core' => 'exclude',
            ],
            'source' => [
                'excluded_terrain_keys' => [
                    0 => 'sea',
                    1 => 'shallow',
                    2 => 'wasteland',
                    3 => 'scorched',
                ],
                'excluded_facility_keys' => [
                    0 => 'seabed_base',
                    1 => 'seabed_oil_field',
                ],
                'monster_occupancy' => 'exclude',
                'monument' => 'allowed',
            ],
            'neighbor' => [
                'directions' => 6,
                'selection' => 'uniform_one',
                'reroll_on_missing_or_ineligible' => false,
            ],
            'resolution' => [
                'cell_visit_order' => 'shared_surface_shuffle_once',
                'attempts_per_eligible_target' => 1,
                'source_state' => 'evaluate_at_visit',
                'mutation_timing' => 'immediate',
                'direction_stream' => 'territory_influence:direction:v1',
            ],
            'effect' => [
                'owner' => 'source_owner',
                'terrain' => 'preserve',
                'population' => 'preserve',
                'facility' => 'preserve',
                'facility_scale' => 'preserve',
                'resource_and_state' => 'preserve',
            ],
        ],
    ],
    'capital_growth_maximum_population' => 25000,
    'capital_damage_percentages' => [
        'facility_or_wasteland' => 10,
        'excavation_or_shallow' => 30,
        'deep_sea' => 90,
        'eruption_center' => 30,
    ],
    'resource_capacities' => [
        'industrial_goods' => 9999000,
        'minerals' => 9999000,
    ],
    'resource_capacity_overflow' => [
        'behavior' => 'sell_stockpile_overflow_then_discard_unsold',
        'applies_after_sale_policy' => true,
        'converts_unsold_to_money' => false,
        'event_type' => 'capacity.overflow',
    ],
    'monster_definitions' => [
        0 => [
            'key' => 'mecha_inora',
            'name' => 'メカいのら',
            'asset_key' => 'hakoniwa_original.monster.mecha_inora',
            'hardened_asset_key' => null,
            'base_hp' => 2,
            'hp_variation' => 0,
            'skill_key' => 'none',
            'movement_limit' => 1,
            'natural_spawn_tier' => null,
            'wreckage_value_money' => 0,
            'missile_base_experience' => 5,
            'skill_description' => '特殊能力なし（最大1歩移動）',
            'visibility' => 'public',
            'movement_terrain_contract' => [
                'candidate_attempts_per_action' => 3,
                'blocked_terrain_keys' => [
                    0 => 'sea',
                    1 => 'shallow',
                    2 => 'mountain',
                ],
                'blocked_facility_keys' => [
                    0 => 'seabed_oil_field',
                    1 => 'seabed_base',
                    2 => 'mine',
                    3 => 'monument',
                    4 => 'capital',
                ],
                'defense_facility_key' => 'defense',
                'destination_terrain_key' => 'wasteland',
                'preserve_owner' => true,
            ],
            'trample_contract' => [
                'population_after' => 0,
                'remove_facility' => true,
                'restore_previous_terrain' => false,
            ],
            'hardening_contract' => [
                'type' => 'none',
            ],
            'source_metadata' => [
                'kind' => 0,
                'skill_code' => 0,
                'filename' => 'monster7.gif',
                'reward_policy' => 'standard_split',
                'manual' => [
                    'appearance' => '怪獣派遣',
                    'special' => '特殊能力なし',
                ],
                'behavior' => [
                    'movement' => 'legacy_land',
                    'dispatchable' => true,
                    'can_act_on_spawn_turn' => false,
                    'special_action' => 'none',
                    'island_creation_displaceable' => false,
                ],
            ],
            'display_order' => 0,
        ],
        1 => [
            'key' => 'mecha_inora_zero',
            'name' => 'メカいのら零式',
            'asset_key' => 'hakoniwa_custom.monster.mecha_inora_zero',
            'hardened_asset_key' => null,
            'base_hp' => 4,
            'hp_variation' => 0,
            'skill_key' => 'none',
            'movement_limit' => 1,
            'natural_spawn_tier' => null,
            'wreckage_value_money' => 0,
            'missile_base_experience' => 35,
            'skill_description' => 'HP1で核爆発',
            'visibility' => 'public',
            'movement_terrain_contract' => [
                'candidate_attempts_per_action' => 3,
                'blocked_terrain_keys' => [
                    0 => 'sea',
                    1 => 'shallow',
                    2 => 'mountain',
                ],
                'blocked_facility_keys' => [
                    0 => 'seabed_oil_field',
                    1 => 'seabed_base',
                    2 => 'mine',
                    3 => 'monument',
                    4 => 'capital',
                ],
                'defense_facility_key' => 'defense',
                'destination_terrain_key' => 'wasteland',
                'preserve_owner' => true,
            ],
            'trample_contract' => [
                'population_after' => 0,
                'remove_facility' => true,
                'restore_previous_terrain' => false,
            ],
            'hardening_contract' => [
                'type' => 'none',
            ],
            'source_metadata' => [
                'reward_policy' => 'standard_split',
                'secretary_item_target_safety' => [
                    'policy' => 'certain_self_action_at_remaining_hp',
                    'remaining_hp' => 1,
                ],
                'manual' => [
                    'appearance' => '怪獣派遣（9,999億円）',
                    'special' => 'HP1で核爆発',
                ],
                'behavior' => [
                    'movement' => 'legacy_land',
                    'dispatchable' => true,
                    'can_act_on_spawn_turn' => false,
                    'special_action' => 'nuclear_self_destruct_at_hp_one',
                    'island_creation_displaceable' => false,
                ],
            ],
            'display_order' => 50,
        ],
        2 => [
            'key' => 'inora',
            'name' => 'いのら',
            'asset_key' => 'hakoniwa_original.monster.inora',
            'hardened_asset_key' => null,
            'base_hp' => 1,
            'hp_variation' => 1,
            'skill_key' => 'none',
            'movement_limit' => 1,
            'natural_spawn_tier' => 1,
            'wreckage_value_money' => 400,
            'missile_base_experience' => 5,
            'skill_description' => '特殊能力なし（最大1歩移動）',
            'visibility' => 'public',
            'movement_terrain_contract' => [
                'candidate_attempts_per_action' => 3,
                'blocked_terrain_keys' => [
                    0 => 'sea',
                    1 => 'shallow',
                    2 => 'mountain',
                ],
                'blocked_facility_keys' => [
                    0 => 'seabed_oil_field',
                    1 => 'seabed_base',
                    2 => 'mine',
                    3 => 'monument',
                    4 => 'capital',
                ],
                'defense_facility_key' => 'defense',
                'destination_terrain_key' => 'wasteland',
                'preserve_owner' => true,
            ],
            'trample_contract' => [
                'population_after' => 0,
                'remove_facility' => true,
                'restore_previous_terrain' => false,
            ],
            'hardening_contract' => [
                'type' => 'none',
            ],
            'source_metadata' => [
                'kind' => 1,
                'skill_code' => 0,
                'filename' => 'monster0.gif',
                'reward_policy' => 'standard_split',
                'manual' => [
                    'appearance' => '人口10万人以上で自然発生',
                    'special' => '特殊能力なし',
                ],
                'behavior' => [
                    'movement' => 'legacy_land',
                    'dispatchable' => false,
                    'can_act_on_spawn_turn' => false,
                    'special_action' => 'none',
                    'island_creation_displaceable' => false,
                ],
            ],
            'display_order' => 100,
        ],
        3 => [
            'key' => 'sanjira',
            'name' => 'サンジラ',
            'asset_key' => 'hakoniwa_original.monster.sanjira',
            'hardened_asset_key' => 'hakoniwa_original.monster.hardened',
            'base_hp' => 1,
            'hp_variation' => 1,
            'skill_key' => 'harden_odd',
            'movement_limit' => 1,
            'natural_spawn_tier' => 1,
            'wreckage_value_money' => 500,
            'missile_base_experience' => 7,
            'skill_description' => '奇数ターンは硬化し、移動と通常ダメージを無効化',
            'visibility' => 'public',
            'movement_terrain_contract' => [
                'candidate_attempts_per_action' => 3,
                'blocked_terrain_keys' => [
                    0 => 'sea',
                    1 => 'shallow',
                    2 => 'mountain',
                ],
                'blocked_facility_keys' => [
                    0 => 'seabed_oil_field',
                    1 => 'seabed_base',
                    2 => 'mine',
                    3 => 'monument',
                    4 => 'capital',
                ],
                'defense_facility_key' => 'defense',
                'destination_terrain_key' => 'wasteland',
                'preserve_owner' => true,
            ],
            'trample_contract' => [
                'population_after' => 0,
                'remove_facility' => true,
                'restore_previous_terrain' => false,
            ],
            'hardening_contract' => [
                'type' => 'target_turn_parity',
                'parity' => 'odd',
            ],
            'source_metadata' => [
                'kind' => 2,
                'skill_code' => 3,
                'filename' => 'monster5.gif',
                'reward_policy' => 'standard_split',
                'manual' => [
                    'appearance' => '人口10万人以上で自然発生',
                    'special' => '奇数ターンは硬化',
                ],
                'behavior' => [
                    'movement' => 'legacy_land',
                    'dispatchable' => false,
                    'can_act_on_spawn_turn' => false,
                    'special_action' => 'none',
                    'island_creation_displaceable' => false,
                ],
            ],
            'display_order' => 200,
        ],
        4 => [
            'key' => 'red_inora',
            'name' => 'レッドいのら',
            'asset_key' => 'hakoniwa_original.monster.red_inora',
            'hardened_asset_key' => null,
            'base_hp' => 3,
            'hp_variation' => 1,
            'skill_key' => 'none',
            'movement_limit' => 1,
            'natural_spawn_tier' => 2,
            'wreckage_value_money' => 1000,
            'missile_base_experience' => 12,
            'skill_description' => '特殊能力なし（最大1歩移動）',
            'visibility' => 'public',
            'movement_terrain_contract' => [
                'candidate_attempts_per_action' => 3,
                'blocked_terrain_keys' => [
                    0 => 'sea',
                    1 => 'shallow',
                    2 => 'mountain',
                ],
                'blocked_facility_keys' => [
                    0 => 'seabed_oil_field',
                    1 => 'seabed_base',
                    2 => 'mine',
                    3 => 'monument',
                    4 => 'capital',
                ],
                'defense_facility_key' => 'defense',
                'destination_terrain_key' => 'wasteland',
                'preserve_owner' => true,
            ],
            'trample_contract' => [
                'population_after' => 0,
                'remove_facility' => true,
                'restore_previous_terrain' => false,
            ],
            'hardening_contract' => [
                'type' => 'none',
            ],
            'source_metadata' => [
                'kind' => 3,
                'skill_code' => 0,
                'filename' => 'monster1.gif',
                'reward_policy' => 'standard_split',
                'manual' => [
                    'appearance' => '人口25万人以上で自然発生',
                    'special' => '特殊能力なし',
                ],
                'behavior' => [
                    'movement' => 'legacy_land',
                    'dispatchable' => false,
                    'can_act_on_spawn_turn' => false,
                    'special_action' => 'none',
                    'island_creation_displaceable' => false,
                ],
            ],
            'display_order' => 300,
        ],
        5 => [
            'key' => 'dark_inora',
            'name' => 'ダークいのら',
            'asset_key' => 'hakoniwa_original.monster.dark_inora',
            'hardened_asset_key' => null,
            'base_hp' => 2,
            'hp_variation' => 1,
            'skill_key' => 'move_2',
            'movement_limit' => 2,
            'natural_spawn_tier' => 2,
            'wreckage_value_money' => 800,
            'missile_base_experience' => 15,
            'skill_description' => '1ターンに最大2歩移動',
            'visibility' => 'public',
            'movement_terrain_contract' => [
                'candidate_attempts_per_action' => 3,
                'blocked_terrain_keys' => [
                    0 => 'sea',
                    1 => 'shallow',
                    2 => 'mountain',
                ],
                'blocked_facility_keys' => [
                    0 => 'seabed_oil_field',
                    1 => 'seabed_base',
                    2 => 'mine',
                    3 => 'monument',
                    4 => 'capital',
                ],
                'defense_facility_key' => 'defense',
                'destination_terrain_key' => 'wasteland',
                'preserve_owner' => true,
            ],
            'trample_contract' => [
                'population_after' => 0,
                'remove_facility' => true,
                'restore_previous_terrain' => false,
            ],
            'hardening_contract' => [
                'type' => 'none',
            ],
            'source_metadata' => [
                'kind' => 4,
                'skill_code' => 1,
                'filename' => 'monster2.gif',
                'reward_policy' => 'standard_split',
                'manual' => [
                    'appearance' => '人口25万人以上で自然発生',
                    'special' => '最大2歩移動',
                ],
                'behavior' => [
                    'movement' => 'legacy_land',
                    'dispatchable' => false,
                    'can_act_on_spawn_turn' => false,
                    'special_action' => 'none',
                    'island_creation_displaceable' => false,
                ],
            ],
            'display_order' => 400,
        ],
        6 => [
            'key' => 'aoi_inora',
            'name' => 'あおいのら',
            'asset_key' => 'hakoniwa_custom.monster.aoi_inora',
            'hardened_asset_key' => null,
            'base_hp' => 2,
            'hp_variation' => 1,
            'skill_key' => 'none',
            'movement_limit' => 1,
            'natural_spawn_tier' => null,
            'wreckage_value_money' => 1200,
            'missile_base_experience' => 18,
            'skill_description' => '海から陸地へ侵攻し、踏み荒らした場所を中立の海へ変える',
            'visibility' => 'public',
            'movement_terrain_contract' => [
                'candidate_attempts_per_action' => 3,
                'blocked_terrain_keys' => [
                    0 => 'mountain',
                ],
                'blocked_facility_keys' => [
                    0 => 'mine',
                    1 => 'monument',
                    2 => 'capital',
                ],
                'defense_facility_key' => 'defense',
                'destination_terrain_key' => 'sea',
                'clear_owner' => true,
            ],
            'trample_contract' => [
                'population_after' => 0,
                'remove_facility' => true,
                'restore_previous_terrain' => false,
            ],
            'hardening_contract' => [
                'type' => 'none',
            ],
            'source_metadata' => [
                'reward_policy' => 'hostless_full_killer_money',
                'manual' => [
                    'appearance' => 'Worldの海上災害',
                    'special' => '海から陸地へ侵攻し中立の海へ変化。中立海上の通常撃破は撃破者へ残骸資金100%',
                ],
                'behavior' => [
                    'movement' => 'water_neutralizing',
                    'dispatchable' => false,
                    'can_act_on_spawn_turn' => false,
                    'special_action' => 'none',
                    'island_creation_displaceable' => true,
                    'world_spawn' => [
                        'type' => 'world_aoi_disaster',
                        'probability_per_active_owned_land_cell' => [
                            'numerator' => 1,
                            'denominator' => 10000,
                        ],
                        'maximum_probability_numerator' => 10000,
                        'terrain_keys' => [
                            0 => 'sea',
                            1 => 'shallow',
                        ],
                        'minimum_land_distance' => 4,
                        'stream_version' => 1,
                    ],
                ],
            ],
            'display_order' => 450,
        ],
        7 => [
            'key' => 'inora_ghost',
            'name' => 'いのらゴースト',
            'asset_key' => 'hakoniwa_original.monster.inora_ghost',
            'hardened_asset_key' => null,
            'base_hp' => 1,
            'hp_variation' => 0,
            'skill_key' => 'move_9999',
            'movement_limit' => 9999,
            'natural_spawn_tier' => 2,
            'wreckage_value_money' => 300,
            'missile_base_experience' => 10,
            'skill_description' => '1ターンに最大？歩移動',
            'visibility' => 'public',
            'movement_terrain_contract' => [
                'candidate_attempts_per_action' => 3,
                'blocked_terrain_keys' => [
                    0 => 'sea',
                    1 => 'shallow',
                    2 => 'mountain',
                ],
                'blocked_facility_keys' => [
                    0 => 'seabed_oil_field',
                    1 => 'seabed_base',
                    2 => 'mine',
                    3 => 'monument',
                    4 => 'capital',
                ],
                'defense_facility_key' => 'defense',
                'destination_terrain_key' => 'wasteland',
                'preserve_owner' => true,
            ],
            'trample_contract' => [
                'population_after' => 0,
                'remove_facility' => true,
                'restore_previous_terrain' => false,
            ],
            'hardening_contract' => [
                'type' => 'none',
            ],
            'source_metadata' => [
                'kind' => 5,
                'skill_code' => 2,
                'filename' => 'monster8.gif',
                'reward_policy' => 'standard_split',
                'manual' => [
                    'appearance' => '人口25万人以上で自然発生',
                    'special' => '高速移動',
                ],
                'behavior' => [
                    'movement' => 'legacy_land',
                    'dispatchable' => false,
                    'can_act_on_spawn_turn' => false,
                    'special_action' => 'none',
                    'island_creation_displaceable' => false,
                ],
            ],
            'display_order' => 500,
        ],
        8 => [
            'key' => 'whale',
            'name' => 'クジラ',
            'asset_key' => 'hakoniwa_original.monster.kujira',
            'hardened_asset_key' => 'hakoniwa_original.monster.hardened',
            'base_hp' => 4,
            'hp_variation' => 1,
            'skill_key' => 'harden_even',
            'movement_limit' => 1,
            'natural_spawn_tier' => 3,
            'wreckage_value_money' => 1500,
            'missile_base_experience' => 20,
            'skill_description' => '偶数ターンは硬化し、移動と通常ダメージを無効化',
            'visibility' => 'public',
            'movement_terrain_contract' => [
                'candidate_attempts_per_action' => 3,
                'blocked_terrain_keys' => [
                    0 => 'sea',
                    1 => 'shallow',
                    2 => 'mountain',
                ],
                'blocked_facility_keys' => [
                    0 => 'seabed_oil_field',
                    1 => 'seabed_base',
                    2 => 'mine',
                    3 => 'monument',
                    4 => 'capital',
                ],
                'defense_facility_key' => 'defense',
                'destination_terrain_key' => 'wasteland',
                'preserve_owner' => true,
            ],
            'trample_contract' => [
                'population_after' => 0,
                'remove_facility' => true,
                'restore_previous_terrain' => false,
            ],
            'hardening_contract' => [
                'type' => 'target_turn_parity',
                'parity' => 'even',
            ],
            'source_metadata' => [
                'kind' => 6,
                'skill_code' => 4,
                'filename' => 'monster6.gif',
                'reward_policy' => 'standard_split',
                'manual' => [
                    'appearance' => '人口40万人以上で自然発生',
                    'special' => '偶数ターンは硬化',
                ],
                'behavior' => [
                    'movement' => 'legacy_land',
                    'dispatchable' => false,
                    'can_act_on_spawn_turn' => false,
                    'special_action' => 'none',
                    'island_creation_displaceable' => false,
                ],
            ],
            'display_order' => 600,
        ],
        9 => [
            'key' => 'king_inora',
            'name' => 'キングいのら',
            'asset_key' => 'hakoniwa_original.monster.king_inora',
            'hardened_asset_key' => null,
            'base_hp' => 5,
            'hp_variation' => 1,
            'skill_key' => 'none',
            'movement_limit' => 1,
            'natural_spawn_tier' => 3,
            'wreckage_value_money' => 2000,
            'missile_base_experience' => 30,
            'skill_description' => '特殊能力なし（最大1歩移動）',
            'visibility' => 'public',
            'movement_terrain_contract' => [
                'candidate_attempts_per_action' => 3,
                'blocked_terrain_keys' => [
                    0 => 'sea',
                    1 => 'shallow',
                    2 => 'mountain',
                ],
                'blocked_facility_keys' => [
                    0 => 'seabed_oil_field',
                    1 => 'seabed_base',
                    2 => 'mine',
                    3 => 'monument',
                    4 => 'capital',
                ],
                'defense_facility_key' => 'defense',
                'destination_terrain_key' => 'wasteland',
                'preserve_owner' => true,
            ],
            'trample_contract' => [
                'population_after' => 0,
                'remove_facility' => true,
                'restore_previous_terrain' => false,
            ],
            'hardening_contract' => [
                'type' => 'none',
            ],
            'source_metadata' => [
                'kind' => 7,
                'skill_code' => 0,
                'filename' => 'monster3.gif',
                'reward_policy' => 'standard_split',
                'manual' => [
                    'appearance' => '人口40万人以上で自然発生',
                    'special' => '特殊能力なし',
                ],
                'behavior' => [
                    'movement' => 'legacy_land',
                    'dispatchable' => false,
                    'can_act_on_spawn_turn' => false,
                    'special_action' => 'none',
                    'island_creation_displaceable' => false,
                ],
            ],
            'display_order' => 700,
        ],
    ],
    'monster_system' => [
        'footprint_cells' => 1,
        'natural_spawn' => [
            'probability_per_land_cell' => [
                'numerator' => 2,
                'denominator' => 10000,
            ],
            'maximum_probability_numerator' => 10000,
            'one_draw_per_active_nation' => true,
            'eligible_nation_state' => 'active',
            'minimum_population' => 100000,
            'population_tiers' => [
                0 => [
                    'minimum_population' => 100000,
                    'monster_keys' => [
                        0 => 'inora',
                        1 => 'sanjira',
                    ],
                ],
                1 => [
                    'minimum_population' => 250000,
                    'monster_keys' => [
                        0 => 'inora',
                        1 => 'sanjira',
                        2 => 'red_inora',
                        3 => 'dark_inora',
                        4 => 'inora_ghost',
                    ],
                ],
                2 => [
                    'minimum_population' => 400000,
                    'monster_keys' => [
                        0 => 'inora',
                        1 => 'sanjira',
                        2 => 'red_inora',
                        3 => 'dark_inora',
                        4 => 'inora_ghost',
                        5 => 'whale',
                        6 => 'king_inora',
                    ],
                ],
            ],
            'settlement_facility_keys' => [
                0 => 'village',
                1 => 'town',
                2 => 'city',
            ],
            'exclude_capital' => true,
            'maximum_per_nation_per_turn' => 1,
            'selection' => 'uniform_source_pool',
            'stream_version' => 1,
        ],
        'movement' => [
            'candidate_attempts_per_action' => 3,
            'blocked_terrain_keys' => [
                0 => 'sea',
                1 => 'shallow',
                2 => 'mountain',
            ],
            'blocked_facility_keys' => [
                0 => 'seabed_oil_field',
                1 => 'seabed_base',
                2 => 'mine',
                3 => 'monument',
                4 => 'capital',
            ],
            'defense_facility_key' => 'defense',
            'destination_terrain_key' => 'wasteland',
            'preserve_owner' => true,
        ],
        'reward' => [
            'killer_money_share' => 'floor_half',
            'host_remainder_share' => true,
            'host_food_resource_key' => 'monster_meat',
            'food_tons_per_money_unit' => 500,
            'missile_base_experience_maximum' => 200,
        ],
        'terrain_events' => [
            'preserve_occupancy' => [
                0 => 'earthquake',
                1 => 'tsunami',
                2 => 'typhoon',
            ],
            'remove_without_rewards' => [
                0 => 'meteor_shower',
                1 => 'huge_meteor',
                2 => 'eruption',
                3 => 'land_subsidence',
                4 => 'defense_self_destruct',
                5 => 'terrain_destruction_missile',
            ],
        ],
        'kill_stats' => [
            'scope' => 'nation_monster_definition',
            'increment_on_attributed_final_blow' => true,
            'authoritative_for_final_blow_count' => true,
            'authoritative_for_kill_marks' => true,
        ],
    ],
    'capital_relocation_cost_money' => 1000,
    'military' => [
        'launch_base_facility_keys' => [
            0 => 'missile_base',
            1 => 'seabed_base',
        ],
        'missiles' => [
            'missile' => [
                'cost_money_per_shot' => 20,
                'deviation_radius' => 2,
                'creates_terrain' => 'scorched',
                'refugees' => true,
            ],
            'pp_missile' => [
                'cost_money_per_shot' => 50,
                'deviation_radius' => 1,
                'creates_terrain' => 'scorched',
                'refugees' => true,
            ],
            'land_destruction_missile' => [
                'cost_money_per_shot' => 100,
                'deviation_radius' => 2,
                'creates_terrain' => null,
                'refugees' => false,
            ],
            'spp_missile' => [
                'cost_money_per_shot' => 500,
                'deviation_radius' => 0,
                'creates_terrain' => 'scorched',
                'refugees' => true,
            ],
        ],
        'visibility' => [
            'launch_summary' => 'public',
            'meaningful_impacts' => 'public',
            'ineffective_impacts' => 'aggregate_per_launch',
            'firing_nation_details' => 'private',
            'anonymous_missile_keys' => [
            ],
        ],
        'dormant_impact' => [
            'explicit_target_state' => 'any_existing_coordinate',
            'no_effect_owner_states' => [
            ],
            'preserve' => [
                0 => 'cell',
                1 => 'facility',
                2 => 'population',
                3 => 'monster_occupancy',
            ],
            'monster_exception' => false,
        ],
        'refugees' => [
            'settlement_facility_keys' => [
                0 => 'village',
                1 => 'town',
                2 => 'city',
                3 => 'capital',
            ],
            'recipient' => 'firing_nation',
            'generated_fraction' => [
                'numerator' => 1,
                'denominator' => 2,
            ],
            'event_types' => [
                0 => 'refugee_generated',
                1 => 'refugee_received',
            ],
        ],
        'launch_base_experience' => [
            'facility_keys' => [
                0 => 'missile_base',
                1 => 'seabed_base',
            ],
            'settlement_hit' => [
                'missile_keys' => [
                    0 => 'missile',
                    1 => 'pp_missile',
                    2 => 'spp_missile',
                ],
                'population_divisor' => 2000,
                'capital_population_loss_multiplier' => 2,
            ],
            'monster_damage_experience' => 0,
            'monster_final_blow_experience' => 'monster_definition.missile_base_experience',
        ],
        'seabed_base_resistance' => [
            'facility_key' => 'seabed_base',
            'ineffective_missile_keys' => [
                0 => 'missile',
                1 => 'pp_missile',
                2 => 'spp_missile',
            ],
            'destructive_missile_keys' => [
                0 => 'land_destruction_missile',
            ],
        ],
        'defense_spp_resistance' => [
            'facility_key' => 'defense',
            'ineffective_missile_keys' => [
                0 => 'spp_missile',
            ],
        ],
        'defense_interception' => [
            'facility_key' => 'defense',
            'radius' => 2,
            'exclude_center' => true,
            'defense_target_cells' => 'exclude',
            'missile_keys' => [
                0 => 'missile',
                1 => 'pp_missile',
                2 => 'land_destruction_missile',
                3 => 'spp_missile',
            ],
            'facility_owner_scope' => 'any',
            'monster_occupied_cells' => 'include',
            'self_fired_missiles' => 'include',
            'overlap_resolution' => 'single_interception',
            'resolve_before' => 'secretary',
        ],
    ],
    'territory_transfer' => [
        'capital_core' => [
            'ownership_transfer_protected' => true,
            'owner_states' => [
                0 => 'active',
            ],
            'radius' => 2,
        ],
    ],
    'secretary' => [
        'skills' => [
            'agricultural_policy' => [
                'key' => 'agricultural_policy',
                'name' => '農業政策',
                'initial_level' => 0,
                'level_requirement' => [
                    'basis' => 'next_level_squared',
                    'multiplier' => 1,
                ],
                'effect' => [
                    'type' => 'production_multiplier',
                    'resource_key' => 'wheat',
                    'per_mille_per_level' => 1,
                ],
                'experience_source' => [
                    'type' => 'successful_command_execution',
                    'command_key' => 'build_farm',
                    'points_per_execution' => 1,
                    'quantity_multiplier' => false,
                ],
            ],
            'specialty_development' => [
                'key' => 'specialty_development',
                'name' => '特産品開発',
                'initial_level' => 0,
                'level_requirement' => [
                    'basis' => 'next_level_squared',
                    'multiplier' => 1,
                ],
                'effect' => [
                    'type' => 'production_multiplier',
                    'resource_key' => 'industrial_goods',
                    'per_mille_per_level' => 1,
                ],
                'experience_source' => [
                    'type' => 'successful_command_execution',
                    'command_key' => 'build_factory',
                    'points_per_execution' => 1,
                    'quantity_multiplier' => false,
                ],
            ],
            'gold_vein_survey' => [
                'key' => 'gold_vein_survey',
                'name' => '金鉱脈調査',
                'initial_level' => 0,
                'level_requirement' => [
                    'basis' => 'next_level_squared',
                    'multiplier' => 1,
                ],
                'effect' => [
                    'type' => 'production_multiplier',
                    'resource_key' => 'minerals',
                    'per_mille_per_level' => 1,
                ],
                'experience_source' => [
                    'type' => 'successful_command_execution',
                    'command_key' => 'build_mine',
                    'points_per_execution' => 1,
                    'quantity_multiplier' => false,
                ],
            ],
            'final_defense_line' => [
                'key' => 'final_defense_line',
                'name' => '最終防衛ライン',
                'initial_level' => 1,
                'level_requirement' => [
                    'basis' => 'current_level_squared',
                    'multiplier' => 100,
                ],
                'effect' => [
                    'type' => 'final_defense_line',
                    'interceptions_per_level_per_turn' => 1,
                    'normal_defense_resolves_first' => true,
                    'exclude_monster_occupied_cells' => true,
                ],
                'experience_source' => [
                    'type' => 'owned_cell_missile_arrival',
                    'points_per_missile' => 1,
                    'include_normal_defense_interception' => true,
                    'include_secretary_interception' => true,
                    'include_actual_impact' => true,
                    'include_self_fired_collateral' => true,
                    'independent_from_interception_eligibility' => true,
                ],
            ],
        ],
        'item_categories' => [
            'bow' => [
                'key' => 'bow',
                'max_equipped' => 1,
            ],
            'ring' => [
                'key' => 'ring',
                'max_equipped' => 5,
            ],
        ],
        'items' => [
            'old_bow' => [
                'key' => 'old_bow',
                'category' => 'bow',
                'max_level' => 1,
                'same_item_max_equipped' => 1,
                'effects' => [
                    0 => [
                        'type' => 'pre_normal_monster_attack',
                        'timing' => 'after_missile_finalization_before_normal_monsters',
                        'chance_basis_points' => 1000,
                        'damage' => 1,
                        'damage_type' => 'secretary_old_bow',
                        'target_scope' => 'owned_territory',
                        'target_map_space_keys' => [
                            0 => 'surface',
                        ],
                        'target_safety_policy' => 'avoid_ineffective_or_immediate_hazard',
                        'random_stream_version' => 1,
                    ],
                ],
            ],
            'ring' => [
                'key' => 'ring',
                'category' => 'ring',
                'max_level' => 10,
                'same_item_max_equipped' => 5,
                'effects' => [
                    0 => [
                        'type' => 'finance_income_bonus',
                        'bonus_money_per_level' => 1,
                        'stacking' => 'sum_equipped_levels',
                    ],
                ],
            ],
        ],
    ],
    'turn_resolution' => [
        'normal_monster_stage' => 'after_ordinary_surface_cell_events',
    ],
];
