<?php

$v17 = require __DIR__.'/hakoniwa-2s-plus-v17.php';
$worldAndMap = (require __DIR__.'/v18/world-and-map.php')['payload'];
$lifecycleAndKarma = (require __DIR__.'/v18/lifecycle-and-karma.php')['payload'];
$terrainAndDisasters = (require __DIR__.'/v18/terrain-and-disasters.php')['payload'];
$facilities = (require __DIR__.'/v18/facilities.php')['payload'];
$commandsAndProduction = (require __DIR__.'/v18/commands-and-production.php')['payload'];
$turnPipeline = (require __DIR__.'/v18/turn-pipeline.php')['payload'];
$monstersAndMilitary = (require __DIR__.'/v18/monsters-and-military.php')['payload'];
$turnProcessing = $v17['turn_processing'];
$turnProcessing['settlement'] = $turnPipeline['turn_processing']['settlement'];
$turnProcessing['undersea_city_maintenance'] = $turnPipeline['turn_processing']['undersea_city_maintenance'];
$turnProcessing['disasters'] = $terrainAndDisasters['turn_processing']['disasters'];

return [
    'key' => $worldAndMap['key'],
    'version' => $worldAndMap['version'],
    'chunk_size' => $v17['chunk_size'],
    'initial_x_min' => $v17['initial_x_min'],
    'initial_x_max' => $v17['initial_x_max'],
    'initial_y_min' => $v17['initial_y_min'],
    'initial_y_max' => $v17['initial_y_max'],
    'minimum_capital_distance' => $v17['minimum_capital_distance'],
    'capital_initial_population' => $v17['capital_initial_population'],
    'capital_minimum_population' => $v17['capital_minimum_population'],
    'initial_money' => $v17['initial_money'],
    'nation_lifecycle' => $lifecycleAndKarma['nation_lifecycle'],
    'karma' => $lifecycleAndKarma['karma'],
    'resource_definitions' => $v17['resource_definitions'],
    'resource_sale_prices' => $v17['resource_sale_prices'],
    'initial_resources' => $v17['initial_resources'],
    'default_sale_policy' => $v17['default_sale_policy'],
    'command_queue_limit' => $v17['command_queue_limit'],
    'terrain_quantities' => $v17['terrain_quantities'],
    'facility_definitions' => $facilities['facility_definitions'],
    'command_definitions' => $commandsAndProduction['command_definitions'],
    'production_definitions' => $commandsAndProduction['production_definitions'],
    'initial_territory_radius' => $v17['initial_territory_radius'],
    'initial_island_land_radius' => $v17['initial_island_land_radius'],
    'initial_island_growth_radius' => $v17['initial_island_growth_radius'],
    'initial_island_reservation_radius' => $v17['initial_island_reservation_radius'],
    'initial_island_growth_steps' => $v17['initial_island_growth_steps'],
    'development_plan_quantity' => $v17['development_plan_quantity'],
    'initial_island_minimum_shallow_cells' => $v17['initial_island_minimum_shallow_cells'],
    'base_money_capacity' => $v17['base_money_capacity'],
    'base_food_capacity_tons' => $v17['base_food_capacity_tons'],
    'inventory_sale_rates' => $v17['inventory_sale_rates'],
    'turn_processing' => $turnProcessing,
    'capital_growth_maximum_population' => $v17['capital_growth_maximum_population'],
    'capital_damage_percentages' => $v17['capital_damage_percentages'],
    'resource_capacities' => $v17['resource_capacities'],
    'resource_capacity_overflow' => $v17['resource_capacity_overflow'],
    'monster_definitions' => $monstersAndMilitary['monster_definitions'],
    'monster_system' => $monstersAndMilitary['monster_system'],
    'capital_relocation_cost_money' => $v17['capital_relocation_cost_money'],
    'military' => $monstersAndMilitary['military'],
    'territory_transfer' => $v17['territory_transfer'],
    'secretary' => $v17['secretary'],
    'trading_post' => $v17['trading_post'],
    'turn_resolution' => $v17['turn_resolution'],
];
