<?php

$worldAndMap = (require __DIR__.'/current/world-and-map.php')['payload'];
$lifecycleAndKarma = (require __DIR__.'/current/lifecycle-and-karma.php')['payload'];
$economyAndResources = (require __DIR__.'/current/economy-and-resources.php')['payload'];
$terrainAndDisasters = (require __DIR__.'/current/terrain-and-disasters.php')['payload'];
$facilities = (require __DIR__.'/current/facilities.php')['payload'];
$commandsAndProduction = (require __DIR__.'/current/commands-and-production.php')['payload'];
$turnPipeline = (require __DIR__.'/current/turn-pipeline.php')['payload'];
$monstersAndMilitary = (require __DIR__.'/current/monsters-and-military.php')['payload'];
$secretary = (require __DIR__.'/current/secretary.php')['payload'];
$tradingPost = (require __DIR__.'/current/trading-post.php')['payload'];

return [
    'key' => $worldAndMap['key'],
    'version' => $worldAndMap['version'],
    'chunk_size' => $worldAndMap['chunk_size'],
    'initial_x_min' => $worldAndMap['initial_x_min'],
    'initial_x_max' => $worldAndMap['initial_x_max'],
    'initial_y_min' => $worldAndMap['initial_y_min'],
    'initial_y_max' => $worldAndMap['initial_y_max'],
    'minimum_capital_distance' => $worldAndMap['minimum_capital_distance'],
    'capital_initial_population' => $worldAndMap['capital_initial_population'],
    'capital_minimum_population' => $worldAndMap['capital_minimum_population'],
    'initial_money' => $economyAndResources['initial_money'],
    'nation_lifecycle' => $lifecycleAndKarma['nation_lifecycle'],
    'karma' => $lifecycleAndKarma['karma'],
    'resource_definitions' => $economyAndResources['resource_definitions'],
    'resource_sale_prices' => $economyAndResources['resource_sale_prices'],
    'initial_resources' => $economyAndResources['initial_resources'],
    'default_sale_policy' => $economyAndResources['default_sale_policy'],
    'command_queue_limit' => $commandsAndProduction['command_queue_limit'],
    'terrain_quantities' => $terrainAndDisasters['terrain_quantities'],
    'facility_definitions' => $facilities['facility_definitions'],
    'command_definitions' => $commandsAndProduction['command_definitions'],
    'production_definitions' => $commandsAndProduction['production_definitions'],
    'initial_territory_radius' => $worldAndMap['initial_territory_radius'],
    'initial_island_land_radius' => $worldAndMap['initial_island_land_radius'],
    'initial_island_growth_radius' => $worldAndMap['initial_island_growth_radius'],
    'initial_island_reservation_radius' => $worldAndMap['initial_island_reservation_radius'],
    'initial_island_growth_steps' => $worldAndMap['initial_island_growth_steps'],
    'development_plan_quantity' => $commandsAndProduction['development_plan_quantity'],
    'initial_island_minimum_shallow_cells' => $worldAndMap['initial_island_minimum_shallow_cells'],
    'base_money_capacity' => $economyAndResources['base_money_capacity'],
    'base_food_capacity_tons' => $economyAndResources['base_food_capacity_tons'],
    'inventory_sale_rates' => $economyAndResources['inventory_sale_rates'],
    'turn_processing' => [
        'automatic_finance_money' => $turnPipeline['turn_processing']['automatic_finance_money'],
        'food' => $turnPipeline['turn_processing']['food'],
        'workforce' => $turnPipeline['turn_processing']['workforce'],
        'settlement' => $turnPipeline['turn_processing']['settlement'],
        'famine' => $turnPipeline['turn_processing']['famine'],
        'riot' => $turnPipeline['turn_processing']['riot'],
        'command_random_effects' => $terrainAndDisasters['turn_processing']['command_random_effects'],
        'sale_policy' => $turnPipeline['turn_processing']['sale_policy'],
        'disasters' => $terrainAndDisasters['turn_processing']['disasters'],
        'oil_field' => $terrainAndDisasters['turn_processing']['oil_field'],
        'resource_sale_phase' => $turnPipeline['turn_processing']['resource_sale_phase'],
        'territory_influence' => $turnPipeline['turn_processing']['territory_influence'],
    ],
    'capital_growth_maximum_population' => $terrainAndDisasters['capital_growth_maximum_population'],
    'capital_damage_percentages' => $terrainAndDisasters['capital_damage_percentages'],
    'resource_capacities' => $economyAndResources['resource_capacities'],
    'resource_capacity_overflow' => $economyAndResources['resource_capacity_overflow'],
    'monster_definitions' => $monstersAndMilitary['monster_definitions'],
    'monster_system' => $monstersAndMilitary['monster_system'],
    'capital_relocation_cost_money' => $worldAndMap['capital_relocation_cost_money'],
    'military' => $monstersAndMilitary['military'],
    'territory_transfer' => $worldAndMap['territory_transfer'],
    'secretary' => $secretary['secretary'],
    'trading_post' => $tradingPost['trading_post'],
    'turn_resolution' => $turnPipeline['turn_resolution'],
];
