<?php

$kingdomEnemy = static function (
    string $label,
    array $stats,
    int $maxHp,
    int $physicalDefense,
    int $magicalDefense,
    int $weaponPower,
    string $category = 'physical',
    array $skills = [],
    array $aiRules = [],
    array $modifiers = [],
    int $normalPotencyBps = 7_000,
): array {
    $primaryStat = $category === 'miracle' ? 'spirit' : 'might';

    return [
        'label' => $label,
        'boss' => false,
        'base_stats' => $stats,
        'max_hp' => $maxHp,
        'physical_defense' => $physicalDefense,
        'magical_defense' => $magicalDefense,
        'weapon_power' => $weaponPower,
        'normal_attack' => [
            'type' => 'damage', 'category' => $category, 'potency_bps' => $normalPotencyBps,
            'stat_coefficients' => [$primaryStat => 10_000], 'weapon_coefficient_bps' => 10_000,
            'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1,
        ],
        'skills' => $skills,
        'ai_rules' => $aiRules === []
            ? [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']]
            : $aiRules,
        'modifiers' => $modifiers,
    ];
};

$attack = [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']];
$guardThenAttack = [
    ['conditions' => [['type' => 'round_modulo', 'modulo' => 4, 'equals' => 0]], 'action' => 'defend'],
    ...$attack,
];
$telegraphThenHeavy = [
    ['conditions' => [['type' => 'self_has_status', 'status' => 'telegraph']], 'action' => 'skill:pressure_heavy'],
    ['conditions' => [['type' => 'round_modulo', 'modulo' => 3, 'equals' => 2]], 'action' => 'skill:enemy_telegraph'],
    ...$attack,
];
$healer = [
    ['conditions' => [['type' => 'own_hp_lte', 'percent' => 55]], 'action' => 'skill:enemy_mending_prayer'],
    ['conditions' => [['type' => 'always']], 'action' => 'skill:enemy_holy_bolt'],
];
$shiningKingdomEncounters = [
    'kingdom_gate_shield' => ['label' => '城門の盾兵', 'weight' => 900, 'xp' => 650, 'shards' => 175, 'drop_profile' => 'shining_kingdom', 'item_level_min' => 91, 'item_level_max' => 100, 'enemy' => $kingdomEnemy('城門の盾兵', ['vitality' => 40, 'might' => 26, 'finesse' => 8, 'spirit' => 16, 'agility' => 10], 7500, 450, 340, 2880, aiRules: $guardThenAttack)],
    'kingdom_guard' => ['label' => '王都の衛兵', 'weight' => 900, 'xp' => 680, 'shards' => 185, 'drop_profile' => 'shining_kingdom', 'item_level_min' => 91, 'item_level_max' => 100, 'enemy' => $kingdomEnemy('王都の衛兵', ['vitality' => 28, 'might' => 34, 'finesse' => 18, 'spirit' => 10, 'agility' => 10], 6000, 350, 310, 3240, aiRules: $guardThenAttack)],
    'kingdom_crossbow' => ['label' => '城壁の弩兵', 'weight' => 900, 'xp' => 710, 'shards' => 195, 'drop_profile' => 'shining_kingdom', 'item_level_min' => 91, 'item_level_max' => 100, 'enemy' => $kingdomEnemy('城壁の弩兵', ['vitality' => 18, 'might' => 28, 'finesse' => 38, 'spirit' => 6, 'agility' => 10], 5000, 290, 280, 4140, aiRules: $guardThenAttack)],
    'kingdom_healer' => ['label' => '王城の施療師', 'weight' => 900, 'xp' => 740, 'shards' => 205, 'drop_profile' => 'shining_kingdom', 'item_level_min' => 91, 'item_level_max' => 100, 'enemy' => $kingdomEnemy('王城の施療師', ['vitality' => 18, 'might' => 6, 'finesse' => 16, 'spirit' => 50, 'agility' => 10], 5300, 300, 380, 3240, 'miracle', ['enemy_mending_prayer', 'enemy_holy_bolt'], $healer)],
    'kingdom_ice_mage' => ['label' => '宮廷の氷術師', 'weight' => 900, 'xp' => 770, 'shards' => 215, 'drop_profile' => 'shining_kingdom', 'item_level_min' => 91, 'item_level_max' => 100, 'enemy' => $kingdomEnemy('宮廷の氷術師', ['vitality' => 18, 'might' => 5, 'finesse' => 17, 'spirit' => 50, 'agility' => 10], 5600, 300, 410, 3420, 'miracle', ['enemy_holy_bolt'], $guardThenAttack)],
    'kingdom_drummer' => ['label' => '王旗の鼓手', 'weight' => 900, 'xp' => 800, 'shards' => 225, 'drop_profile' => 'shining_kingdom', 'item_level_min' => 91, 'item_level_max' => 100, 'enemy' => $kingdomEnemy('王旗の鼓手', ['vitality' => 25, 'might' => 30, 'finesse' => 20, 'spirit' => 15, 'agility' => 10], 5500, 310, 310, 3060)],
    'kingdom_lancer' => ['label' => '王都の槍兵', 'weight' => 634, 'xp' => 835, 'shards' => 230, 'drop_profile' => 'shining_kingdom', 'item_level_min' => 101, 'item_level_max' => 110, 'enemy' => $kingdomEnemy('王都の槍兵', ['vitality' => 24, 'might' => 40, 'finesse' => 18, 'spirit' => 8, 'agility' => 10], 5400, 310, 290, 3780, skills: ['pressure_heavy', 'enemy_telegraph'], aiRules: $telegraphThenHeavy)],
    'kingdom_executioner' => ['label' => '王国の執行官', 'weight' => 634, 'xp' => 865, 'shards' => 235, 'drop_profile' => 'shining_kingdom', 'item_level_min' => 101, 'item_level_max' => 110, 'enemy' => $kingdomEnemy('王国の執行官', ['vitality' => 26, 'might' => 42, 'finesse' => 12, 'spirit' => 10, 'agility' => 10], 5700, 330, 310, 3960, skills: ['pressure_heavy', 'enemy_telegraph'], aiRules: $telegraphThenHeavy)],
    'kingdom_barrier_mage' => ['label' => '宮廷の結界師', 'weight' => 633, 'xp' => 895, 'shards' => 240, 'drop_profile' => 'shining_kingdom', 'item_level_min' => 101, 'item_level_max' => 110, 'enemy' => $kingdomEnemy('宮廷の結界師', ['vitality' => 25, 'might' => 5, 'finesse' => 10, 'spirit' => 50, 'agility' => 10], 6400, 310, 430, 3060, 'miracle', ['enemy_holy_bolt'], $guardThenAttack)],
    'kingdom_priest' => ['label' => '聖堂の司祭', 'weight' => 633, 'xp' => 925, 'shards' => 245, 'drop_profile' => 'shining_kingdom', 'item_level_min' => 101, 'item_level_max' => 110, 'enemy' => $kingdomEnemy('聖堂の司祭', ['vitality' => 20, 'might' => 5, 'finesse' => 15, 'spirit' => 50, 'agility' => 10], 5700, 290, 440, 3240, 'miracle', ['enemy_mending_prayer', 'enemy_holy_bolt'], $healer)],
    'kingdom_musketeer' => ['label' => '王立銃士', 'weight' => 633, 'xp' => 955, 'shards' => 250, 'drop_profile' => 'shining_kingdom', 'item_level_min' => 101, 'item_level_max' => 110, 'enemy' => $kingdomEnemy('王立銃士', ['vitality' => 18, 'might' => 28, 'finesse' => 44, 'spirit' => 4, 'agility' => 6], 5100, 300, 290, 4500, skills: ['pressure_heavy', 'enemy_telegraph'], aiRules: $telegraphThenHeavy)],
    'kingdom_fire_mage' => ['label' => '宮廷の火術師', 'weight' => 633, 'xp' => 985, 'shards' => 264, 'drop_profile' => 'shining_kingdom', 'item_level_min' => 101, 'item_level_max' => 110, 'enemy' => $kingdomEnemy('宮廷の火術師', ['vitality' => 16, 'might' => 4, 'finesse' => 16, 'spirit' => 54, 'agility' => 10], 5200, 270, 390, 3780, 'miracle', ['enemy_holy_bolt'], $attack)],
    'kingdom_duelist' => ['label' => '近衛の決闘士', 'weight' => 400, 'xp' => 890, 'shards' => 244, 'drop_profile' => 'shining_kingdom', 'item_level_min' => 111, 'item_level_max' => 119, 'enemy' => $kingdomEnemy('近衛の決闘士', ['vitality' => 24, 'might' => 48, 'finesse' => 18, 'spirit' => 5, 'agility' => 5], 6500, 350, 330, 7200, skills: ['enemy_counter_stance', 'pressure_heavy', 'enemy_telegraph'], aiRules: [['conditions' => [['type' => 'self_lacks_status', 'status' => 'aegis']], 'action' => 'skill:enemy_counter_stance'], ...$telegraphThenHeavy])],
    'kingdom_archmage' => ['label' => '宮廷の大魔術師', 'weight' => 400, 'xp' => 938, 'shards' => 253, 'drop_profile' => 'shining_kingdom', 'item_level_min' => 111, 'item_level_max' => 119, 'enemy' => $kingdomEnemy('宮廷の大魔術師', ['vitality' => 20, 'might' => 4, 'finesse' => 10, 'spirit' => 60, 'agility' => 6], 6800, 320, 480, 6075, 'miracle', ['radiant_judgment', 'enemy_telegraph'], [['conditions' => [['type' => 'round_modulo', 'modulo' => 3, 'equals' => 2]], 'action' => 'skill:enemy_telegraph'], ['conditions' => [['type' => 'self_has_status', 'status' => 'telegraph']], 'action' => 'skill:radiant_judgment'], ...$attack])],
];
$shiningNobleEncounter = [
    'label' => '輝衣の宮廷貴族', 'xp' => 4200, 'shards' => 400,
    'drop_profile' => 'shining_kingdom', 'item_level_min' => 120, 'item_level_max' => 120,
    'enemy' => $kingdomEnemy(
        '輝衣の宮廷貴族',
        ['vitality' => 55, 'might' => 5, 'finesse' => 10, 'spirit' => 25, 'agility' => 5],
        25_000, 700, 700, 5_000, skills: ['pressure_heavy'],
        aiRules: [['conditions' => [['type' => 'always']], 'action' => 'defend']],
        modifiers: ['outrage_chance_bps' => 100], normalPotencyBps: 100,
    ),
];

return [
    'schema_version' => 1,
    'growth_identity' => 'secretary-underground-growth-alpha-v1',
    'skill_tree_identity' => 'secretary-underground-skill-tree-alpha-v2',
    'initial_skill_points' => 20,
    // Player-facing build guidance only. Combat, healing, AI, requirements, and simulation must not read it.
    'player_skill_guidance' => [
        'precision_cut' => ['recommended_stats' => ['might', 'finesse']],
        'sweeping_cut' => ['recommended_stats' => ['might', 'finesse']],
        'dagger_flurry' => ['recommended_stats' => ['might', 'finesse']],
        'armor_break_strike' => ['recommended_stats' => ['might', 'finesse']],
        'disarming_cut' => ['recommended_stats' => ['might', 'finesse']],
        'severing_bleed' => ['recommended_stats' => ['might', 'finesse']],
        'iaido_cut' => ['recommended_stats' => ['might', 'finesse']],
        'whirlwind' => ['recommended_stats' => ['might', 'finesse']],
        'executioner_cut' => ['recommended_stats' => ['might', 'finesse']],
        'quick_stab' => ['recommended_stats' => ['might', 'finesse']],
        'shield_bash' => ['recommended_stats' => ['vitality', 'might']],
        'rallying_cry' => ['recommended_stats' => ['vitality', 'might']],
        'counter_stance' => ['recommended_stats' => ['vitality', 'might']],
        'renewing_guard' => ['recommended_stats' => ['vitality', 'spirit']],
        'protective_oath' => ['recommended_stats' => ['vitality', 'might']],
        'bulwark_strike' => ['recommended_stats' => ['vitality', 'might']],
        'fortress' => ['recommended_stats' => ['vitality', 'might']],
        'sundering_shield' => ['recommended_stats' => ['vitality', 'might']],
        'unbroken_retort' => ['recommended_stats' => ['vitality', 'might']],
        'holy_bolt' => ['recommended_stats' => ['spirit']],
        'mending_prayer' => ['recommended_stats' => ['spirit']],
        'lucid_dream' => ['recommended_stats' => []],
        'regeneration' => ['recommended_stats' => ['spirit']],
        'holy_nova' => ['recommended_stats' => ['spirit']],
        'crystal_cycle' => ['recommended_stats' => []],
        'crystal_aegis' => ['recommended_stats' => ['spirit']],
        'cleansing_wave' => ['recommended_stats' => ['spirit']],
        'holy_lance' => ['recommended_stats' => ['spirit']],
        'resurrection' => ['recommended_stats' => []],
        'heart_of_mercy' => ['recommended_stats' => ['spirit']],
    ],
    'growth_paths' => [
        'martial_red' => [
            'label' => '戦技',
            'color' => 'red',
            'build_key' => 'pure_attacker',
            'description' => [
                '戦技とは立ちはだかる障害を素早く葬り去る技術である。',
                '陰に潜み、暗殺に特化したエルフの物語も少なくない。',
                '自身が傷つくよりも早く、相手が倒れたらそれでよい。',
                '勝利へと素早く辿り着きたいなら、このスキルを選べば良いだろう。',
            ],
            'natural_growth' => ['vitality' => 1, 'might' => 2, 'finesse' => 1, 'spirit' => 1, 'agility' => 0],
            'unspent_stp_per_level' => 5,
        ],
        'guardianship_blue' => [
            'label' => '護身',
            'color' => 'blue',
            'build_key' => 'pure_tank',
            'description' => [
                '護身術は要人の嗜みである。当然、箱庭の全てを管理する秘書もまた例外ではない。',
                '優れた五感であらゆる危機を察知し、敵をその威圧を以て制圧する。',
                'なによりその頑丈さを以て、仲間の前に立つことで真価を発揮することだろう。',
                '粘り強い戦いを求めるならば、このスキルを選べば良いだろう。',
            ],
            'natural_growth' => ['vitality' => 2, 'might' => 1, 'finesse' => 1, 'spirit' => 1, 'agility' => 0],
            'unspent_stp_per_level' => 5,
        ],
        'blessing_green' => [
            'label' => '祝福',
            'color' => 'green',
            'build_key' => 'pure_healer',
            'description' => [
                'エルフは自然との調和性が高く、輝石に秘められた力とも強く共鳴する。',
                '傷を癒やし、身を守る障壁を生み、時にはその光を敵へと向ける。',
                '生き残るための手段を多く持ち、長い戦いほどその力を発揮することだろう。',
                '癒やしと輝石の力を自在に操りたいなら、このスキルを選べば良いだろう。',
            ],
            'natural_growth' => ['vitality' => 1, 'might' => 1, 'finesse' => 1, 'spirit' => 2, 'agility' => 0],
            'unspent_stp_per_level' => 5,
        ],
        'free_black' => [
            'label' => '自由',
            'color' => 'black',
            'build_key' => 'balanced',
            'description' => [
                '全ての輝石を受け取る。非常に欲深く最も効果的な選択肢ではあるが、秘書一人が使える魔力は限られている。',
                '本当に戦闘に最適な能力の振り分けが何なのか、全て自分が決める必要がある。',
                '全て手探りで進めることは茨の道であることは間違いないが、複数の能力を自在に組み合わせ使いこなすことができるだろう。',
                '手動で割り振れるSTPが少し高い。',
            ],
            'natural_growth' => ['vitality' => 1, 'might' => 1, 'finesse' => 1, 'spirit' => 1, 'agility' => 0],
            'unspent_stp_per_level' => 6,
        ],
    ],
    'exploration' => [
        'identity' => 'secretary-underground-exploration-alpha-v2',
        'default_hunting_ground_key' => 'shallow_caves',
        'max_rounds' => 100,
        'starter_weapon' => [
            'key' => 'starter_knife',
            'label' => '護身用ナイフ',
            'item_level' => 1,
            'rarity' => 'common',
            'weapon_style' => 'dagger',
            'weapon_power' => 24,
            'physical_defense' => 0,
            'magical_defense' => 0,
            'max_hp' => 0,
            'stats' => ['vitality' => 1, 'might' => 1, 'finesse' => 1, 'spirit' => 1, 'agility' => 1],
            'modifiers' => [],
            'affixes' => [],
            'unique_effect' => null,
        ],
        'player_ai_rules' => [
            ['conditions' => [['type' => 'enemy_telegraph']], 'action' => 'defend'],
            ['conditions' => [['type' => 'own_hp_lte', 'percent' => 20]], 'action' => 'defend'],
            ['conditions' => [['type' => 'always']], 'action' => 'normal_attack'],
        ],
        'player_skill_ai_rules' => [
            ['conditions' => [['type' => 'always']], 'action' => 'skill:quick_stab'],
            ['conditions' => [['type' => 'always']], 'action' => 'skill:resurrection', 'target' => 'fallen_ally'],
            ['conditions' => [['type' => 'ally_hp_lte', 'percent' => 55]], 'action' => 'skill:mending_prayer'],
            ['conditions' => [['type' => 'own_hp_lte', 'percent' => 55]], 'action' => 'skill:renewing_guard'],
            ['conditions' => [['type' => 'own_mp_lte', 'percent' => 75], ['type' => 'self_lacks_status', 'status' => 'lucid_recovery']], 'action' => 'skill:lucid_dream'],
            ['conditions' => [['type' => 'own_mp_lte', 'percent' => 35]], 'action' => 'skill:crystal_cycle'],
            ['conditions' => [['type' => 'role_stacks_gte', 'status' => 'grace', 'stacks' => 3]], 'action' => 'skill:heart_of_mercy'],
            ['conditions' => [['type' => 'always']], 'action' => 'skill:cleansing_wave', 'target' => 'debuffed_ally'],
            ['conditions' => [['type' => 'ally_hp_lte', 'percent' => 80]], 'action' => 'skill:regeneration'],
            ['conditions' => [['type' => 'self_lacks_status', 'status' => 'protective_guard']], 'action' => 'skill:fortress'],
            ['conditions' => [['type' => 'ally_hp_lte', 'percent' => 75]], 'action' => 'skill:protective_oath'],
            ['conditions' => [['type' => 'own_hp_lte', 'percent' => 70], ['type' => 'self_lacks_status', 'status' => 'aegis']], 'action' => 'skill:crystal_aegis'],
            ['conditions' => [['type' => 'always']], 'action' => 'skill:rallying_cry'],
            ['conditions' => [['type' => 'enemy_telegraph']], 'action' => 'skill:counter_stance'],
            ['conditions' => [['type' => 'own_hp_lte', 'percent' => 95], ['type' => 'self_lacks_status', 'status' => 'aegis']], 'action' => 'skill:counter_stance'],
            ['conditions' => [['type' => 'always']], 'action' => 'skill:unbroken_retort'],
            ['conditions' => [['type' => 'always']], 'action' => 'skill:executioner_cut'],
            ['conditions' => [['type' => 'always']], 'action' => 'skill:iaido_cut'],
            ['conditions' => [['type' => 'always']], 'action' => 'skill:armor_break_strike'],
            ['conditions' => [['type' => 'always']], 'action' => 'skill:severing_bleed'],
            ['conditions' => [['type' => 'always']], 'action' => 'skill:whirlwind'],
            ['conditions' => [['type' => 'always']], 'action' => 'skill:dagger_flurry'],
            ['conditions' => [['type' => 'always']], 'action' => 'skill:disarming_cut'],
            ['conditions' => [['type' => 'always']], 'action' => 'skill:sweeping_cut'],
            ['conditions' => [['type' => 'always']], 'action' => 'skill:holy_lance'],
            ['conditions' => [['type' => 'always']], 'action' => 'skill:holy_nova'],
            ['conditions' => [['type' => 'always']], 'action' => 'skill:sundering_shield'],
            ['conditions' => [['type' => 'always']], 'action' => 'skill:bulwark_strike'],
            ['conditions' => [['type' => 'always']], 'action' => 'skill:shield_bash'],
            ['conditions' => [['type' => 'always']], 'action' => 'skill:precision_cut'],
            ['conditions' => [['type' => 'always']], 'action' => 'skill:holy_bolt'],
        ],
        'drop' => [
            'identity' => 'secretary-underground-exploration-drop-alpha-v1',
            'profiles' => [
                'standard' => [
                    'presence_bps' => 2006,
                    'rarity_weights' => ['common' => 9118, 'uncommon' => 683, 'rare' => 194, 'epic' => 5],
                ],
                'elite' => [
                    'presence_bps' => 3815,
                    'rarity_weights' => ['common' => 7864, 'uncommon' => 1573, 'rare' => 524, 'epic' => 39],
                ],
                'rare' => [
                    'presence_bps' => 10000,
                    'rarity_weights' => ['common' => 5000, 'uncommon' => 3000, 'rare' => 1500, 'epic' => 500],
                ],
                'shining_kingdom' => [
                    'presence_bps' => 2610,
                    'rarity_weights' => ['common' => 8429, 'uncommon' => 1149, 'rare' => 383, 'epic' => 39],
                ],
                'shining_kingdom_vault' => [
                    'presence_bps' => 10000,
                    'rarity_weights' => ['common' => 0, 'uncommon' => 7317, 'rare' => 2439, 'epic' => 244],
                ],
                'trial2_shallow' => [
                    'presence_bps' => 5500,
                    'rarity_weights' => ['common' => 6500, 'uncommon' => 2500, 'rare' => 900, 'epic' => 100],
                ],
                'trial2_middle' => [
                    'presence_bps' => 6500,
                    'rarity_weights' => ['common' => 5000, 'uncommon' => 3200, 'rare' => 1500, 'epic' => 300],
                ],
                'trial2_deep' => [
                    'presence_bps' => 8000,
                    'rarity_weights' => ['common' => 3500, 'uncommon' => 3500, 'rare' => 2400, 'epic' => 600],
                ],
            ],
            'category_weights' => ['weapon' => 2000, 'armor' => 2000, 'accessory' => 6000],
            'weapon_styles' => ['dagger', 'rapier', 'longsword', 'crystal_staff'],
            'accessory_main_stats' => ['vitality', 'might', 'finesse', 'spirit', 'agility'],
        ],
        'grounds' => [
            'shallow_caves' => [
                'content_identity' => 'secretary-underground-exploration-alpha-v1',
                'name' => '浅い洞窟',
                'required_trial_key' => null,
                'enemy_count_by_party_size' => [1 => 1, 2 => 2, 3 => 3, 4 => 4],
                'item_level_min' => 5,
                'item_level_max' => 30,
                'encounters' => [
                    'subterranean_rat' => [
                        'label' => '地底鼠', 'weight' => 2500, 'xp' => 36, 'shards' => 10,
                        'drop_profile' => 'standard', 'item_level_min' => 5, 'item_level_max' => 15,
                        'enemy' => [
                            'label' => '地底鼠', 'boss' => false,
                            'base_stats' => ['vitality' => 15, 'might' => 18, 'finesse' => 18, 'spirit' => 12, 'agility' => 37],
                            'max_hp' => 260, 'physical_defense' => 45, 'magical_defense' => 40, 'weapon_power' => 16,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 6500, 'stat_coefficients' => ['might' => 7000, 'finesse' => 3000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => [], 'ai_rules' => [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']], 'modifiers' => [],
                        ],
                    ],
                    'cave_vermin' => [
                        'label' => '洞窟蟲', 'weight' => 2500, 'xp' => 40, 'shards' => 12,
                        'drop_profile' => 'standard', 'item_level_min' => 5, 'item_level_max' => 15,
                        'enemy' => [
                            'label' => '洞窟蟲', 'boss' => false,
                            'base_stats' => ['vitality' => 22, 'might' => 22, 'finesse' => 18, 'spirit' => 18, 'agility' => 20],
                            'max_hp' => 340, 'physical_defense' => 55, 'magical_defense' => 50, 'weapon_power' => 18,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 7000, 'stat_coefficients' => ['might' => 7000, 'finesse' => 3000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => [], 'ai_rules' => [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']], 'modifiers' => [],
                        ],
                    ],
                    'corrosive_slime' => [
                        'label' => '腐食スライム', 'weight' => 2000, 'xp' => 46, 'shards' => 14,
                        'drop_profile' => 'standard', 'item_level_min' => 5, 'item_level_max' => 15,
                        'enemy' => [
                            'label' => '腐食スライム', 'boss' => false,
                            'base_stats' => ['vitality' => 38, 'might' => 18, 'finesse' => 12, 'spirit' => 22, 'agility' => 10],
                            'max_hp' => 520, 'physical_defense' => 65, 'magical_defense' => 60, 'weapon_power' => 17,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 6500, 'stat_coefficients' => ['might' => 7000, 'finesse' => 3000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => [], 'ai_rules' => [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']], 'modifiers' => [],
                        ],
                    ],
                    'regenerating_mass' => [
                        'label' => '再生肉塊', 'weight' => 1000, 'xp' => 52, 'shards' => 16,
                        'drop_profile' => 'elite', 'item_level_min' => 10, 'item_level_max' => 25,
                        'enemy' => [
                            'label' => '再生肉塊', 'boss' => false,
                            'base_stats' => ['vitality' => 34, 'might' => 26, 'finesse' => 14, 'spirit' => 16, 'agility' => 10],
                            'max_hp' => 500, 'physical_defense' => 60, 'magical_defense' => 55, 'weapon_power' => 25,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 7000, 'stat_coefficients' => ['might' => 7000, 'finesse' => 3000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => [], 'ai_rules' => [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']],
                            'modifiers' => ['self_regeneration_target_hp_bps' => 150],
                        ],
                    ],
                    'fanatic' => [
                        'label' => '狂信者', 'weight' => 1000, 'xp' => 58, 'shards' => 18,
                        'drop_profile' => 'elite', 'item_level_min' => 10, 'item_level_max' => 25,
                        'enemy' => [
                            'label' => '狂信者', 'boss' => false,
                            'base_stats' => ['vitality' => 24, 'might' => 34, 'finesse' => 18, 'spirit' => 12, 'agility' => 12],
                            'max_hp' => 450, 'physical_defense' => 60, 'magical_defense' => 55, 'weapon_power' => 28,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 6500, 'stat_coefficients' => ['might' => 7000, 'finesse' => 3000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => ['pressure_heavy', 'enemy_telegraph'],
                            'ai_rules' => [
                                ['conditions' => [['type' => 'self_has_status', 'status' => 'telegraph']], 'action' => 'skill:pressure_heavy'],
                                ['conditions' => [['type' => 'round_modulo', 'modulo' => 3, 'equals' => 2]], 'action' => 'skill:enemy_telegraph'],
                                ['conditions' => [['type' => 'always']], 'action' => 'normal_attack'],
                            ],
                            'modifiers' => [],
                        ],
                    ],
                    'lost_shadow' => [
                        'label' => '迷い人の影', 'weight' => 900, 'xp' => 72, 'shards' => 22,
                        'drop_profile' => 'elite', 'item_level_min' => 20, 'item_level_max' => 30,
                        'enemy' => [
                            'label' => '迷い人の影', 'boss' => false,
                            'base_stats' => ['vitality' => 28, 'might' => 34, 'finesse' => 20, 'spirit' => 2, 'agility' => 16],
                            'max_hp' => 1000, 'physical_defense' => 110, 'magical_defense' => 100, 'weapon_power' => 44,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 10500, 'stat_coefficients' => ['might' => 7000, 'finesse' => 3000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => true, 'dodgeable' => true, 'hits' => 1],
                            'skills' => [], 'ai_rules' => [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']], 'modifiers' => [],
                        ],
                    ],
                    'crystal_bug' => [
                        'label' => '輝石虫', 'weight' => 100, 'xp' => 1150, 'shards' => 0,
                        'drop_profile' => 'rare', 'item_level_min' => 25, 'item_level_max' => 30,
                        'enemy' => [
                            'label' => '輝石虫', 'boss' => false,
                            'base_stats' => ['vitality' => 20, 'might' => 5, 'finesse' => 5, 'spirit' => 60, 'agility' => 10],
                            'max_hp' => 1, 'physical_defense' => 0, 'magical_defense' => 0, 'weapon_power' => 1,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 1000, 'stat_coefficients' => ['might' => 10000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => [], 'ai_rules' => [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']],
                            'modifiers' => ['complete_guard_chance_bps' => 9900],
                        ],
                    ],
                ],
            ],
            'black_crystal_cave' => [
                'content_identity' => 'secretary-underground-black-crystal-cave-alpha-v1',
                'name' => '黒晶洞',
                'required_trial_key' => 'trial_01',
                'enemy_count_by_party_size' => [1 => 1, 2 => 2, 3 => 3, 4 => 4],
                'item_level_min' => 30,
                'item_level_max' => 60,
                'encounters' => [
                    'black_crystal_bat' => [
                        'label' => '黒晶蝙蝠', 'weight' => 2500, 'xp' => 145, 'shards' => 37,
                        'drop_profile' => 'standard', 'item_level_min' => 30, 'item_level_max' => 38,
                        'enemy' => [
                            'label' => '黒晶蝙蝠', 'boss' => false,
                            'base_stats' => ['vitality' => 18, 'might' => 26, 'finesse' => 22, 'spirit' => 8, 'agility' => 26],
                            'max_hp' => 1400, 'physical_defense' => 100, 'magical_defense' => 90, 'weapon_power' => 125,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 6500, 'stat_coefficients' => ['might' => 7000, 'finesse' => 3000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => [], 'ai_rules' => [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']], 'modifiers' => [],
                        ],
                    ],
                    'black_crystal_beast' => [
                        'label' => '黒晶獣', 'weight' => 2000, 'xp' => 160, 'shards' => 42,
                        'drop_profile' => 'standard', 'item_level_min' => 30, 'item_level_max' => 40,
                        'enemy' => [
                            'label' => '黒晶獣', 'boss' => false,
                            'base_stats' => ['vitality' => 24, 'might' => 32, 'finesse' => 18, 'spirit' => 12, 'agility' => 14],
                            'max_hp' => 1650, 'physical_defense' => 125, 'magical_defense' => 110, 'weapon_power' => 135,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 7000, 'stat_coefficients' => ['might' => 7000, 'finesse' => 3000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => [], 'ai_rules' => [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']], 'modifiers' => [],
                        ],
                    ],
                    'crystal_shell_bug' => [
                        'label' => '晶殻蟲', 'weight' => 1500, 'xp' => 170, 'shards' => 47,
                        'drop_profile' => 'standard', 'item_level_min' => 32, 'item_level_max' => 40,
                        'enemy' => [
                            'label' => '晶殻蟲', 'boss' => false,
                            'base_stats' => ['vitality' => 40, 'might' => 22, 'finesse' => 8, 'spirit' => 20, 'agility' => 10],
                            'max_hp' => 1950, 'physical_defense' => 200, 'magical_defense' => 125, 'weapon_power' => 125,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 6000, 'stat_coefficients' => ['might' => 7000, 'finesse' => 3000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => [], 'ai_rules' => [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']], 'modifiers' => [],
                        ],
                    ],
                    'black_crystal_mage' => [
                        'label' => '黒晶術師', 'weight' => 1000, 'xp' => 185, 'shards' => 55,
                        'drop_profile' => 'standard', 'item_level_min' => 34, 'item_level_max' => 40,
                        'enemy' => [
                            'label' => '黒晶術師', 'boss' => false,
                            'base_stats' => ['vitality' => 18, 'might' => 10, 'finesse' => 20, 'spirit' => 42, 'agility' => 10],
                            'max_hp' => 1550, 'physical_defense' => 100, 'magical_defense' => 190, 'weapon_power' => 140,
                            'normal_attack' => ['type' => 'damage', 'category' => 'miracle', 'potency_bps' => 7000, 'stat_coefficients' => ['spirit' => 10000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => [], 'ai_rules' => [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']], 'modifiers' => [],
                        ],
                    ],
                    'crystal_berserker' => [
                        'label' => '破晶の狂戦士', 'weight' => 1200, 'xp' => 280, 'shards' => 78,
                        'drop_profile' => 'elite', 'item_level_min' => 35, 'item_level_max' => 47,
                        'enemy' => [
                            'label' => '破晶の狂戦士', 'boss' => false,
                            'base_stats' => ['vitality' => 30, 'might' => 40, 'finesse' => 10, 'spirit' => 10, 'agility' => 10],
                            'max_hp' => 2300, 'physical_defense' => 165, 'magical_defense' => 140, 'weapon_power' => 170,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 6500, 'stat_coefficients' => ['might' => 10000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => ['pressure_heavy', 'enemy_telegraph'],
                            'ai_rules' => [
                                ['conditions' => [['type' => 'self_has_status', 'status' => 'telegraph']], 'action' => 'skill:pressure_heavy'],
                                ['conditions' => [['type' => 'round_modulo', 'modulo' => 3, 'equals' => 2]], 'action' => 'skill:enemy_telegraph'],
                                ['conditions' => [['type' => 'always']], 'action' => 'normal_attack'],
                            ],
                            'modifiers' => [],
                        ],
                    ],
                    'black_crystal_regenerator' => [
                        'label' => '黒晶再生体', 'weight' => 800, 'xp' => 330, 'shards' => 98,
                        'drop_profile' => 'elite', 'item_level_min' => 40, 'item_level_max' => 50,
                        'enemy' => [
                            'label' => '黒晶再生体', 'boss' => false,
                            'base_stats' => ['vitality' => 42, 'might' => 22, 'finesse' => 8, 'spirit' => 18, 'agility' => 10],
                            'max_hp' => 2800, 'physical_defense' => 180, 'magical_defense' => 165, 'weapon_power' => 160,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 7000, 'stat_coefficients' => ['might' => 7000, 'finesse' => 3000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => [], 'ai_rules' => [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']],
                            'modifiers' => ['self_regeneration_target_hp_bps' => 150],
                        ],
                    ],
                    'black_crystal_warden' => [
                        'label' => '黒晶の番人', 'weight' => 900, 'xp' => 600, 'shards' => 157,
                        'drop_profile' => 'elite', 'item_level_min' => 45, 'item_level_max' => 60,
                        'enemy' => [
                            'label' => '黒晶の番人', 'boss' => false,
                            'base_stats' => ['vitality' => 36, 'might' => 34, 'finesse' => 10, 'spirit' => 10, 'agility' => 10],
                            'max_hp' => 3700, 'physical_defense' => 240, 'magical_defense' => 215, 'weapon_power' => 215,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 7000, 'stat_coefficients' => ['might' => 10000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => ['pressure_heavy', 'enemy_telegraph'],
                            'ai_rules' => [
                                ['conditions' => [['type' => 'self_has_status', 'status' => 'telegraph']], 'action' => 'skill:pressure_heavy'],
                                ['conditions' => [['type' => 'round_modulo', 'modulo' => 4, 'equals' => 3]], 'action' => 'skill:enemy_telegraph'],
                                ['conditions' => [['type' => 'always']], 'action' => 'normal_attack'],
                            ],
                            'modifiers' => ['damage_taken_reduction_bps' => 300],
                        ],
                    ],
                    'black_crystal_bug' => [
                        'label' => '黒晶虫', 'weight' => 100, 'xp' => 1400, 'shards' => 0,
                        'drop_profile' => 'rare', 'item_level_min' => 50, 'item_level_max' => 60,
                        'enemy' => [
                            'label' => '黒晶虫', 'boss' => false,
                            'base_stats' => ['vitality' => 20, 'might' => 5, 'finesse' => 5, 'spirit' => 60, 'agility' => 10],
                            'max_hp' => 1, 'physical_defense' => 0, 'magical_defense' => 0, 'weapon_power' => 1,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 1000, 'stat_coefficients' => ['might' => 10000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => [], 'ai_rules' => [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']],
                            'modifiers' => ['complete_guard_chance_bps' => 9900],
                        ],
                    ],
                ],
            ],
            'shining_kingdom' => [
                'content_identity' => 'secretary-underground-shining-kingdom-v1',
                'name' => '輝きの王国',
                'kind' => 'hunting_ground',
                'required_trial_key' => 'trial_02',
                'enemy_count_by_party_size' => [1 => 1, 2 => 2, 3 => 3, 4 => 4],
                'item_level_min' => 91,
                'item_level_max' => 120,
                'rare_encounter' => ['key' => 'shining_court_noble', 'chance_bps' => 100, 'encounter' => $shiningNobleEncounter, 'distorted_stone_quantity' => 1],
                'key_reward' => ['normal_chance_bps' => 670, 'rare_quantity' => 1],
                'encounters' => $shiningKingdomEncounters,
            ],
            'shining_kingdom_vault' => [
                'content_identity' => 'secretary-underground-shining-kingdom-vault-v1',
                'name' => '輝きの王国の宝物庫',
                'kind' => 'vault',
                'required_trial_key' => 'trial_02',
                'enemy_count_by_party_size' => [1 => 1, 2 => 2, 3 => 3, 4 => 4],
                'item_level_min' => 91,
                'item_level_max' => 120,
                'rare_encounter' => ['key' => 'shining_court_noble', 'chance_bps' => 100, 'encounter' => $shiningNobleEncounter, 'distorted_stone_quantity' => 1],
                'entry_key_cost' => 1,
                'vault_base_g' => 222,
                'treasure_multiplier' => 20,
                'forced_drop_profile' => 'shining_kingdom_vault',
                'drop_tier_key' => 'shining_kingdom',
                'encounters' => $shiningKingdomEncounters,
            ],
        ],
    ],
    'shop' => [
        'inn' => ['cost_shards' => 10],
        'bank' => ['transfer_unit_shards' => 1000],
    ],
    'playtest' => [
        'identity' => 'secretary-underground-playtest-alpha-v1',
        'tier_key' => 'early',
        'notice' => 'α版の戦闘検証用完成形ビルドです。正式な育成・装備状態ではありません。',
        'builds' => [
            'pure_attacker' => ['description' => '戦技を中心に、短い戦闘で敵を倒す完成形ビルド。'],
            'pure_tank' => ['description' => 'guard・barrier・闘志・counterを組み合わせる護身型ビルド。'],
            'pure_healer' => ['description' => '回復・障壁・恩寵を使って長く戦う祝福型ビルド。'],
            'balanced' => ['description' => '戦技・護身・祝福を混ぜて対応する混成ビルド。'],
        ],
        'enemies' => [
            'depth_stalker' => [
                'label' => '深層追跡者',
                'description' => 'Lv1相当の完成形ビルドを確認する、通常の適正戦闘です。',
                'max_rounds' => 100,
            ],
            'pressure_construct' => [
                'label' => '予兆を放つ圧力試験体',
                'description' => '予告大技に対する防御判断と長期戦の挙動を確認します。',
                'max_rounds' => 100,
            ],
            'crystal_warden' => [
                'label' => '輝晶守護者',
                'description' => 'bossへのstatus・control変換と継戦能力を確認します。',
                'max_rounds' => 100,
            ],
        ],
    ],
    'otherworld' => [
        'minimum_level' => 100,
        'required_trial_key' => 'trial_02',
        'cooldown_seconds' => 600,
        'weapon_drop_chance_bps' => 1000,
        'max_rounds' => 80,
        // Initial tuning values; measured with a fixed four-member party, without party-size scaling.
        'stages' => [
            'bahamul_beginner_1' => ['name' => '黒竜バハムル・初級1', 'level' => 100, 'item_level' => 130, 'previous' => null, 'abyssal_roar' => false,
                'max_hp' => 42000, 'might' => 600, 'spirit' => 600, 'finesse' => 200, 'agility' => 80,
                'physical_defense' => 600, 'magical_defense' => 400, 'weapon_power' => 300, 'xp' => 10000, 'shards' => 10000],
            'bahamul_beginner_2' => ['name' => '黒竜バハムル・初級2', 'level' => 200, 'item_level' => 150, 'previous' => 'bahamul_beginner_1', 'abyssal_roar' => false,
                'max_hp' => 100000, 'might' => 1500, 'spirit' => 1500, 'finesse' => 450, 'agility' => 100,
                'physical_defense' => 1800, 'magical_defense' => 1400, 'weapon_power' => 700, 'xp' => 25000, 'shards' => 25000],
            'bahamul_beginner_3' => ['name' => '黒竜バハムル・初級3', 'level' => 400, 'item_level' => 180, 'previous' => 'bahamul_beginner_2', 'abyssal_roar' => false,
                'max_hp' => 140000, 'might' => 3100, 'spirit' => 3100, 'finesse' => 800, 'agility' => 150,
                'physical_defense' => 4800, 'magical_defense' => 3800, 'weapon_power' => 1600, 'xp' => 80000, 'shards' => 60000],
            'bahamul_intermediate_1' => ['name' => '黒竜バハムル・中級1', 'level' => 666, 'item_level' => 210, 'previous' => 'bahamul_beginner_3', 'abyssal_roar' => true,
                'max_hp' => 360000, 'might' => 12000, 'spirit' => 6000, 'finesse' => 1200, 'agility' => 220,
                'physical_defense' => 16000, 'magical_defense' => 9000, 'weapon_power' => 2600, 'xp' => 200000, 'shards' => 120000],
        ],
        'ultimate_hp_percent' => 40,
        'roar_hp_percent' => 50,
        'charged_attack' => ['trigger_skill' => 'bahamul_roar', 'countdown_rounds' => 5, 'skill' => 'bahamul_megaflare', 'status' => 'abyssal_roar'],
        'statuses' => [
            'abyssal_roar' => ['label' => '深淵の咆哮', 'disposition' => 'buff', 'duration_rounds' => 100,
                'stack_policy' => 'refresh', 'max_stacks' => 1, 'application_chance_bps' => 10000,
                'effects' => [['type' => 'damage_dealt_modifier', 'category' => 'all', 'action_key' => 'bahamul_megaflare', 'value_bps' => 70000]]],
        ],
        'skills' => [
            'bahamul_breath' => [
                'label' => '黒炎の息吹', 'node_key' => null, 'mp_cost' => 0, 'cooldown' => 0, 'required_weapon_styles' => [],
                'effects' => [['type' => 'damage', 'target' => 'enemy', 'target_scope' => 'all_enemies', 'category' => 'miracle',
                    'potency_bps' => 12000, 'stat_coefficients' => ['spirit' => 10000], 'weapon_coefficient_bps' => 10000,
                    'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => false, 'hits' => 1]],
            ],
            'bahamul_megaflare' => [
                'label' => 'メガフレア', 'node_key' => null, 'mp_cost' => 0, 'cooldown' => 10, 'required_weapon_styles' => [], 'consume_status' => 'telegraph',
                'effects' => [['type' => 'damage', 'target' => 'enemy', 'target_scope' => 'all_enemies', 'category' => 'miracle',
                    'potency_bps' => 50000, 'stat_coefficients' => ['spirit' => 10000], 'weapon_coefficient_bps' => 10000,
                    'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => false, 'hits' => 1]],
            ],
            'bahamul_roar' => [
                'label' => '深淵の咆哮', 'node_key' => null, 'mp_cost' => 0, 'cooldown' => 100, 'required_weapon_styles' => [],
                'effects' => [['type' => 'apply_status', 'target' => 'self', 'status' => 'abyssal_roar']],
            ],
        ],
    ],
    'guide_duel' => [
        'identity' => 'secretary-underground-guide-duel-v1',
        'key' => 'dream_queen',
        'required_ground' => 'shining_kingdom',
        'enemy' => [
            'label' => '夢の女王', 'boss' => true,
            'base_stats' => ['vitality' => 5500, 'might' => 5500, 'finesse' => 1300, 'spirit' => 1500, 'agility' => 200],
            'max_hp' => 351400, 'physical_defense' => 30000, 'magical_defense' => 12000, 'weapon_power' => 3000,
            'skills' => [], 'ai_rules' => [], 'modifiers' => [],
            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 10000,
                'stat_coefficients' => ['might' => 10000], 'weapon_coefficient_bps' => 10000, 'can_crit' => true, 'dodgeable' => true],
            'guide_duel' => [
                'identity' => 'secretary-underground-guide-duel-v1',
                'heal_per_round' => 1254, 'threshold_percent' => 25,
                'ultimate_name' => '雷迅月翔斬', 'ultimate_potency_bps' => 1000,
                'ultimate_min_hits' => 30, 'ultimate_max_hits' => 50,
                'area_name' => 'ミルキーウェイ', 'area_potency_bps' => 15000, 'area_chance_bps' => 2500,
                'opening_lines' => ['「私と戦うなら、全力を出す以外の選択肢は与えませんよ？」', '魔力の奔流が強制的に○○たちの肉体を作り変える……！'],
                'ultimate_opening_line' => '「私は魔王。故に本能があるのです……挑むものを返り討ちにして踏み躙るという本能がね！」',
                'ultimate_threshold_line' => '「いひひ……こんなに楽しい戦いも久しぶりです！　そうでしょう？　○○！」',
                'ultimate_description' => '突然案内人の姿が幾重にも映る——斬撃がどの方角から襲いかかるか予測できない！',
                'area_lines' => ['「ミルキーウェイ！」', '「天雷よ、降り注げ！」', '「滅びなさい！」', '「何度でも立ち上がってくださいな！」', '「唸りなさい、私のグラム！」'],
                'area_description' => '天の川の如き、大量の雷が全てを焼き払う——！',
                'defeated_line' => '「ああ、この輝きこそ、私は望んでいた——」',
            ],
        ],
        'challenge_lines' => ['「……」', '「どのような理由で武器を構えているのかはあえて尋ねませんが……」',
            '「いいでしょう。私には倒されるべき理由があります」', '「ただ、やるなら事前にこれだけは伝えておきましょうか……」',
            '「私は大人気ないですし、相当な負けず嫌いですよ？」', '「あなたは瞬殺されるでしょう。そのような理不尽、受ける必要ありませんね」'],
        'accept_lines' => ['「……勇者とは、どの世界でも変わりませんね」', '「実に愚かで……輝いています」'],
        'cancel_lines' => ['「助かります。理不尽ほど最悪なものはありませんからね」'],
        'rematch_lines' => ['「……」', '「なんで既に倒した相手と戦うつもりなのですか？」',
            '「なに、魔王なら第二携帯や第三形態とかないのかって？」', '「……いや、そりゃー……ありますけど……私にもイメージ戦略というのがですね……？」'],
        'solo_rematch_lines' => ['「……」', '「あなたの考えはわかるわ」', '「おおかた今度は一人で倒そう、なんて思考でしょ？」', '「いいわよ、来なさい。へし折ってやるわ」'],
        'victory_lines' => ['「……久しぶりに負け、ました」', '「悔しいですが……ふふ、やはり戦うのは楽しいものですね」',
            '「ええ。本当は好きなんですよ、私、戦うの」', '「負けるのは嫌いなんですが……ふふ、今はどうしてか楽しくて仕方ないんです」',
            '「戦ってくれてありがとうございました」', '「これを貸してあげましょう。もっとも、あなたには使えないでしょうがお守りにはなります」'],
        'first_victory_lines' => ['「良き夢のあらんことを」'],
        'defeat_lines' => ['「……これでいいでしょう」', '「ふふ、やはり戦うのは楽しいものですね」',
            '「ええ。本当は好きなんですよ、私、戦うの」', '「起きれますか？手当してあげますよ」'],
        'repeat_victory_lines' => ['「……ふむ、すでに持ってましたか」', '「私は一体何を使って戦ってたんでしょうね」', '「どうも長く生きると、記憶が曖昧になっていたようで」'],
        'reward_key' => 'demon_sword_gram',
    ],
    'true_name_story_battle' => [
        'build_key' => 'story_unawakened',
        'enemy_key' => 'story_guide_tank',
        'tier_key' => 'early',
        'combat_level_equivalent' => 1254,
        'seed' => 10602,
        'max_rounds' => 6,
        'expected_winner' => 'enemy',
        'build' => [
            'label' => '契約前の秘書',
            'base_stats' => ['vitality' => 20, 'might' => 20, 'finesse' => 20, 'spirit' => 20, 'agility' => 20],
            'weapon_style' => 'dagger',
            'allocations' => ['martial_precision_cut' => 1],
            'active_skills' => ['precision_cut'],
            'ai_rules' => [
                ['conditions' => [['type' => 'always']], 'action' => 'skill:precision_cut'],
            ],
            'equipment' => [],
        ],
        'enemy' => [
            'label' => 'リカ',
            'boss' => true,
            'base_stats' => ['vitality' => 40, 'might' => 22, 'finesse' => 10, 'spirit' => 16, 'agility' => 12],
            'max_hp' => 5000,
            'physical_defense' => 500,
            'magical_defense' => 500,
            'weapon_power' => 200,
            'normal_attack' => [
                'type' => 'damage', 'category' => 'physical', 'potency_bps' => 10000,
                'stat_coefficients' => ['might' => 10000], 'weapon_coefficient_bps' => 10000,
                'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false,
                'dodgeable' => false, 'hits' => 1,
            ],
            'skills' => ['enemy_unbroken_retort', 'enemy_renewing_guard', 'enemy_bulwark_strike', 'enemy_counter_stance', 'enemy_shield_bash'],
            'ai_rules' => [
                ['conditions' => [['type' => 'round_modulo', 'modulo' => 99, 'equals' => 1]], 'action' => 'skill:enemy_counter_stance'],
                ['conditions' => [['type' => 'own_hp_lte', 'percent' => 65], ['type' => 'skill_ready', 'skill' => 'enemy_renewing_guard']], 'action' => 'skill:enemy_renewing_guard'],
                ['conditions' => [['type' => 'role_stacks_gte', 'status' => 'fighting_spirit', 'stacks' => 1], ['type' => 'skill_ready', 'skill' => 'enemy_unbroken_retort']], 'action' => 'skill:enemy_unbroken_retort'],
                ['conditions' => [['type' => 'skill_ready', 'skill' => 'enemy_bulwark_strike']], 'action' => 'skill:enemy_bulwark_strike'],
                ['conditions' => [['type' => 'skill_ready', 'skill' => 'enemy_shield_bash']], 'action' => 'skill:enemy_shield_bash'],
                ['conditions' => [['type' => 'always']], 'action' => 'normal_attack'],
            ],
            'modifiers' => [
                'fighting_spirit_enabled' => true,
                'counter_power_bps' => 3400,
                'guard_reduction_bps' => 500,
                'parry_bps' => 700,
                'damage_taken_reduction_bps' => 820,
                'self_regeneration_target_hp_bps' => 135,
                'status_potency_bps' => 160,
            ],
        ],
    ],
];
