<?php

return [
    'schema_version' => 1,
    'growth_identity' => 'secretary-underground-growth-alpha-v1',
    'skill_tree_identity' => 'secretary-underground-skill-tree-alpha-v1',
    'initial_skill_points' => 20,
    // Player-facing build guidance only. Combat, healing, AI, requirements, and simulation must not read it.
    'player_skill_guidance' => [
        'precision_cut' => ['recommended_stats' => ['might']],
        'dagger_flurry' => ['recommended_stats' => ['might', 'finesse']],
        'armor_break_strike' => ['recommended_stats' => ['might', 'finesse']],
        'severing_bleed' => ['recommended_stats' => ['might', 'finesse']],
        'executioner_cut' => ['recommended_stats' => ['might', 'finesse']],
        'shield_bash' => ['recommended_stats' => ['vitality', 'might']],
        'counter_stance' => ['recommended_stats' => ['vitality', 'spirit']],
        'bulwark_strike' => ['recommended_stats' => ['vitality', 'might']],
        'renewing_guard' => ['recommended_stats' => ['vitality', 'spirit']],
        'unbroken_retort' => ['recommended_stats' => ['vitality', 'might']],
        'holy_bolt' => ['recommended_stats' => ['spirit', 'finesse']],
        'mending_prayer' => ['recommended_stats' => ['spirit']],
        'crystal_cycle' => ['recommended_stats' => []],
        'crystal_aegis' => ['recommended_stats' => ['spirit', 'vitality']],
        'cleansing_wave' => ['recommended_stats' => ['spirit']],
        'radiant_judgment' => ['recommended_stats' => ['spirit', 'finesse']],
    ],
    'growth_paths' => [
        'martial_red' => [
            'label' => '戦技',
            'color' => 'red',
            'build_key' => 'pure_attacker',
            'description' => [
                '戦技とは立ちはだかる障害を素早く葬り去る技術である。',
                '陰に潜み、暗殺に特化したエルフの物語も少なくない。',
                '自身が傷つくよりも早く、相手が倒れたらそれでよい。',
                '勝利へと素早く辿り着きたいなら、このスキルを選べば良いだろう。',
            ],
            'natural_growth' => ['vitality' => 1, 'might' => 2, 'finesse' => 1, 'spirit' => 1, 'agility' => 0],
            'unspent_stp_per_level' => 5,
        ],
        'guardianship_blue' => [
            'label' => '護身',
            'color' => 'blue',
            'build_key' => 'pure_tank',
            'description' => [
                '護身術は要人の嗜みである。当然、箱庭の全てを管理する秘書もまた例外ではない。',
                '優れた五感であらゆる危機を察知し、敵をその威圧を以て制圧する。',
                'なによりその頑丈さを以て、仲間の前に立つことで真価を発揮することだろう。',
                '粘り強い戦いを求めるならば、このスキルを選べば良いだろう。',
            ],
            'natural_growth' => ['vitality' => 2, 'might' => 1, 'finesse' => 1, 'spirit' => 1, 'agility' => 0],
            'unspent_stp_per_level' => 5,
        ],
        'blessing_green' => [
            'label' => '祝福',
            'color' => 'green',
            'build_key' => 'pure_healer',
            'description' => [
                'エルフは自然との調和性が高く、輝石に秘められた力とも強く共鳴する。',
                '傷を癒やし、身を守る障壁を生み、時にはその光を敵へと向ける。',
                '生き残るための手段を多く持ち、長い戦いほどその力を発揮することだろう。',
                '癒やしと輝石の力を自在に操りたいなら、このスキルを選べば良いだろう。',
            ],
            'natural_growth' => ['vitality' => 1, 'might' => 1, 'finesse' => 1, 'spirit' => 2, 'agility' => 0],
            'unspent_stp_per_level' => 5,
        ],
        'free_black' => [
            'label' => '自由',
            'color' => 'black',
            'build_key' => 'balanced',
            'description' => [
                '全ての輝石を受け取る。非常に欲深く最も効果的な選択肢ではあるが、秘書一人が使える魔力は限られている。',
                '本当に戦闘に最適な能力の振り分けが何なのか、全て自分が決める必要がある。',
                '全て手探りで進めることは茨の道であることは間違いないが、複数の能力を自在に組み合わせ使いこなすことができるだろう。',
                '手動で割り振れるSTPが少し高い。',
            ],
            'natural_growth' => ['vitality' => 1, 'might' => 1, 'finesse' => 1, 'spirit' => 1, 'agility' => 0],
            'unspent_stp_per_level' => 6,
        ],
    ],
    'exploration' => [
        'identity' => 'secretary-underground-exploration-alpha-v2',
        'default_hunting_ground_key' => 'shallow_caves',
        'max_rounds' => 100,
        'starter_weapon' => [
            'key' => 'starter_knife',
            'label' => '護身用ナイフ',
            'item_level' => 1,
            'rarity' => 'common',
            'weapon_style' => 'dagger',
            'weapon_power' => 24,
            'physical_defense' => 0,
            'magical_defense' => 0,
            'max_hp' => 0,
            'stats' => ['vitality' => 1, 'might' => 1, 'finesse' => 1, 'spirit' => 1, 'agility' => 1],
            'modifiers' => [],
            'affixes' => [],
            'unique_effect' => null,
        ],
        'player_ai_rules' => [
            ['conditions' => [['type' => 'enemy_telegraph']], 'action' => 'defend'],
            ['conditions' => [['type' => 'own_hp_lte', 'percent' => 20]], 'action' => 'defend'],
            ['conditions' => [['type' => 'always']], 'action' => 'normal_attack'],
        ],
        'player_skill_ai_rules' => [
            ['conditions' => [['type' => 'own_hp_lte', 'percent' => 55], ['type' => 'skill_ready', 'skill' => 'mending_prayer']], 'action' => 'skill:mending_prayer'],
            ['conditions' => [['type' => 'own_hp_lte', 'percent' => 55], ['type' => 'skill_ready', 'skill' => 'renewing_guard']], 'action' => 'skill:renewing_guard'],
            ['conditions' => [['type' => 'own_mp_lte', 'percent' => 35], ['type' => 'skill_ready', 'skill' => 'crystal_cycle']], 'action' => 'skill:crystal_cycle'],
            ['conditions' => [['type' => 'own_hp_lte', 'percent' => 70], ['type' => 'skill_ready', 'skill' => 'crystal_aegis']], 'action' => 'skill:crystal_aegis'],
            ['conditions' => [['type' => 'self_has_status', 'status' => 'armor_break'], ['type' => 'skill_ready', 'skill' => 'cleansing_wave']], 'action' => 'skill:cleansing_wave'],
            ['conditions' => [['type' => 'role_stacks_gte', 'status' => 'fighting_spirit', 'stacks' => 1], ['type' => 'skill_ready', 'skill' => 'unbroken_retort']], 'action' => 'skill:unbroken_retort'],
            ['conditions' => [['type' => 'self_lacks_status', 'status' => 'aegis'], ['type' => 'skill_ready', 'skill' => 'counter_stance']], 'action' => 'skill:counter_stance'],
            ['conditions' => [['type' => 'enemy_hp_lte', 'percent' => 35], ['type' => 'skill_ready', 'skill' => 'executioner_cut']], 'action' => 'skill:executioner_cut'],
            ['conditions' => [['type' => 'skill_ready', 'skill' => 'armor_break_strike']], 'action' => 'skill:armor_break_strike'],
            ['conditions' => [['type' => 'skill_ready', 'skill' => 'severing_bleed']], 'action' => 'skill:severing_bleed'],
            ['conditions' => [['type' => 'skill_ready', 'skill' => 'dagger_flurry']], 'action' => 'skill:dagger_flurry'],
            ['conditions' => [['type' => 'skill_ready', 'skill' => 'radiant_judgment']], 'action' => 'skill:radiant_judgment'],
            ['conditions' => [['type' => 'skill_ready', 'skill' => 'bulwark_strike']], 'action' => 'skill:bulwark_strike'],
            ['conditions' => [['type' => 'skill_ready', 'skill' => 'shield_bash']], 'action' => 'skill:shield_bash'],
            ['conditions' => [['type' => 'skill_ready', 'skill' => 'precision_cut']], 'action' => 'skill:precision_cut'],
            ['conditions' => [['type' => 'skill_ready', 'skill' => 'holy_bolt']], 'action' => 'skill:holy_bolt'],
        ],
        'drop' => [
            'identity' => 'secretary-underground-exploration-drop-alpha-v1',
            'profiles' => [
                'standard' => [
                    'presence_bps' => 2006,
                    'rarity_weights' => ['common' => 9118, 'uncommon' => 683, 'rare' => 194, 'epic' => 5],
                ],
                'elite' => [
                    'presence_bps' => 3815,
                    'rarity_weights' => ['common' => 7864, 'uncommon' => 1573, 'rare' => 524, 'epic' => 39],
                ],
                'rare' => [
                    'presence_bps' => 10000,
                    'rarity_weights' => ['common' => 5000, 'uncommon' => 3000, 'rare' => 1500, 'epic' => 500],
                ],
            ],
            'category_weights' => ['weapon' => 2000, 'armor' => 2000, 'accessory' => 6000],
            'weapon_styles' => ['dagger', 'rapier', 'longsword', 'crystal_staff'],
            'accessory_main_stats' => ['vitality', 'might', 'finesse', 'spirit', 'agility'],
        ],
        'grounds' => [
            'shallow_caves' => [
                'content_identity' => 'secretary-underground-exploration-alpha-v1',
                'name' => '浅い洞窟',
                'required_trial_key' => null,
                'item_level_min' => 5,
                'item_level_max' => 30,
                'encounters' => [
                    'subterranean_rat' => [
                        'label' => '地底鼠', 'weight' => 2500, 'xp' => 36, 'shards' => 10,
                        'drop_profile' => 'standard', 'item_level_min' => 5, 'item_level_max' => 15,
                        'enemy' => [
                            'label' => '地底鼠', 'boss' => false,
                            'base_stats' => ['vitality' => 15, 'might' => 18, 'finesse' => 18, 'spirit' => 12, 'agility' => 37],
                            'max_hp' => 260, 'physical_defense' => 45, 'magical_defense' => 40, 'weapon_power' => 16,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 6500, 'stat_coefficients' => ['might' => 7000, 'finesse' => 3000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => [], 'ai_rules' => [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']], 'modifiers' => [],
                        ],
                    ],
                    'cave_vermin' => [
                        'label' => '洞窟蟲', 'weight' => 2500, 'xp' => 40, 'shards' => 12,
                        'drop_profile' => 'standard', 'item_level_min' => 5, 'item_level_max' => 15,
                        'enemy' => [
                            'label' => '洞窟蟲', 'boss' => false,
                            'base_stats' => ['vitality' => 22, 'might' => 22, 'finesse' => 18, 'spirit' => 18, 'agility' => 20],
                            'max_hp' => 340, 'physical_defense' => 55, 'magical_defense' => 50, 'weapon_power' => 18,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 7000, 'stat_coefficients' => ['might' => 7000, 'finesse' => 3000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => [], 'ai_rules' => [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']], 'modifiers' => [],
                        ],
                    ],
                    'corrosive_slime' => [
                        'label' => '腐食スライム', 'weight' => 2000, 'xp' => 46, 'shards' => 14,
                        'drop_profile' => 'standard', 'item_level_min' => 5, 'item_level_max' => 15,
                        'enemy' => [
                            'label' => '腐食スライム', 'boss' => false,
                            'base_stats' => ['vitality' => 38, 'might' => 18, 'finesse' => 12, 'spirit' => 22, 'agility' => 10],
                            'max_hp' => 520, 'physical_defense' => 65, 'magical_defense' => 60, 'weapon_power' => 17,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 6500, 'stat_coefficients' => ['might' => 7000, 'finesse' => 3000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => [], 'ai_rules' => [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']], 'modifiers' => [],
                        ],
                    ],
                    'regenerating_mass' => [
                        'label' => '再生肉塊', 'weight' => 1000, 'xp' => 52, 'shards' => 16,
                        'drop_profile' => 'elite', 'item_level_min' => 10, 'item_level_max' => 25,
                        'enemy' => [
                            'label' => '再生肉塊', 'boss' => false,
                            'base_stats' => ['vitality' => 34, 'might' => 26, 'finesse' => 14, 'spirit' => 16, 'agility' => 10],
                            'max_hp' => 500, 'physical_defense' => 60, 'magical_defense' => 55, 'weapon_power' => 25,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 7000, 'stat_coefficients' => ['might' => 7000, 'finesse' => 3000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => [], 'ai_rules' => [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']],
                            'modifiers' => ['self_regeneration_target_hp_bps' => 150],
                        ],
                    ],
                    'fanatic' => [
                        'label' => '狂信者', 'weight' => 1000, 'xp' => 58, 'shards' => 18,
                        'drop_profile' => 'elite', 'item_level_min' => 10, 'item_level_max' => 25,
                        'enemy' => [
                            'label' => '狂信者', 'boss' => false,
                            'base_stats' => ['vitality' => 24, 'might' => 34, 'finesse' => 18, 'spirit' => 12, 'agility' => 12],
                            'max_hp' => 450, 'physical_defense' => 60, 'magical_defense' => 55, 'weapon_power' => 28,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 6500, 'stat_coefficients' => ['might' => 7000, 'finesse' => 3000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => ['pressure_heavy', 'enemy_telegraph'],
                            'ai_rules' => [
                                ['conditions' => [['type' => 'self_has_status', 'status' => 'telegraph']], 'action' => 'skill:pressure_heavy'],
                                ['conditions' => [['type' => 'round_modulo', 'modulo' => 3, 'equals' => 2]], 'action' => 'skill:enemy_telegraph'],
                                ['conditions' => [['type' => 'always']], 'action' => 'normal_attack'],
                            ],
                            'modifiers' => [],
                        ],
                    ],
                    'lost_shadow' => [
                        'label' => '迷い人の影', 'weight' => 900, 'xp' => 72, 'shards' => 22,
                        'drop_profile' => 'elite', 'item_level_min' => 20, 'item_level_max' => 30,
                        'enemy' => [
                            'label' => '迷い人の影', 'boss' => false,
                            'base_stats' => ['vitality' => 28, 'might' => 34, 'finesse' => 20, 'spirit' => 2, 'agility' => 16],
                            'max_hp' => 1000, 'physical_defense' => 110, 'magical_defense' => 100, 'weapon_power' => 44,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 10500, 'stat_coefficients' => ['might' => 7000, 'finesse' => 3000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => true, 'dodgeable' => true, 'hits' => 1],
                            'skills' => [], 'ai_rules' => [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']], 'modifiers' => [],
                        ],
                    ],
                    'crystal_bug' => [
                        'label' => '輝石虫', 'weight' => 100, 'xp' => 1150, 'shards' => 0,
                        'drop_profile' => 'rare', 'item_level_min' => 25, 'item_level_max' => 30,
                        'enemy' => [
                            'label' => '輝石虫', 'boss' => false,
                            'base_stats' => ['vitality' => 20, 'might' => 5, 'finesse' => 5, 'spirit' => 60, 'agility' => 10],
                            'max_hp' => 1, 'physical_defense' => 0, 'magical_defense' => 0, 'weapon_power' => 1,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 1000, 'stat_coefficients' => ['might' => 10000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => [], 'ai_rules' => [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']],
                            'modifiers' => ['complete_guard_chance_bps' => 9900],
                        ],
                    ],
                ],
            ],
            'black_crystal_cave' => [
                'content_identity' => 'secretary-underground-black-crystal-cave-alpha-v1',
                'name' => '黒晶洞',
                'required_trial_key' => 'trial_01',
                'item_level_min' => 30,
                'item_level_max' => 60,
                'encounters' => [
                    'black_crystal_bat' => [
                        'label' => '黒晶蝙蝠', 'weight' => 2500, 'xp' => 145, 'shards' => 37,
                        'drop_profile' => 'standard', 'item_level_min' => 30, 'item_level_max' => 38,
                        'enemy' => [
                            'label' => '黒晶蝙蝠', 'boss' => false,
                            'base_stats' => ['vitality' => 18, 'might' => 26, 'finesse' => 22, 'spirit' => 8, 'agility' => 26],
                            'max_hp' => 1400, 'physical_defense' => 100, 'magical_defense' => 90, 'weapon_power' => 125,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 6500, 'stat_coefficients' => ['might' => 7000, 'finesse' => 3000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => [], 'ai_rules' => [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']], 'modifiers' => [],
                        ],
                    ],
                    'black_crystal_beast' => [
                        'label' => '黒晶獣', 'weight' => 2000, 'xp' => 160, 'shards' => 42,
                        'drop_profile' => 'standard', 'item_level_min' => 30, 'item_level_max' => 40,
                        'enemy' => [
                            'label' => '黒晶獣', 'boss' => false,
                            'base_stats' => ['vitality' => 24, 'might' => 32, 'finesse' => 18, 'spirit' => 12, 'agility' => 14],
                            'max_hp' => 1650, 'physical_defense' => 125, 'magical_defense' => 110, 'weapon_power' => 135,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 7000, 'stat_coefficients' => ['might' => 7000, 'finesse' => 3000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => [], 'ai_rules' => [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']], 'modifiers' => [],
                        ],
                    ],
                    'crystal_shell_bug' => [
                        'label' => '晶殻蟲', 'weight' => 1500, 'xp' => 170, 'shards' => 47,
                        'drop_profile' => 'standard', 'item_level_min' => 32, 'item_level_max' => 40,
                        'enemy' => [
                            'label' => '晶殻蟲', 'boss' => false,
                            'base_stats' => ['vitality' => 40, 'might' => 22, 'finesse' => 8, 'spirit' => 20, 'agility' => 10],
                            'max_hp' => 1950, 'physical_defense' => 200, 'magical_defense' => 125, 'weapon_power' => 125,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 6000, 'stat_coefficients' => ['might' => 7000, 'finesse' => 3000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => [], 'ai_rules' => [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']], 'modifiers' => [],
                        ],
                    ],
                    'black_crystal_mage' => [
                        'label' => '黒晶術師', 'weight' => 1000, 'xp' => 185, 'shards' => 55,
                        'drop_profile' => 'standard', 'item_level_min' => 34, 'item_level_max' => 40,
                        'enemy' => [
                            'label' => '黒晶術師', 'boss' => false,
                            'base_stats' => ['vitality' => 18, 'might' => 10, 'finesse' => 20, 'spirit' => 42, 'agility' => 10],
                            'max_hp' => 1550, 'physical_defense' => 100, 'magical_defense' => 190, 'weapon_power' => 140,
                            'normal_attack' => ['type' => 'damage', 'category' => 'miracle', 'potency_bps' => 7000, 'stat_coefficients' => ['spirit' => 10000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => [], 'ai_rules' => [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']], 'modifiers' => [],
                        ],
                    ],
                    'crystal_berserker' => [
                        'label' => '破晶の狂戦士', 'weight' => 1200, 'xp' => 280, 'shards' => 78,
                        'drop_profile' => 'elite', 'item_level_min' => 35, 'item_level_max' => 47,
                        'enemy' => [
                            'label' => '破晶の狂戦士', 'boss' => false,
                            'base_stats' => ['vitality' => 30, 'might' => 40, 'finesse' => 10, 'spirit' => 10, 'agility' => 10],
                            'max_hp' => 2300, 'physical_defense' => 165, 'magical_defense' => 140, 'weapon_power' => 170,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 6500, 'stat_coefficients' => ['might' => 10000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => ['pressure_heavy', 'enemy_telegraph'],
                            'ai_rules' => [
                                ['conditions' => [['type' => 'self_has_status', 'status' => 'telegraph']], 'action' => 'skill:pressure_heavy'],
                                ['conditions' => [['type' => 'round_modulo', 'modulo' => 3, 'equals' => 2]], 'action' => 'skill:enemy_telegraph'],
                                ['conditions' => [['type' => 'always']], 'action' => 'normal_attack'],
                            ],
                            'modifiers' => [],
                        ],
                    ],
                    'black_crystal_regenerator' => [
                        'label' => '黒晶再生体', 'weight' => 800, 'xp' => 330, 'shards' => 98,
                        'drop_profile' => 'elite', 'item_level_min' => 40, 'item_level_max' => 50,
                        'enemy' => [
                            'label' => '黒晶再生体', 'boss' => false,
                            'base_stats' => ['vitality' => 42, 'might' => 22, 'finesse' => 8, 'spirit' => 18, 'agility' => 10],
                            'max_hp' => 2800, 'physical_defense' => 180, 'magical_defense' => 165, 'weapon_power' => 160,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 7000, 'stat_coefficients' => ['might' => 7000, 'finesse' => 3000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => [], 'ai_rules' => [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']],
                            'modifiers' => ['self_regeneration_target_hp_bps' => 150],
                        ],
                    ],
                    'black_crystal_warden' => [
                        'label' => '黒晶の番人', 'weight' => 900, 'xp' => 600, 'shards' => 157,
                        'drop_profile' => 'elite', 'item_level_min' => 45, 'item_level_max' => 60,
                        'enemy' => [
                            'label' => '黒晶の番人', 'boss' => false,
                            'base_stats' => ['vitality' => 36, 'might' => 34, 'finesse' => 10, 'spirit' => 10, 'agility' => 10],
                            'max_hp' => 3700, 'physical_defense' => 240, 'magical_defense' => 215, 'weapon_power' => 215,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 7000, 'stat_coefficients' => ['might' => 10000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => ['pressure_heavy', 'enemy_telegraph'],
                            'ai_rules' => [
                                ['conditions' => [['type' => 'self_has_status', 'status' => 'telegraph']], 'action' => 'skill:pressure_heavy'],
                                ['conditions' => [['type' => 'round_modulo', 'modulo' => 4, 'equals' => 3]], 'action' => 'skill:enemy_telegraph'],
                                ['conditions' => [['type' => 'always']], 'action' => 'normal_attack'],
                            ],
                            'modifiers' => ['damage_taken_reduction_bps' => 300],
                        ],
                    ],
                    'black_crystal_bug' => [
                        'label' => '黒晶虫', 'weight' => 100, 'xp' => 1400, 'shards' => 0,
                        'drop_profile' => 'rare', 'item_level_min' => 50, 'item_level_max' => 60,
                        'enemy' => [
                            'label' => '黒晶虫', 'boss' => false,
                            'base_stats' => ['vitality' => 20, 'might' => 5, 'finesse' => 5, 'spirit' => 60, 'agility' => 10],
                            'max_hp' => 1, 'physical_defense' => 0, 'magical_defense' => 0, 'weapon_power' => 1,
                            'normal_attack' => ['type' => 'damage', 'category' => 'physical', 'potency_bps' => 1000, 'stat_coefficients' => ['might' => 10000], 'weapon_coefficient_bps' => 10000, 'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false, 'dodgeable' => true, 'hits' => 1],
                            'skills' => [], 'ai_rules' => [['conditions' => [['type' => 'always']], 'action' => 'normal_attack']],
                            'modifiers' => ['complete_guard_chance_bps' => 9900],
                        ],
                    ],
                ],
            ],
        ],
    ],
    'shop' => [
        'inn' => ['cost_shards' => 10],
        'bank' => ['transfer_unit_shards' => 1000],
    ],
    'playtest' => [
        'identity' => 'secretary-underground-playtest-alpha-v1',
        'tier_key' => 'early',
        'notice' => 'α版の戦闘検証用完成形ビルドです。正式な育成・装備状態ではありません。',
        'builds' => [
            'pure_attacker' => ['description' => '戦技を中心に、短い戦闘で敵を倒す完成形ビルド。'],
            'pure_tank' => ['description' => 'guard・barrier・闘志・counterを組み合わせる護身型ビルド。'],
            'pure_healer' => ['description' => '回復・障壁・恩寵を使って長く戦う祝福型ビルド。'],
            'balanced' => ['description' => '戦技・護身・祝福を混ぜて対応する混成ビルド。'],
        ],
        'enemies' => [
            'depth_stalker' => [
                'label' => '深層追跡者',
                'description' => 'Lv1相当の完成形ビルドを確認する、通常の適正戦闘です。',
                'max_rounds' => 100,
            ],
            'pressure_construct' => [
                'label' => '予兆を放つ圧力試験体',
                'description' => '予告大技に対する防御判断と長期戦の挙動を確認します。',
                'max_rounds' => 100,
            ],
            'crystal_warden' => [
                'label' => '輝晶守護者',
                'description' => 'bossへのstatus・control変換と継戦能力を確認します。',
                'max_rounds' => 100,
            ],
        ],
    ],
    'true_name_story_battle' => [
        'build_key' => 'story_unawakened',
        'enemy_key' => 'story_guide_tank',
        'tier_key' => 'early',
        'combat_level_equivalent' => 1254,
        'seed' => 10602,
        'max_rounds' => 6,
        'expected_winner' => 'enemy',
        'build' => [
            'label' => '契約前の秘書',
            'base_stats' => ['vitality' => 20, 'might' => 20, 'finesse' => 20, 'spirit' => 20, 'agility' => 20],
            'weapon_style' => 'dagger',
            'allocations' => ['martial_precision_cut' => 1],
            'active_skills' => ['precision_cut'],
            'ai_rules' => [
                ['conditions' => [['type' => 'always']], 'action' => 'skill:precision_cut'],
            ],
            'equipment' => [],
        ],
        'enemy' => [
            'label' => 'リカ',
            'boss' => true,
            'base_stats' => ['vitality' => 40, 'might' => 22, 'finesse' => 10, 'spirit' => 16, 'agility' => 12],
            'max_hp' => 5000,
            'physical_defense' => 500,
            'magical_defense' => 500,
            'weapon_power' => 200,
            'normal_attack' => [
                'type' => 'damage', 'category' => 'physical', 'potency_bps' => 10000,
                'stat_coefficients' => ['might' => 10000], 'weapon_coefficient_bps' => 10000,
                'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false,
                'dodgeable' => false, 'hits' => 1,
            ],
            'skills' => ['unbroken_retort', 'renewing_guard', 'bulwark_strike', 'counter_stance', 'shield_bash'],
            'ai_rules' => [
                ['conditions' => [['type' => 'round_modulo', 'modulo' => 99, 'equals' => 1]], 'action' => 'skill:counter_stance'],
                ['conditions' => [['type' => 'own_hp_lte', 'percent' => 65], ['type' => 'skill_ready', 'skill' => 'renewing_guard']], 'action' => 'skill:renewing_guard'],
                ['conditions' => [['type' => 'role_stacks_gte', 'status' => 'fighting_spirit', 'stacks' => 1], ['type' => 'skill_ready', 'skill' => 'unbroken_retort']], 'action' => 'skill:unbroken_retort'],
                ['conditions' => [['type' => 'skill_ready', 'skill' => 'bulwark_strike']], 'action' => 'skill:bulwark_strike'],
                ['conditions' => [['type' => 'skill_ready', 'skill' => 'shield_bash']], 'action' => 'skill:shield_bash'],
                ['conditions' => [['type' => 'always']], 'action' => 'normal_attack'],
            ],
            'modifiers' => [
                'fighting_spirit_enabled' => true,
                'counter_power_bps' => 3400,
                'guard_reduction_bps' => 500,
                'parry_bps' => 700,
                'damage_taken_reduction_bps' => 820,
                'self_regeneration_target_hp_bps' => 135,
                'status_potency_bps' => 160,
            ],
        ],
    ],
];
