<?php

return [
    'schema_version' => 2,
    'story_identity' => 'secretary-underground-intro-alpha-v2',
    'shopkeeper_name' => [
        'maximum_graphemes' => 20,
        'true_name_aliases' => [
            'リカ',
            '雨宮利香',
            '雨宮 利香',
            '雨宮　利香',
            'リカ・サキュバス',
        ],
    ],
    'battles' => [
        'tutorial' => [
            'activity_type' => 'tutorial',
            'activity_key' => 'first_descent_tutorial',
            'encounter_key' => 'tutorial_giant_rat',
            'display_name' => 'ジャイアントラット',
            'seed' => 10401,
            'max_rounds' => 30,
            'expected_winner' => 'player',
            'xp_reward' => 5,
            'shard_reward' => 0,
            'actor' => [
                'key' => 'tutorial_secretary',
                'label' => '秘書',
                'stats' => ['vitality' => 10, 'might' => 10, 'finesse' => 10, 'spirit' => 10, 'agility' => 10],
                'weapon_key' => 'tutorial_starter_knife',
                'max_hp' => 220,
                'attack' => 105,
                'defense' => 70,
                'speed' => 90,
                'available_skills' => ['quick_slash'],
            ],
            'loadout' => ['quick_slash'],
            'enemy' => [
                'key' => 'tutorial_giant_rat',
                'label' => 'ジャイアントラット',
                'role' => 'tutorial',
                'behavior' => 'standard',
                'max_hp' => 90,
                'attack' => 38,
                'defense' => 18,
                'speed' => 45,
            ],
        ],
        'scripted_loss' => [
            'activity_type' => 'story',
            'activity_key' => 'shopkeeper_special_loss',
            'encounter_key' => 'shopkeeper_scripted_loss',
            'display_name' => '（ダミー）',
            'seed' => 10402,
            'max_rounds' => 10,
            'expected_winner' => 'enemy',
            'xp_reward' => 0,
            'shard_reward' => 0,
            'actor' => [
                'key' => 'scripted_loss_secretary',
                'label' => '秘書',
                'weapon_key' => 'story_snapshot',
                'max_hp' => 40,
                'attack' => 20,
                'defense' => 0,
                'speed' => 20,
                'available_skills' => ['quick_slash'],
            ],
            'loadout' => ['quick_slash'],
            'enemy' => [
                'key' => 'shopkeeper_scripted_loss',
                'label' => '（ダミー）',
                'role' => 'scripted_loss',
                'behavior' => 'standard',
                'max_hp' => 999,
                'attack' => 500,
                'defense' => 999,
                'speed' => 200,
            ],
        ],
    ],
];
