<?php

return [
    'commands' => [
        [
            'key' => 'build_underground_city',
            'name' => '地底都市建設',
            'description' => '空き地底施設枠へ地底都市を建設し、首都人口の成長上限を10,000人増やします。',
            'cost_money' => 1000,
            'action' => 'build',
            'facility_key' => 'underground_city',
            'effect' => ['capital_maximum_population_bonus' => 10_000],
            'sort_order' => 1,
        ],
        [
            'key' => 'build_underground_farm',
            'name' => '地底農場建設',
            'description' => '空き地底施設枠へ地底農場を建設し、農場能力を10,000人分増やします。',
            'cost_money' => 1000,
            'action' => 'build',
            'facility_key' => 'underground_farm',
            'effect' => ['farm_capacity_people' => 10_000],
            'sort_order' => 2,
        ],
        [
            'key' => 'build_underground_factory',
            'name' => '地底工場建設',
            'description' => '空き地底施設枠へ地底工場を建設し、工場能力を30,000人分増やします。',
            'cost_money' => 1000,
            'action' => 'build',
            'facility_key' => 'underground_factory',
            'effect' => ['factory_capacity_people' => 30_000],
            'sort_order' => 3,
        ],
        [
            'key' => 'build_underground_missile_base',
            'name' => '地底ミサイル基地建設',
            'description' => '空き地底施設枠へ地底ミサイル基地を建設し、ミサイル1発分の発射能力を追加します。',
            'cost_money' => 1000,
            'action' => 'build',
            'facility_key' => 'underground_missile_base',
            'effect' => ['missile_launch_capacity' => 1],
            'sort_order' => 4,
        ],
        [
            'key' => 'remove_underground_facility',
            'name' => '地下施設撤去',
            'description' => '建築済みの地下施設を撤去して空き枠へ戻します。払い戻しはありません。',
            'cost_money' => 50,
            'action' => 'remove',
            'facility_key' => null,
            'effect' => [],
            'sort_order' => 5,
        ],
    ],
];
