<?php

return [
    'schema_version' => 1,
    'runtime_identity' => 'secretary-underground-runtime-alpha-v0',
    'combat_rules_identity' => 'secretary-underground-alpha-v0',
    'combat' => [
        'max_rounds' => 100,
        'cooldown_seconds' => 10,
        'battle_log_retention_hours' => 1,
        'actor_key' => 'knife_initiate',
        'loadout' => [
            'quick_slash',
            'piercing_thrust',
            'mending_light',
            'crystal_burst',
        ],
        'ai_preset' => 'built_in_v0',
    ],
    'xp_curve' => [
        'first_level_cost' => 100,
        'cost_increment_per_level' => 50,
    ],
    'encounters' => [
        'cave_crawler' => ['type' => 'combat', 'enemy_key' => 'cave_crawler', 'xp' => 40, 'shards' => 12],
        'needle_bat' => ['type' => 'combat', 'enemy_key' => 'needle_bat', 'xp' => 45, 'shards' => 14],
        'stone_shell' => ['type' => 'combat', 'enemy_key' => 'stone_shell', 'xp' => 55, 'shards' => 18],
        'gloom_herald' => ['type' => 'combat', 'enemy_key' => 'gloom_herald', 'xp' => 65, 'shards' => 22],
    ],
    'hunting_grounds' => [
        'shallow_caves' => [
            'minimum_combat_level' => 1,
            'encounters' => ['cave_crawler', 'needle_bat'],
        ],
        'lower_galleries' => [
            'minimum_combat_level' => 4,
            'encounters' => ['stone_shell', 'gloom_herald'],
        ],
    ],
    // Party boss definitions are intentionally absent until a concrete boss is authored.
    'party_boss_scaling_profiles' => [
        'none' => ['mode' => 'none'],
    ],
    'skip' => [
        'identity' => 'secretary-underground-skip-v1',
        'hunting_ground' => [
            'actual_clears_required' => 50,
            'ticket_cost' => 1,
        ],
        'trial' => [
            'actual_clears_required' => 5,
            'ticket_cost' => 10,
        ],
    ],
    'trials' => [
        'trial_01' => [
            'label' => '地下に眠る古代遺跡',
            'content_identity' => 'secretary-underground-trial-01-v2',
            'balance_manifest' => 'underground/balance/trial1-v1.json',
            'required_trial_key' => null,
            'interbattle_heal_bps' => 2000,
            'first_clear_skill_points' => 40,
            'unlocked_area_layers' => 1,
            'encounters' => [
                'trial_rat_vanguard',
                'trial_cave_hunter',
                'trial_corrosive_guard',
                'trial_regenerating_hulk',
                'trial_crystal_adept',
                'trial_fanatic_captain',
                'trial_razor_bat',
                'trial_ash_knight',
                'trial_gate_golem',
                'trial_wyvern',
            ],
            'rewards' => [
                ['xp' => 40, 'shards' => 12],
                ['xp' => 45, 'shards' => 14],
                ['xp' => 40, 'shards' => 12],
                ['xp' => 55, 'shards' => 18],
                ['xp' => 45, 'shards' => 14],
                ['xp' => 40, 'shards' => 12],
                ['xp' => 55, 'shards' => 18],
                ['xp' => 45, 'shards' => 14],
                ['xp' => 65, 'shards' => 22],
                ['xp' => 370, 'shards' => 69],
            ],
        ],
        'trial_02' => [
            'label' => '黒曜石の魔窟',
            'content_identity' => 'secretary-underground-trial-02-v1',
            'balance_manifest' => 'underground/balance/trial2-v1.json',
            'required_trial_key' => 'trial_01',
            'drop_tier_key' => 'obsidian_cavern',
            'interbattle_heal_bps' => 2000,
            'first_clear_skill_points' => 40,
            'unlocked_area_layers' => 2,
            'encounters' => [
                'trial2_sootfang_scout',
                'trial2_mockflame_jester',
                'trial2_ironchain_hellhound',
                'trial2_sleepless_stonewing',
                'trial2_redhorn_breacher',
                'trial2_funeral_bell_priest',
                'trial2_beguiling_serpent_princess',
                'trial2_night_banquet_blood_lord',
                'trial2_oath_eater_black_knight',
                'trial2_headless_lord_of_judgment',
            ],
            'rewards' => [
                ['xp' => 250, 'shards' => 65, 'drop_profile' => 'trial2_shallow', 'item_level_min' => 55, 'item_level_max' => 66],
                ['xp' => 260, 'shards' => 68, 'drop_profile' => 'trial2_shallow', 'item_level_min' => 56, 'item_level_max' => 67],
                ['xp' => 270, 'shards' => 70, 'drop_profile' => 'trial2_shallow', 'item_level_min' => 58, 'item_level_max' => 69],
                ['xp' => 280, 'shards' => 72, 'drop_profile' => 'trial2_middle', 'item_level_min' => 60, 'item_level_max' => 72],
                ['xp' => 290, 'shards' => 75, 'drop_profile' => 'trial2_middle', 'item_level_min' => 62, 'item_level_max' => 74],
                ['xp' => 300, 'shards' => 78, 'drop_profile' => 'trial2_middle', 'item_level_min' => 64, 'item_level_max' => 76],
                ['xp' => 320, 'shards' => 82, 'drop_profile' => 'trial2_middle', 'item_level_min' => 66, 'item_level_max' => 78],
                ['xp' => 350, 'shards' => 88, 'drop_profile' => 'trial2_deep', 'item_level_min' => 68, 'item_level_max' => 82],
                ['xp' => 400, 'shards' => 95, 'drop_profile' => 'trial2_deep', 'item_level_min' => 72, 'item_level_max' => 86],
                ['xp' => 2000, 'shards' => 540, 'drop_profile' => 'trial2_deep', 'item_level_min' => 76, 'item_level_max' => 90],
            ],
        ],
    ],
];
