<?php

return [
    'schema_version' => 1,
    'growth_identity' => 'secretary-underground-growth-alpha-v1',
    'growth_paths' => [
        'martial_red' => [
            'label' => '戦技',
            'color' => 'red',
            'build_key' => 'pure_attacker',
            'description' => [
                '戦技とは立ちはだかる障害を素早く葬り去る技術である。',
                '陰に潜み、暗殺に特化したエルフの物語も少なくない。',
                '自身が傷つくよりも早く、相手が倒れたらそれでよい。',
                '勝利へと素早く辿り着きたいなら、このスキルを選べば良いだろう。',
            ],
            'natural_growth' => ['vitality' => 1, 'might' => 2, 'finesse' => 1, 'spirit' => 1, 'agility' => 0],
            'unspent_stp_per_level' => 5,
        ],
        'guardianship_blue' => [
            'label' => '護身',
            'color' => 'blue',
            'build_key' => 'pure_tank',
            'description' => [
                '護身術は要人の嗜みである。当然、箱庭の全てを管理する秘書もまた例外ではない。',
                '優れた五感であらゆる危機を察知し、敵をその威圧を以て制圧する。',
                'なによりその頑丈さを以て、仲間の前に立つことで真価を発揮することだろう。',
                '粘り強い戦いを求めるならば、このスキルを選べば良いだろう。',
            ],
            'natural_growth' => ['vitality' => 2, 'might' => 1, 'finesse' => 1, 'spirit' => 1, 'agility' => 0],
            'unspent_stp_per_level' => 5,
        ],
        'blessing_green' => [
            'label' => '祝福',
            'color' => 'green',
            'build_key' => 'pure_healer',
            'description' => [
                'エルフは自然との調和性が高く、輝石に秘められた力とも強く共鳴する。',
                '傷を癒やし、身を守る障壁を生み、時にはその光を敵へと向ける。',
                '生き残るための手段を多く持ち、長い戦いほどその力を発揮することだろう。',
                '癒やしと輝石の力を自在に操りたいなら、このスキルを選べば良いだろう。',
            ],
            'natural_growth' => ['vitality' => 1, 'might' => 1, 'finesse' => 1, 'spirit' => 2, 'agility' => 0],
            'unspent_stp_per_level' => 5,
        ],
        'free_black' => [
            'label' => '自由',
            'color' => 'black',
            'build_key' => 'balanced',
            'description' => [
                '全ての輝石を受け取る。非常に欲深く最も効果的な選択肢ではあるが、秘書一人が使える魔力は限られている。',
                '本当に戦闘に最適な能力の振り分けが何なのか、全て自分が決める必要がある。',
                '全て手探りで進めることは茨の道であることは間違いないが、複数の能力を自在に組み合わせ使いこなすことができるだろう。',
                '手動で割り振れるSTPが少し高い。',
            ],
            'natural_growth' => ['vitality' => 1, 'might' => 1, 'finesse' => 1, 'spirit' => 1, 'agility' => 0],
            'unspent_stp_per_level' => 6,
        ],
    ],
    'playtest' => [
        'identity' => 'secretary-underground-playtest-alpha-v1',
        'tier_key' => 'early',
        'notice' => 'α版の戦闘検証用完成形ビルドです。正式な育成・装備状態ではありません。',
        'builds' => [
            'pure_attacker' => ['description' => '戦技を中心に、短い戦闘で敵を倒す完成形ビルド。'],
            'pure_tank' => ['description' => 'guard・barrier・闘志・counterを組み合わせる護身型ビルド。'],
            'pure_healer' => ['description' => '回復・障壁・恩寵を使って長く戦う奇跡型ビルド。'],
            'balanced' => ['description' => '戦技・護身・奇跡を混ぜて対応する混成ビルド。'],
        ],
        'enemies' => [
            'depth_stalker' => [
                'label' => '深層追跡者',
                'description' => 'Lv1相当の完成形ビルドを確認する、通常の適正戦闘です。',
                'max_rounds' => 100,
            ],
            'pressure_construct' => [
                'label' => '予兆を放つ圧力試験体',
                'description' => '予告大技に対する防御判断と長期戦の挙動を確認します。',
                'max_rounds' => 100,
            ],
            'crystal_warden' => [
                'label' => '輝晶守護者',
                'description' => 'bossへのstatus・control変換と継戦能力を確認します。',
                'max_rounds' => 100,
            ],
        ],
    ],
    'true_name_story_battle' => [
        'build_key' => 'story_unawakened',
        'enemy_key' => 'story_guide_tank',
        'tier_key' => 'early',
        'combat_level_equivalent' => 1254,
        'seed' => 10602,
        'max_rounds' => 6,
        'expected_winner' => 'enemy',
        'build' => [
            'label' => '契約前の秘書',
            'base_stats' => ['vitality' => 20, 'might' => 20, 'finesse' => 20, 'spirit' => 20, 'agility' => 20],
            'weapon_style' => 'dagger',
            'allocations' => ['martial_precision_cut' => 1],
            'active_skills' => ['precision_cut'],
            'ai_rules' => [
                ['conditions' => [['type' => 'always']], 'action' => 'skill:precision_cut'],
            ],
            'equipment' => [],
        ],
        'enemy' => [
            'label' => 'リカ',
            'boss' => true,
            'base_stats' => ['vitality' => 40, 'might' => 22, 'finesse' => 10, 'spirit' => 16, 'agility' => 12],
            'max_hp' => 5000,
            'physical_defense' => 500,
            'magical_defense' => 500,
            'weapon_power' => 200,
            'normal_attack' => [
                'type' => 'damage', 'category' => 'physical', 'potency_bps' => 10000,
                'stat_coefficients' => ['might' => 10000], 'weapon_coefficient_bps' => 10000,
                'fixed' => 0, 'target_max_hp_bps' => 0, 'can_crit' => false,
                'dodgeable' => false, 'hits' => 1,
            ],
            'skills' => ['unbroken_retort', 'renewing_guard', 'bulwark_strike', 'counter_stance', 'shield_bash'],
            'ai_rules' => [
                ['conditions' => [['type' => 'round_modulo', 'modulo' => 99, 'equals' => 1]], 'action' => 'skill:counter_stance'],
                ['conditions' => [['type' => 'own_hp_lte', 'percent' => 65], ['type' => 'skill_ready', 'skill' => 'renewing_guard']], 'action' => 'skill:renewing_guard'],
                ['conditions' => [['type' => 'role_stacks_gte', 'status' => 'fighting_spirit', 'stacks' => 1], ['type' => 'skill_ready', 'skill' => 'unbroken_retort']], 'action' => 'skill:unbroken_retort'],
                ['conditions' => [['type' => 'skill_ready', 'skill' => 'bulwark_strike']], 'action' => 'skill:bulwark_strike'],
                ['conditions' => [['type' => 'skill_ready', 'skill' => 'shield_bash']], 'action' => 'skill:shield_bash'],
                ['conditions' => [['type' => 'always']], 'action' => 'normal_attack'],
            ],
            'modifiers' => [
                'fighting_spirit_enabled' => true,
                'counter_power_bps' => 3400,
                'guard_reduction_bps' => 500,
                'parry_bps' => 700,
                'damage_taken_reduction_bps' => 820,
                'self_regeneration_target_hp_bps' => 135,
                'status_potency_bps' => 160,
            ],
        ],
    ],
];
