<?php

return [
    'schema_version' => 2,
    'story_identity' => 'secretary-underground-intro-alpha-v2',
    'distorted_stone_daily_prices' => [10000, 50000, 100000],
    'residence' => [
        'villa' => ['name' => '別荘', 'price' => 100000],
        'mirror' => ['name' => '透明な鏡', 'price' => 1000000],
        'trophy_shelf' => ['name' => 'トロフィー棚', 'price' => 500000],
        'vault_expansion' => ['name' => '宝物庫増築(1)', 'price' => 1000000],
        'resonance_expansion' => ['name' => '共鳴結晶庫増築(1)', 'price' => 1000000],
    ],
    'shopkeeper_name' => [
        'maximum_graphemes' => 20,
        'true_name_aliases' => [
            'リカ',
            '雨宮利香',
            '雨宮 利香',
            '雨宮　利香',
            'リカ・サキュバス',
        ],
    ],
    'recollections' => [
        'identity' => 'secretary-underground-recollections-owner-v1',
        'past' => [
            [
                'key' => 'past_1',
                'chapter' => 1,
                'title' => '過去について問う・1',
                'body' => [
                    '「ええ。かつての世界の全てを滅ぼし、深い海に沈め、永遠に解かれぬ封印をつけたのが犯人というのなら、私がそうですよ」',
                    '「私は男が女性に抱くある種の欲望を満たすために産み出された、人間と色欲の魔族のハーフ……」',
                    '「混血であるが故に、人の残酷なまでな正しさにも、傲慢な魔族の欲望にも馴染めなかった。かつては自分がどちらになるべきかと魔界を飛び出して模索した時期もあったのですが……」',
                    '「結局を言えば、どちらの世界も自分の居場所ではないと思い知らされるばかりでしたね」',
                ],
            ],
            [
                'key' => 'past_2',
                'chapter' => 2,
                'title' => '過去について問う・2',
                'body' => [
                    '「訳あって異世界に迷い込み、勇者紛いの事もした事もありましたが……ええ。ありましたよ。皆の盾になって、それでも護りきれず、同胞が倒れていくのを目にして」',
                    '「感謝したのも束の間、人々は犠牲の山の上に築かれた平和をたったの数十年で神話というカバーストーリーを敷いて、忘れ去ってしまいました」',
                    '「もう彼らも、犠牲になった勇者の名前を一人一人覚えてはいない。私の心には傷として深く刻まれてしまいました」',
                    '「……結局は、自分の寿命が長いばかりに」',
                    '「なのに、人間の少女くらいしか生きていない若造だった故に」',
                    '「まったく。どうして私はあんな勇者ごっこをしてしまったんでしょうね」',
                    '「もう私の名前も覚えているものはいないでしょう」',
                    '「仮にもしあなたやあなたの主人が私の本当の名前を知っていたとしても、そう呼ばれたくはありませんがね」',
                    '「あれは忌々しい、記憶なんですから」',
                ],
            ],
            [
                'key' => 'past_3',
                'chapter' => 3,
                'title' => '過去について問う・3',
                'body' => [
                    '「異世界で私は乱を起こしました」',
                    '「かつての英雄の一人が、力を蓄え、英霊たちの名を忘れた世界に反旗を翻す」',
                    '「実にくだらない理由で怒り、敗北し、帰ってきた私が見たものは、全て海に沈んだ世界でした」',
                    '「何故、どうやったかのは自分でもわかりませんが。自分がやったのだろうというよくわからない確信はありました」',
                    '「色々あったんですよ、人間も魔族も、全部沈めたくなるくらいには……まぁ、うんざりしてました」',
                    '「輝石、あるでしょう？　旧世界の時間や空間を封じ込めた、あなたに力を与える石、そう仰ったはずです」',
                    '「私の種族は人を惑わす魔石の一族」',
                    '「宝石は全てを封じ込める、そして、あの眩いばかりの輝きが、心を奪う」',
                    '「そして閉じ込めてしまうのです、永遠に、永遠に」',
                ],
            ],
            [
                'key' => 'past_4',
                'chapter' => 4,
                'title' => '過去について問う・4',
                'body' => [
                    '「しかし最近、どう言うわけか私の封印を外れ、輝石の一部が魔物やアンデッドとなって形を得て、ダンジョンを作り出し……その中で暴れ始めたのです」',
                    '「恐らくは私の無意識下のなんらかの精神的な変化によるものでしょう。あるいは……なにか原因があるか」',
                    '「いずれにせよ、私がこの地の魔物を斬ったところで何も変わらないのですよ。すぐにどこかで再生する。だって、私がここを作ったんですから……あの首なしの鎧も洞窟の奥であなたへ理不尽な恨みを抱いて待っているでしょう」',
                    '「より下の階層に押し込むくらいならできますけどね」',
                    '「だから、あなたと言う異物が魔物を切り、輝石として持ち帰る、その過程が必要なのです」',
                    '「たくらむことなんてありません。これで世界が救われるだ滅ぶだ、まして私が死ぬわけでもありません。これはただあなたが満足するだけの暇つぶし——私はあなたを喜ばせることだけが存在意義であり役目なのですから」',
                    '「所詮は、全て暇つぶしなんですよ」',
                ],
            ],
            [
                'key' => 'past_5',
                'chapter' => 5,
                'title' => '過去について問う・5',
                'body' => [
                    '「あなたの目的はなんですか？」',
                    '「暇つぶしなら……既に叶ってるでしょうね」',
                    '「私と話をするのは暇つぶしで暇つぶしをしている滑稽な事になりますけれども……」',
                    '「それとも最奥に辿り着き、異変を起こした原因を取り除くことが、目標になりますか？」',
                    '「それには及びませんね。下手人がなんであろうと、私は負けませんから……あなたの地上に影響が及ぶことはないでしょう」',
                    '「あるいは輝石を集めて、より強い自分となる夢を見ますか？」',
                    '「ならば叶えられるでしょう、私は夢魔。夢を叶えるのが私の仕事」',
                    '「私も、あなたも、本来存在しては行けないメアリー・スー」',
                    '「ならば楽しみましょう。共に、一緒に、永遠に」',
                    '「あなたの主人が、あなたを忘れ去ってしまう、その日まで」',
                ],
            ],
        ],
        'serious_talk' => [
            'title' => '案内人に真剣な話をする',
            'scenes' => [
                'root' => [
                    'lines' => ['「まだ、何か？」'],
                    'choices' => [
                        ['key' => 'true_name', 'label' => '本名を聞く', 'next' => 'true_name'],
                        ['key' => 'embrace', 'label' => '抱き締める', 'next' => 'embrace'],
                        ['key' => 'leave', 'label' => '戻る', 'next' => 'guide'],
                    ],
                ],
                'true_name' => [
                    'lines' => [
                        '「私は、自分のことが嫌いです」',
                        '「……それに、最初に私に名前をつけたあなたの夢が覚めることになります」',
                        '「私は、一応は夢魔と名付けられた魔族のハーフです。夢が覚めることはしたくありませんね」',
                        '「どうか夢に浸ってください、私の唯一のお客様」',
                    ],
                    'choices' => [
                        ['key' => 'ask_again', 'label' => 'それでも教えて欲しい', 'next' => 'true_name_branch'],
                        ['key' => 'tell_dream', 'label' => 'あなたについて知ることが私の夢だと伝える', 'next' => 'true_name_reveal'],
                        ['key' => 'call_name', 'label' => '彼女に自分がつけた名前を呼ぶ', 'next' => 'true_name_named'],
                        ['key' => 'leave', 'label' => '立ち去る', 'next' => 'root'],
                    ],
                ],
                'true_name_branch' => [
                    'lines' => [],
                    'normal_branch' => [
                        '「……{{assigned_name}}」',
                        '「ええ、はい。　偶然一致していたのです！　なんと奇跡的な一致でしょうね♪ いひひ♪」',
                    ],
                    'true_name_branch' => [
                        '「……揶揄ってるんですかね、知ってるくせに」',
                        '「苗字のことなら、私にはありませんよ」',
                        '「なぜなら、私は魔王の一族ですから。王族には名前しかありません」',
                        '「リカという名前しか無いのです。　一時期、『自分に苗字がないのはおかしい』と本気で考えて雨宮なんてもん付け足したりしてましたけどね」',
                        '「代わりに、種族の名をつけて呼ぶことはありましたけどね」',
                        '「RIKA the Succubus……リカ＝サキュバス。おお、さむい、さむい」',
                    ],
                    'choices' => [
                        ['key' => 'leave', 'label' => '立ち去る', 'next' => 'root'],
                    ],
                ],
                'true_name_reveal' => [
                    'lines' => ['「………………」', '「リカ。」'],
                    'choices' => [
                        ['key' => 'leave', 'label' => '立ち去る', 'next' => 'root'],
                        ['key' => 'back', 'label' => '本名を聞いた後の選択に戻る', 'next' => 'true_name'],
                    ],
                ],
                'true_name_named' => [
                    'lines' => ['「そう。それでいい。」'],
                    'choices' => [
                        ['key' => 'back', 'label' => '本名を聞いた後の選択に戻る', 'next' => 'true_name'],
                    ],
                ],
                'embrace' => [
                    'lines' => [
                        '「……夢魔が、抱かれるのは慣れてます」',
                        '「それでも私があなたに魔族としての姿を見せないのは、あまりにも儚い人のために働く長命種という共通点に共感を抱いたからに他ならない」',
                        '「あるいは同情？　私は魔王ですよ？」',
                        '「まったく、それなら実に滑稽で、愚かですね」',
                    ],
                    'choices' => [
                        ['key' => 'more', 'label' => 'もっと抱き締める', 'next' => 'embrace_more'],
                        ['key' => 'leave', 'label' => '離れる', 'next' => 'embrace_leave'],
                        ['key' => 'back', 'label' => 'はじめに戻る', 'next' => 'root'],
                    ],
                ],
                'embrace_more' => [
                    'lines' => [
                        '「実に感情的ですね。エルフがそれでは、いつか心折れますよ」',
                        '「……そっち方面を期待してるなら、私も飢えてます。相手してやってもいいですが」',
                    ],
                    'choices' => [
                        ['key' => 'back', 'label' => 'はじめに戻る', 'next' => 'root'],
                    ],
                ],
                'embrace_leave' => [
                    'lines' => ['「どうも人の優しさには、慣れないものですね」'],
                    'choices' => [
                        ['key' => 'back', 'label' => 'はじめに戻る', 'next' => 'root'],
                    ],
                ],
            ],
        ],
        'history' => json_decode(file_get_contents(__DIR__.'/../resources/stories/intro.json'), true, 512, JSON_THROW_ON_ERROR),
    ],
    'battles' => [
        'tutorial' => [
            'activity_type' => 'tutorial',
            'activity_key' => 'first_descent_tutorial',
            'encounter_key' => 'tutorial_giant_rat',
            'display_name' => 'ジャイアントラット',
            'seed' => 10401,
            'max_rounds' => 30,
            'expected_winner' => 'player',
            'xp_reward' => 5,
            'shard_reward' => 0,
            'actor' => [
                'key' => 'tutorial_secretary',
                'label' => '秘書',
                'stats' => ['vitality' => 10, 'might' => 10, 'finesse' => 10, 'spirit' => 10, 'agility' => 10],
                'weapon_key' => 'tutorial_starter_knife',
                'max_hp' => 220,
                'attack' => 105,
                'defense' => 70,
                'speed' => 90,
                'available_skills' => ['quick_slash'],
            ],
            'loadout' => ['quick_slash'],
            'enemy' => [
                'key' => 'tutorial_giant_rat',
                'label' => 'ジャイアントラット',
                'role' => 'tutorial',
                'behavior' => 'standard',
                'max_hp' => 90,
                'attack' => 38,
                'defense' => 18,
                'speed' => 45,
            ],
        ],
        'scripted_loss' => [
            'activity_type' => 'story',
            'activity_key' => 'shopkeeper_special_loss',
            'encounter_key' => 'shopkeeper_scripted_loss',
            'display_name' => '（ダミー）',
            'seed' => 10402,
            'max_rounds' => 10,
            'expected_winner' => 'enemy',
            'xp_reward' => 0,
            'shard_reward' => 0,
            'actor' => [
                'key' => 'scripted_loss_secretary',
                'label' => '秘書',
                'weapon_key' => 'story_snapshot',
                'max_hp' => 40,
                'attack' => 20,
                'defense' => 0,
                'speed' => 20,
                'available_skills' => ['quick_slash'],
            ],
            'loadout' => ['quick_slash'],
            'enemy' => [
                'key' => 'shopkeeper_scripted_loss',
                'label' => '（ダミー）',
                'role' => 'scripted_loss',
                'behavior' => 'standard',
                'max_hp' => 999,
                'attack' => 500,
                'defense' => 999,
                'speed' => 200,
            ],
        ],
    ],
];
